/**
 * Generated by orval v8.0.0-rc.2 🍺
 * Do not edit manually.
 * BarkByte
 * OpenAPI spec version: 0.1.0
 */

import type {
	DataTag,
	DefinedInitialDataOptions,
	DefinedUseQueryResult,
	QueryClient,
	QueryFunction,
	QueryKey,
	UndefinedInitialDataOptions,
	UseQueryOptions,
	UseQueryResult,
} from "@tanstack/react-query";
import { useQuery } from "@tanstack/react-query";
import type { ErrorType } from "../../mutator/custom-instance";
import { customInstance } from "../../mutator/custom-instance";

/**
 * @summary Health Check
 */
export const utilsHealthCheck = (signal?: AbortSignal) => {
	return customInstance<boolean>({
		url: `/api/v1/utils/health-check/`,
		method: "GET",
		signal,
	});
};

export const getUtilsHealthCheckQueryKey = () => {
	return [`/api/v1/utils/health-check/`] as const;
};

export const getUtilsHealthCheckQueryOptions = <
	TData = Awaited<ReturnType<typeof utilsHealthCheck>>,
	TError = ErrorType<unknown>,
>(options?: {
	query?: Partial<
		UseQueryOptions<Awaited<ReturnType<typeof utilsHealthCheck>>, TError, TData>
	>;
}) => {
	const { query: queryOptions } = options ?? {};

	const queryKey = queryOptions?.queryKey ?? getUtilsHealthCheckQueryKey();

	const queryFn: QueryFunction<
		Awaited<ReturnType<typeof utilsHealthCheck>>
	> = ({ signal }) => utilsHealthCheck(signal);

	return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
		Awaited<ReturnType<typeof utilsHealthCheck>>,
		TError,
		TData
	> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type UtilsHealthCheckQueryResult = NonNullable<
	Awaited<ReturnType<typeof utilsHealthCheck>>
>;
export type UtilsHealthCheckQueryError = ErrorType<unknown>;

export function useUtilsHealthCheck<
	TData = Awaited<ReturnType<typeof utilsHealthCheck>>,
	TError = ErrorType<unknown>,
>(
	options: {
		query: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof utilsHealthCheck>>,
				TError,
				TData
			>
		> &
			Pick<
				DefinedInitialDataOptions<
					Awaited<ReturnType<typeof utilsHealthCheck>>,
					TError,
					Awaited<ReturnType<typeof utilsHealthCheck>>
				>,
				"initialData"
			>;
	},
	queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useUtilsHealthCheck<
	TData = Awaited<ReturnType<typeof utilsHealthCheck>>,
	TError = ErrorType<unknown>,
>(
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof utilsHealthCheck>>,
				TError,
				TData
			>
		> &
			Pick<
				UndefinedInitialDataOptions<
					Awaited<ReturnType<typeof utilsHealthCheck>>,
					TError,
					Awaited<ReturnType<typeof utilsHealthCheck>>
				>,
				"initialData"
			>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useUtilsHealthCheck<
	TData = Awaited<ReturnType<typeof utilsHealthCheck>>,
	TError = ErrorType<unknown>,
>(
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof utilsHealthCheck>>,
				TError,
				TData
			>
		>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Health Check
 */

export function useUtilsHealthCheck<
	TData = Awaited<ReturnType<typeof utilsHealthCheck>>,
	TError = ErrorType<unknown>,
>(
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof utilsHealthCheck>>,
				TError,
				TData
			>
		>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
} {
	const queryOptions = getUtilsHealthCheckQueryOptions(options);

	const query = useQuery(queryOptions, queryClient) as UseQueryResult<
		TData,
		TError
	> & { queryKey: DataTag<QueryKey, TData, TError> };

	query.queryKey = queryOptions.queryKey;

	return query;
}
