/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Timverse
 * OpenAPI spec version: 1.2.0
 */
import * as zod from "zod";

/**
 * @summary Health Check
 */
export const UtilsHealthCheckResponse = zod.boolean();
