/**
 * Generated by orval v8.0.0-rc.2 🍺
 * Do not edit manually.
 * BarkByte
 * OpenAPI spec version: 0.1.0
 */

import type {
	DataTag,
	DefinedInitialDataOptions,
	DefinedUseQueryResult,
	QueryClient,
	QueryFunction,
	QueryKey,
	UndefinedInitialDataOptions,
	UseQueryOptions,
	UseQueryResult,
} from "@tanstack/react-query";
import { useQuery } from "@tanstack/react-query";

/**
 * @summary Health Check
 */
export type utilsHealthCheckResponse200 = {
	data: boolean;
	status: 200;
};

export type utilsHealthCheckResponseSuccess = utilsHealthCheckResponse200 & {
	headers: Headers;
};

export type utilsHealthCheckResponse = utilsHealthCheckResponseSuccess;

export const getUtilsHealthCheckUrl = () => {
	return `/api/v1/utils/health-check/`;
};

export const utilsHealthCheck = async (
	options?: RequestInit,
): Promise<utilsHealthCheckResponse> => {
	const res = await fetch(getUtilsHealthCheckUrl(), {
		...options,
		method: "GET",
	});

	const body = [204, 205, 304].includes(res.status) ? null : await res.text();

	const data: utilsHealthCheckResponse["data"] = body ? JSON.parse(body) : {};
	return {
		data,
		status: res.status,
		headers: res.headers,
	} as utilsHealthCheckResponse;
};

export const getUtilsHealthCheckQueryKey = () => {
	return [`/api/v1/utils/health-check/`] as const;
};

export const getUtilsHealthCheckQueryOptions = <
	TData = Awaited<ReturnType<typeof utilsHealthCheck>>,
	TError = unknown,
>(options?: {
	query?: Partial<
		UseQueryOptions<Awaited<ReturnType<typeof utilsHealthCheck>>, TError, TData>
	>;
	fetch?: RequestInit;
}) => {
	const { query: queryOptions, fetch: fetchOptions } = options ?? {};

	const queryKey = queryOptions?.queryKey ?? getUtilsHealthCheckQueryKey();

	const queryFn: QueryFunction<
		Awaited<ReturnType<typeof utilsHealthCheck>>
	> = ({ signal }) => utilsHealthCheck({ signal, ...fetchOptions });

	return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
		Awaited<ReturnType<typeof utilsHealthCheck>>,
		TError,
		TData
	> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type UtilsHealthCheckQueryResult = NonNullable<
	Awaited<ReturnType<typeof utilsHealthCheck>>
>;
export type UtilsHealthCheckQueryError = unknown;

export function useUtilsHealthCheck<
	TData = Awaited<ReturnType<typeof utilsHealthCheck>>,
	TError = unknown,
>(
	options: {
		query: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof utilsHealthCheck>>,
				TError,
				TData
			>
		> &
			Pick<
				DefinedInitialDataOptions<
					Awaited<ReturnType<typeof utilsHealthCheck>>,
					TError,
					Awaited<ReturnType<typeof utilsHealthCheck>>
				>,
				"initialData"
			>;
		fetch?: RequestInit;
	},
	queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useUtilsHealthCheck<
	TData = Awaited<ReturnType<typeof utilsHealthCheck>>,
	TError = unknown,
>(
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof utilsHealthCheck>>,
				TError,
				TData
			>
		> &
			Pick<
				UndefinedInitialDataOptions<
					Awaited<ReturnType<typeof utilsHealthCheck>>,
					TError,
					Awaited<ReturnType<typeof utilsHealthCheck>>
				>,
				"initialData"
			>;
		fetch?: RequestInit;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useUtilsHealthCheck<
	TData = Awaited<ReturnType<typeof utilsHealthCheck>>,
	TError = unknown,
>(
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof utilsHealthCheck>>,
				TError,
				TData
			>
		>;
		fetch?: RequestInit;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Health Check
 */

export function useUtilsHealthCheck<
	TData = Awaited<ReturnType<typeof utilsHealthCheck>>,
	TError = unknown,
>(
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof utilsHealthCheck>>,
				TError,
				TData
			>
		>;
		fetch?: RequestInit;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
} {
	const queryOptions = getUtilsHealthCheckQueryOptions(options);

	const query = useQuery(queryOptions, queryClient) as UseQueryResult<
		TData,
		TError
	> & { queryKey: DataTag<QueryKey, TData, TError> };

	query.queryKey = queryOptions.queryKey;

	return query;
}
