/**
 * Generated by orval v8.0.0-rc.2 🍺
 * Do not edit manually.
 * BarkByte
 * OpenAPI spec version: 0.1.0
 */
import * as zod from "zod";

/**
 * Retrieve a list of dois.
 * @summary Get Dois
 */
export const doiGetDoisQuerySkipDefault = 0;
export const doiGetDoisQueryLimitDefault = 100;

export const doiGetDoisQueryParams = zod.object({
	skip: zod.number().default(doiGetDoisQuerySkipDefault),
	limit: zod.number().default(doiGetDoisQueryLimitDefault),
});

export const doiGetDoisResponse = zod.object({
	count: zod.number(),
	data: zod.array(
		zod
			.object({
				authors: zod.string(),
				id: zod.uuid(),
				link: zod.string(),
				pub_year: zod.number(),
				ref_title: zod.string(),
			})
			.describe("What you return via API."),
	),
});

/**
 * Create DOI.
 * @summary Create Doi
 */
export const doiCreateDoiBody = zod.object({
	authors: zod.string(),
	link: zod.string(),
	pub_year: zod.number(),
	ref_title: zod.string(),
});

export const doiCreateDoiResponse = zod
	.object({
		authors: zod.string(),
		id: zod.uuid(),
		link: zod.string(),
		pub_year: zod.number(),
		ref_title: zod.string(),
	})
	.describe("What you return via API.");

/**
 * Delete joinery type ONLY if not in use.
 * @summary Delete Doi
 */
export const doiDeleteDoiParams = zod.object({
	id: zod.uuid(),
});

export const doiDeleteDoiResponse = zod.unknown();

/**
 * Retrieve a specific doi, including its specimens.
 * @summary Get Doi By Id
 */
export const doiGetDoiByIdParams = zod.object({
	id: zod.uuid(),
});

export const doiGetDoiByIdResponseSpecimensDataItemDoiAuthorsMax = 255;

export const doiGetDoiByIdResponseSpecimensDataItemDoiLinkMax = 255;

export const doiGetDoiByIdResponseSpecimensDataItemDoiRefTitleMax = 255;

export const doiGetDoiByIdResponseSpecimensDataItemEQualitativeFailureMeasureItemLabelMax = 255;

export const doiGetDoiByIdResponseSpecimensDataItemFastenerTypesItemLabelMax = 255;

export const doiGetDoiByIdResponseSpecimensDataItemJoineryTypeLabelMax = 255;

export const doiGetDoiByIdResponseSpecimensDataItemLoadingDirectionsItemLabelMax = 255;

export const doiGetDoiByIdResponseSpecimensDataItemSubJoineryTypeLabelMax = 255;

export const doiGetDoiByIdResponse = zod.object({
	authors: zod.string(),
	id: zod.uuid(),
	link: zod.string(),
	pub_year: zod.number(),
	ref_title: zod.string(),
	specimens: zod.object({
		count: zod.number(),
		data: zod.array(
			zod.object({
				assembly_type: zod.enum([
					"Wall-Floor",
					"Wall-Wall",
					"Wall-Floor & Wall-Wall",
				]),
				connection_description: zod.string(),
				connector: zod.boolean(),
				connector_mechanical_properties: zod
					.union([zod.string(), zod.null()])
					.optional(),
				doi: zod.object({
					authors: zod
						.string()
						.min(1)
						.max(doiGetDoiByIdResponseSpecimensDataItemDoiAuthorsMax),
					id: zod.uuid().optional(),
					link: zod
						.string()
						.min(1)
						.max(doiGetDoiByIdResponseSpecimensDataItemDoiLinkMax),
					pub_year: zod.number(),
					ref_title: zod
						.string()
						.min(1)
						.max(doiGetDoiByIdResponseSpecimensDataItemDoiRefTitleMax),
				}),
				dowel: zod.boolean(),
				e_date: zod.union([zod.string(), zod.null()]).optional(),
				e_ductility: zod.union([zod.number(), zod.null()]).optional(),
				e_max_displacement: zod.union([zod.number(), zod.null()]).optional(),
				e_max_force: zod.union([zod.number(), zod.null()]).optional(),
				e_measurement_unit: zod.union([zod.string(), zod.null()]).optional(),
				e_qfm_description: zod.union([zod.string(), zod.null()]).optional(),
				e_qualitative_failure_measure: zod.array(
					zod.object({
						id: zod.uuid().optional(),
						label: zod
							.string()
							.min(1)
							.max(
								doiGetDoiByIdResponseSpecimensDataItemEQualitativeFailureMeasureItemLabelMax,
							),
						type: zod.enum(["WOOD", "DOWEL", "CONNECTOR", "OTHER"]),
					}),
				),
				e_stiffness: zod.union([zod.number(), zod.null()]).optional(),
				e_test_loading_type: zod
					.union([
						zod.enum(["Cyclic", "Monotonic", "Monotonic and Cyclic"]),
						zod.null(),
					])
					.optional(),
				e_ultimate_displacement: zod
					.union([zod.number(), zod.null()])
					.optional(),
				e_ultimate_force: zod.union([zod.number(), zod.null()]).optional(),
				e_yield_displacement: zod.union([zod.number(), zod.null()]).optional(),
				e_yield_force: zod.union([zod.number(), zod.null()]).optional(),
				e_yield_point_method: zod
					.union([zod.enum(["CEN 1/6", "EEEP", "FEMA P795"]), zod.null()])
					.optional(),
				element_dimension: zod.string(),
				fastener_mechanical_properties: zod
					.union([zod.string(), zod.null()])
					.optional(),
				fastener_numbers: zod.number(),
				fastener_types: zod.array(
					zod.object({
						id: zod.uuid().optional(),
						label: zod
							.string()
							.min(1)
							.max(
								doiGetDoiByIdResponseSpecimensDataItemFastenerTypesItemLabelMax,
							),
					}),
				),
				id: zod.uuid(),
				joinery_type: zod.object({
					has_dowel: zod.boolean(),
					id: zod.uuid().optional(),
					label: zod
						.string()
						.min(1)
						.max(doiGetDoiByIdResponseSpecimensDataItemJoineryTypeLabelMax),
				}),
				loading_directions: zod.array(
					zod.object({
						id: zod.uuid().optional(),
						label: zod
							.string()
							.min(1)
							.max(
								doiGetDoiByIdResponseSpecimensDataItemLoadingDirectionsItemLabelMax,
							),
					}),
				),
				moisture_percentage: zod.string(),
				note: zod.union([zod.string(), zod.null()]).optional(),
				practice: zod.enum(["Conventional", "Research and Development"]),
				replicate_tests: zod.number(),
				specimen_reference_id: zod.string(),
				sub_joinery_type: zod.object({
					id: zod.uuid().optional(),
					joinery_type_id: zod.uuid(),
					label: zod
						.string()
						.min(1)
						.max(doiGetDoiByIdResponseSpecimensDataItemSubJoineryTypeLabelMax),
				}),
				uploader_id: zod.uuid(),
				wood_mechanical_properties: zod
					.union([zod.string(), zod.null()])
					.optional(),
				wood_type: zod.union([zod.string(), zod.null()]).optional(),
			}),
		),
	}),
});

/**
 * Create doi.
 * @summary Update Doi
 */
export const doiUpdateDoiParams = zod.object({
	id: zod.uuid(),
});

export const doiUpdateDoiBody = zod.object({
	authors: zod.string(),
	link: zod.string(),
	pub_year: zod.number(),
	ref_title: zod.string(),
});

export const doiUpdateDoiResponse = zod
	.object({
		authors: zod.string(),
		id: zod.uuid(),
		link: zod.string(),
		pub_year: zod.number(),
		ref_title: zod.string(),
	})
	.describe("What you return via API.");
