/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * BarkByte
 * OpenAPI spec version: 1.1.0
 */
import * as zod from "zod";

/**
 * Retrieve a list of dois.
 * @summary Get Dois
 */
export const doiGetDoisQuerySkipDefault = 0;
export const doiGetDoisQueryLimitDefault = 100;

export const DoiGetDoisQueryParams = zod.object({
	skip: zod.number().default(doiGetDoisQuerySkipDefault),
	limit: zod.number().default(doiGetDoisQueryLimitDefault),
});

export const DoiGetDoisResponse = zod.object({
	data: zod.array(
		zod
			.object({
				link: zod.string(),
				ref_title: zod.string(),
				authors: zod.string(),
				pub_year: zod.number(),
				id: zod.uuid(),
			})
			.describe("What you return via API."),
	),
	count: zod.number(),
});

/**
 * Create DOI.
 * @summary Create Doi
 */
export const DoiCreateDoiBody = zod.object({
	link: zod.string(),
	ref_title: zod.string(),
	authors: zod.string(),
	pub_year: zod.number(),
});

export const DoiCreateDoiResponse = zod
	.object({
		link: zod.string(),
		ref_title: zod.string(),
		authors: zod.string(),
		pub_year: zod.number(),
		id: zod.uuid(),
	})
	.describe("What you return via API.");

/**
 * Retrieve a specific doi, including its specimens.
 * @summary Get Doi By Id
 */
export const DoiGetDoiByIdParams = zod.object({
	id: zod.uuid(),
});

export const doiGetDoiByIdResponseSpecimensDataItemElementDimensionMax = 1000;

export const doiGetDoiByIdResponseSpecimensDataItemDoiLinkMax = 255;

export const doiGetDoiByIdResponseSpecimensDataItemDoiRefTitleMax = 255;

export const doiGetDoiByIdResponseSpecimensDataItemDoiAuthorsMax = 255;

export const doiGetDoiByIdResponseSpecimensDataItemJoineryTypeLabelMax = 255;

export const doiGetDoiByIdResponseSpecimensDataItemSubJoineryTypeLabelMax = 255;

export const doiGetDoiByIdResponseSpecimensDataItemEQualitativeFailureMeasureItemLabelMax = 255;

export const doiGetDoiByIdResponseSpecimensDataItemFastenerTypesItemLabelMax = 255;

export const doiGetDoiByIdResponseSpecimensDataItemLoadingDirectionsItemLabelMax = 255;

export const DoiGetDoiByIdResponse = zod.object({
	link: zod.string(),
	ref_title: zod.string(),
	authors: zod.string(),
	pub_year: zod.number(),
	id: zod.uuid(),
	specimens: zod.object({
		data: zod.array(
			zod.object({
				specimen_reference_id: zod.string(),
				replicate_tests: zod.number(),
				note: zod.union([zod.string(), zod.null()]).optional(),
				dowel: zod.boolean(),
				connector: zod.boolean(),
				assembly_type: zod.enum([
					"Wall-Floor",
					"Wall-Wall",
					"Wall-Floor & Wall-Wall",
				]),
				practice: zod.enum(["Conventional", "Research and Development"]),
				connection_description: zod
					.union([zod.string(), zod.null()])
					.optional(),
				element_dimension: zod
					.string()
					.max(doiGetDoiByIdResponseSpecimensDataItemElementDimensionMax),
				fastener_numbers: zod.number(),
				moisture_percentage: zod.union([zod.string(), zod.null()]).optional(),
				wood_type: zod.union([zod.string(), zod.null()]).optional(),
				wood_mechanical_properties: zod
					.union([zod.string(), zod.null()])
					.optional(),
				connector_mechanical_properties: zod
					.union([zod.string(), zod.null()])
					.optional(),
				fastener_mechanical_properties: zod
					.union([zod.string(), zod.null()])
					.optional(),
				e_date: zod.union([zod.string(), zod.null()]).optional(),
				e_test_loading_type: zod.enum([
					"Cyclic",
					"Monotonic",
					"Monotonic and Cyclic",
				]),
				e_yield_point_method: zod.enum(["CEN 1/6", "EEEP"]),
				e_stiffness: zod.number(),
				e_yield_displacement: zod.number(),
				e_yield_force: zod.number(),
				e_max_displacement: zod.number(),
				e_max_force: zod.number(),
				e_ultimate_displacement: zod.number(),
				e_ultimate_force: zod.number(),
				e_ductility: zod.number(),
				e_qfm_description: zod.union([zod.string(), zod.null()]).optional(),
				id: zod.uuid(),
				uploader_id: zod.uuid(),
				doi: zod.object({
					id: zod.uuid().optional(),
					link: zod
						.string()
						.min(1)
						.max(doiGetDoiByIdResponseSpecimensDataItemDoiLinkMax),
					ref_title: zod
						.string()
						.min(1)
						.max(doiGetDoiByIdResponseSpecimensDataItemDoiRefTitleMax),
					authors: zod
						.string()
						.min(1)
						.max(doiGetDoiByIdResponseSpecimensDataItemDoiAuthorsMax),
					pub_year: zod.number(),
				}),
				joinery_type: zod.object({
					id: zod.uuid().optional(),
					label: zod
						.string()
						.min(1)
						.max(doiGetDoiByIdResponseSpecimensDataItemJoineryTypeLabelMax),
					has_dowel: zod.boolean(),
				}),
				sub_joinery_type: zod.object({
					id: zod.uuid().optional(),
					joinery_type_id: zod.uuid(),
					label: zod
						.string()
						.min(1)
						.max(doiGetDoiByIdResponseSpecimensDataItemSubJoineryTypeLabelMax),
				}),
				e_qualitative_failure_measure: zod.array(
					zod.object({
						id: zod.uuid().optional(),
						label: zod
							.string()
							.min(1)
							.max(
								doiGetDoiByIdResponseSpecimensDataItemEQualitativeFailureMeasureItemLabelMax,
							),
						type: zod.enum(["WOOD", "DOWEL", "CONNECTOR", "OTHER"]),
					}),
				),
				fastener_types: zod.array(
					zod.object({
						id: zod.uuid().optional(),
						label: zod
							.string()
							.min(1)
							.max(
								doiGetDoiByIdResponseSpecimensDataItemFastenerTypesItemLabelMax,
							),
					}),
				),
				loading_directions: zod.array(
					zod.object({
						id: zod.uuid().optional(),
						label: zod
							.string()
							.min(1)
							.max(
								doiGetDoiByIdResponseSpecimensDataItemLoadingDirectionsItemLabelMax,
							),
					}),
				),
			}),
		),
		count: zod.number(),
	}),
});

/**
 * Create doi.
 * @summary Update Doi
 */
export const DoiUpdateDoiParams = zod.object({
	id: zod.uuid(),
});

export const DoiUpdateDoiBody = zod.object({
	link: zod.string(),
	ref_title: zod.string(),
	authors: zod.string(),
	pub_year: zod.number(),
});

export const DoiUpdateDoiResponse = zod
	.object({
		link: zod.string(),
		ref_title: zod.string(),
		authors: zod.string(),
		pub_year: zod.number(),
		id: zod.uuid(),
	})
	.describe("What you return via API.");

/**
 * Delete joinery type ONLY if not in use.
 * @summary Delete Doi
 */
export const DoiDeleteDoiParams = zod.object({
	id: zod.uuid(),
});

export const DoiDeleteDoiResponse = zod.unknown();
