/**
 * Generated by orval v8.0.0-rc.2 🍺
 * Do not edit manually.
 * BarkByte
 * OpenAPI spec version: 0.1.0
 */
import * as zod from "zod";

/**
 * Retrieve users.
 * @summary Read Users
 */
export const usersReadUsersQuerySkipDefault = 0;
export const usersReadUsersQueryLimitDefault = 100;

export const usersReadUsersQueryParams = zod.object({
	skip: zod.number().default(usersReadUsersQuerySkipDefault),
	limit: zod.number().default(usersReadUsersQueryLimitDefault),
});

export const usersReadUsersResponse = zod.object({
	count: zod.number(),
	data: zod.array(
		zod.object({
			email: zod.email(),
			full_name: zod.union([zod.string(), zod.null()]).optional(),
			id: zod.uuid(),
			is_active: zod.boolean(),
			is_superuser: zod.boolean(),
		}),
	),
});

/**
 * Create new user.
 * @summary Create User
 */
export const usersCreateUserBodyPasswordMin = 8;
export const usersCreateUserBodyPasswordMax = 64;

export const usersCreateUserBody = zod.object({
	email: zod.email(),
	full_name: zod.union([zod.string(), zod.null()]).optional(),
	is_active: zod.boolean(),
	is_superuser: zod.boolean(),
	password: zod
		.string()
		.min(usersCreateUserBodyPasswordMin)
		.max(usersCreateUserBodyPasswordMax),
});

export const usersCreateUserResponse = zod.object({
	email: zod.email(),
	full_name: zod.union([zod.string(), zod.null()]).optional(),
	id: zod.uuid(),
	is_active: zod.boolean(),
	is_superuser: zod.boolean(),
});

/**
 * Delete own user.
 * @summary Delete User Me
 */
export const usersDeleteUserMeResponse = zod.object({
	message: zod.string(),
});

/**
 * Get current user.
 * @summary Read User Me
 */
export const usersReadUserMeResponse = zod.object({
	email: zod.email(),
	full_name: zod.union([zod.string(), zod.null()]).optional(),
	id: zod.uuid(),
	is_active: zod.boolean(),
	is_superuser: zod.boolean(),
});

/**
 * Update own user.
 * @summary Update User Me
 */
export const usersUpdateUserMeBodyEmailOneMax = 255;

export const usersUpdateUserMeBodyFullNameOneMax = 255;

export const usersUpdateUserMeBody = zod.object({
	email: zod
		.union([zod.email().max(usersUpdateUserMeBodyEmailOneMax), zod.null()])
		.optional(),
	full_name: zod
		.union([zod.string().max(usersUpdateUserMeBodyFullNameOneMax), zod.null()])
		.optional(),
	is_active: zod.union([zod.boolean(), zod.null()]).optional(),
});

export const usersUpdateUserMeResponse = zod.object({
	email: zod.email(),
	full_name: zod.union([zod.string(), zod.null()]).optional(),
	id: zod.uuid(),
	is_active: zod.boolean(),
	is_superuser: zod.boolean(),
});

/**
 * Update own password.
 * @summary Update Password Me
 */
export const usersUpdatePasswordMeBodyCurrentPasswordMin = 8;
export const usersUpdatePasswordMeBodyCurrentPasswordMax = 64;

export const usersUpdatePasswordMeBodyNewPasswordMin = 8;
export const usersUpdatePasswordMeBodyNewPasswordMax = 64;

export const usersUpdatePasswordMeBody = zod.object({
	current_password: zod
		.string()
		.min(usersUpdatePasswordMeBodyCurrentPasswordMin)
		.max(usersUpdatePasswordMeBodyCurrentPasswordMax),
	new_password: zod
		.string()
		.min(usersUpdatePasswordMeBodyNewPasswordMin)
		.max(usersUpdatePasswordMeBodyNewPasswordMax),
});

export const usersUpdatePasswordMeResponse = zod.object({
	message: zod.string(),
});

/**
 * Create new user without the need to be logged in.
 * @summary Register User
 */
export const usersRegisterUserBodyEmailMax = 255;

export const usersRegisterUserBodyFullNameOneMax = 255;

export const usersRegisterUserBodyPasswordMin = 8;
export const usersRegisterUserBodyPasswordMax = 64;

export const usersRegisterUserBody = zod.object({
	email: zod.email().max(usersRegisterUserBodyEmailMax),
	full_name: zod
		.union([zod.string().max(usersRegisterUserBodyFullNameOneMax), zod.null()])
		.optional(),
	password: zod
		.string()
		.min(usersRegisterUserBodyPasswordMin)
		.max(usersRegisterUserBodyPasswordMax),
});

export const usersRegisterUserResponse = zod.object({
	message: zod.string(),
});

/**
 * verify email and reset password.
 * @summary Verify Email
 */
export const usersVerifyEmailBody = zod.object({
	token: zod.string(),
});

export const usersVerifyEmailResponse = zod.object({
	message: zod.string(),
});

/**
 * Delete a user.
 * @summary Delete User
 */
export const usersDeleteUserParams = zod.object({
	user_id: zod.uuid(),
});

export const usersDeleteUserResponse = zod.object({
	message: zod.string(),
});

/**
 * Get a specific user by id.
 * @summary Read User By Id
 */
export const usersReadUserByIdParams = zod.object({
	user_id: zod.uuid(),
});

export const usersReadUserByIdResponse = zod.object({
	email: zod.email(),
	full_name: zod.union([zod.string(), zod.null()]).optional(),
	id: zod.uuid(),
	is_active: zod.boolean(),
	is_superuser: zod.boolean(),
});

/**
 * Update a user.
 * @summary Update User
 */
export const usersUpdateUserParams = zod.object({
	user_id: zod.uuid(),
});

export const usersUpdateUserBodyEmailOneMax = 255;

export const usersUpdateUserBody = zod.object({
	email: zod
		.union([zod.email().max(usersUpdateUserBodyEmailOneMax), zod.null()])
		.optional(),
	full_name: zod.union([zod.string(), zod.null()]).optional(),
	is_active: zod.union([zod.boolean(), zod.null()]).optional(),
	is_superuser: zod.union([zod.boolean(), zod.null()]).optional(),
});

export const usersUpdateUserResponse = zod.object({
	email: zod.email(),
	full_name: zod.union([zod.string(), zod.null()]).optional(),
	id: zod.uuid(),
	is_active: zod.boolean(),
	is_superuser: zod.boolean(),
});
