/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Timverse
 * OpenAPI spec version: 0.1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  HTTPValidationError,
  Message,
  NewAccount,
  UpdatePassword,
  UserCreate,
  UserPublic,
  UserRegister,
  UserUpdate,
  UserUpdateMe,
  UsersPublic,
  UsersReadUsersParams
} from '../../model';

import { customInstance } from '../../mutator/custom-instance';
import type { ErrorType } from '../../mutator/custom-instance';




/**
 * Get current user.
 * @summary Read User Me
 */
export const usersReadUserMe = (
    
 signal?: AbortSignal
) => {
      
      
      return customInstance<UserPublic>(
      {url: `/api/v1/users/me`, method: 'GET', signal
    },
      );
    }
  



export const getUsersReadUserMeQueryKey = () => {
    return [
    `/api/v1/users/me`
    ] as const;
    }

    
export const getUsersReadUserMeQueryOptions = <TData = Awaited<ReturnType<typeof usersReadUserMe>>, TError = ErrorType<unknown>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof usersReadUserMe>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getUsersReadUserMeQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof usersReadUserMe>>> = ({ signal }) => usersReadUserMe(signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof usersReadUserMe>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type UsersReadUserMeQueryResult = NonNullable<Awaited<ReturnType<typeof usersReadUserMe>>>
export type UsersReadUserMeQueryError = ErrorType<unknown>


export function useUsersReadUserMe<TData = Awaited<ReturnType<typeof usersReadUserMe>>, TError = ErrorType<unknown>>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof usersReadUserMe>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof usersReadUserMe>>,
          TError,
          Awaited<ReturnType<typeof usersReadUserMe>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useUsersReadUserMe<TData = Awaited<ReturnType<typeof usersReadUserMe>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof usersReadUserMe>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof usersReadUserMe>>,
          TError,
          Awaited<ReturnType<typeof usersReadUserMe>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useUsersReadUserMe<TData = Awaited<ReturnType<typeof usersReadUserMe>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof usersReadUserMe>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Read User Me
 */

export function useUsersReadUserMe<TData = Awaited<ReturnType<typeof usersReadUserMe>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof usersReadUserMe>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getUsersReadUserMeQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * Delete own user.
 * @summary Delete User Me
 */
export const usersDeleteUserMe = (
    
 signal?: AbortSignal
) => {
      
      
      return customInstance<Message>(
      {url: `/api/v1/users/me`, method: 'DELETE', signal
    },
      );
    }
  


export const getUsersDeleteUserMeMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof usersDeleteUserMe>>, TError,void, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof usersDeleteUserMe>>, TError,void, TContext> => {

const mutationKey = ['usersDeleteUserMe'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof usersDeleteUserMe>>, void> = () => {
          

          return  usersDeleteUserMe()
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type UsersDeleteUserMeMutationResult = NonNullable<Awaited<ReturnType<typeof usersDeleteUserMe>>>
    
    export type UsersDeleteUserMeMutationError = ErrorType<unknown>

    /**
 * @summary Delete User Me
 */
export const useUsersDeleteUserMe = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof usersDeleteUserMe>>, TError,void, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof usersDeleteUserMe>>,
        TError,
        void,
        TContext
      > => {
      return useMutation(getUsersDeleteUserMeMutationOptions(options), queryClient);
    }
    /**
 * Update own user.
 * @summary Update User Me
 */
export const usersUpdateUserMe = (
    userUpdateMe: UserUpdateMe,
 signal?: AbortSignal
) => {
      
      
      return customInstance<UserPublic>(
      {url: `/api/v1/users/me`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: userUpdateMe, signal
    },
      );
    }
  


export const getUsersUpdateUserMeMutationOptions = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof usersUpdateUserMe>>, TError,{data: UserUpdateMe}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof usersUpdateUserMe>>, TError,{data: UserUpdateMe}, TContext> => {

const mutationKey = ['usersUpdateUserMe'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof usersUpdateUserMe>>, {data: UserUpdateMe}> = (props) => {
          const {data} = props ?? {};

          return  usersUpdateUserMe(data,)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type UsersUpdateUserMeMutationResult = NonNullable<Awaited<ReturnType<typeof usersUpdateUserMe>>>
    export type UsersUpdateUserMeMutationBody = UserUpdateMe
    export type UsersUpdateUserMeMutationError = ErrorType<HTTPValidationError>

    /**
 * @summary Update User Me
 */
export const useUsersUpdateUserMe = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof usersUpdateUserMe>>, TError,{data: UserUpdateMe}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof usersUpdateUserMe>>,
        TError,
        {data: UserUpdateMe},
        TContext
      > => {
      return useMutation(getUsersUpdateUserMeMutationOptions(options), queryClient);
    }
    /**
 * Update own password.
 * @summary Update Password Me
 */
export const usersUpdatePasswordMe = (
    updatePassword: UpdatePassword,
 signal?: AbortSignal
) => {
      
      
      return customInstance<Message>(
      {url: `/api/v1/users/me/password`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: updatePassword, signal
    },
      );
    }
  


export const getUsersUpdatePasswordMeMutationOptions = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof usersUpdatePasswordMe>>, TError,{data: UpdatePassword}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof usersUpdatePasswordMe>>, TError,{data: UpdatePassword}, TContext> => {

const mutationKey = ['usersUpdatePasswordMe'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof usersUpdatePasswordMe>>, {data: UpdatePassword}> = (props) => {
          const {data} = props ?? {};

          return  usersUpdatePasswordMe(data,)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type UsersUpdatePasswordMeMutationResult = NonNullable<Awaited<ReturnType<typeof usersUpdatePasswordMe>>>
    export type UsersUpdatePasswordMeMutationBody = UpdatePassword
    export type UsersUpdatePasswordMeMutationError = ErrorType<HTTPValidationError>

    /**
 * @summary Update Password Me
 */
export const useUsersUpdatePasswordMe = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof usersUpdatePasswordMe>>, TError,{data: UpdatePassword}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof usersUpdatePasswordMe>>,
        TError,
        {data: UpdatePassword},
        TContext
      > => {
      return useMutation(getUsersUpdatePasswordMeMutationOptions(options), queryClient);
    }
    /**
 * Retrieve users.
 * @summary Read Users
 */
export const usersReadUsers = (
    params?: UsersReadUsersParams,
 signal?: AbortSignal
) => {
      
      
      return customInstance<UsersPublic>(
      {url: `/api/v1/users/`, method: 'GET',
        params, signal
    },
      );
    }
  



export const getUsersReadUsersQueryKey = (params?: UsersReadUsersParams,) => {
    return [
    `/api/v1/users/`, ...(params ? [params] : [])
    ] as const;
    }

    
export const getUsersReadUsersQueryOptions = <TData = Awaited<ReturnType<typeof usersReadUsers>>, TError = ErrorType<HTTPValidationError>>(params?: UsersReadUsersParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof usersReadUsers>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getUsersReadUsersQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof usersReadUsers>>> = ({ signal }) => usersReadUsers(params, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof usersReadUsers>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type UsersReadUsersQueryResult = NonNullable<Awaited<ReturnType<typeof usersReadUsers>>>
export type UsersReadUsersQueryError = ErrorType<HTTPValidationError>


export function useUsersReadUsers<TData = Awaited<ReturnType<typeof usersReadUsers>>, TError = ErrorType<HTTPValidationError>>(
 params: undefined |  UsersReadUsersParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof usersReadUsers>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof usersReadUsers>>,
          TError,
          Awaited<ReturnType<typeof usersReadUsers>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useUsersReadUsers<TData = Awaited<ReturnType<typeof usersReadUsers>>, TError = ErrorType<HTTPValidationError>>(
 params?: UsersReadUsersParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof usersReadUsers>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof usersReadUsers>>,
          TError,
          Awaited<ReturnType<typeof usersReadUsers>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useUsersReadUsers<TData = Awaited<ReturnType<typeof usersReadUsers>>, TError = ErrorType<HTTPValidationError>>(
 params?: UsersReadUsersParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof usersReadUsers>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Read Users
 */

export function useUsersReadUsers<TData = Awaited<ReturnType<typeof usersReadUsers>>, TError = ErrorType<HTTPValidationError>>(
 params?: UsersReadUsersParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof usersReadUsers>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getUsersReadUsersQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * Create new user.
 * @summary Create User
 */
export const usersCreateUser = (
    userCreate: UserCreate,
 signal?: AbortSignal
) => {
      
      
      return customInstance<UserPublic>(
      {url: `/api/v1/users/`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: userCreate, signal
    },
      );
    }
  


export const getUsersCreateUserMutationOptions = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof usersCreateUser>>, TError,{data: UserCreate}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof usersCreateUser>>, TError,{data: UserCreate}, TContext> => {

const mutationKey = ['usersCreateUser'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof usersCreateUser>>, {data: UserCreate}> = (props) => {
          const {data} = props ?? {};

          return  usersCreateUser(data,)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type UsersCreateUserMutationResult = NonNullable<Awaited<ReturnType<typeof usersCreateUser>>>
    export type UsersCreateUserMutationBody = UserCreate
    export type UsersCreateUserMutationError = ErrorType<HTTPValidationError>

    /**
 * @summary Create User
 */
export const useUsersCreateUser = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof usersCreateUser>>, TError,{data: UserCreate}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof usersCreateUser>>,
        TError,
        {data: UserCreate},
        TContext
      > => {
      return useMutation(getUsersCreateUserMutationOptions(options), queryClient);
    }
    /**
 * Get a specific user by id.
 * @summary Read User By Id
 */
export const usersReadUserById = (
    userId: string,
 signal?: AbortSignal
) => {
      
      
      return customInstance<UserPublic>(
      {url: `/api/v1/users/${userId}`, method: 'GET', signal
    },
      );
    }
  



export const getUsersReadUserByIdQueryKey = (userId: string,) => {
    return [
    `/api/v1/users/${userId}`
    ] as const;
    }

    
export const getUsersReadUserByIdQueryOptions = <TData = Awaited<ReturnType<typeof usersReadUserById>>, TError = ErrorType<HTTPValidationError>>(userId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof usersReadUserById>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getUsersReadUserByIdQueryKey(userId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof usersReadUserById>>> = ({ signal }) => usersReadUserById(userId, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(userId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof usersReadUserById>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type UsersReadUserByIdQueryResult = NonNullable<Awaited<ReturnType<typeof usersReadUserById>>>
export type UsersReadUserByIdQueryError = ErrorType<HTTPValidationError>


export function useUsersReadUserById<TData = Awaited<ReturnType<typeof usersReadUserById>>, TError = ErrorType<HTTPValidationError>>(
 userId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof usersReadUserById>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof usersReadUserById>>,
          TError,
          Awaited<ReturnType<typeof usersReadUserById>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useUsersReadUserById<TData = Awaited<ReturnType<typeof usersReadUserById>>, TError = ErrorType<HTTPValidationError>>(
 userId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof usersReadUserById>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof usersReadUserById>>,
          TError,
          Awaited<ReturnType<typeof usersReadUserById>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useUsersReadUserById<TData = Awaited<ReturnType<typeof usersReadUserById>>, TError = ErrorType<HTTPValidationError>>(
 userId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof usersReadUserById>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Read User By Id
 */

export function useUsersReadUserById<TData = Awaited<ReturnType<typeof usersReadUserById>>, TError = ErrorType<HTTPValidationError>>(
 userId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof usersReadUserById>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getUsersReadUserByIdQueryOptions(userId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * Update a user.
 * @summary Update User
 */
export const usersUpdateUser = (
    userId: string,
    userUpdate: UserUpdate,
 signal?: AbortSignal
) => {
      
      
      return customInstance<UserPublic>(
      {url: `/api/v1/users/${userId}`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: userUpdate, signal
    },
      );
    }
  


export const getUsersUpdateUserMutationOptions = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof usersUpdateUser>>, TError,{userId: string;data: UserUpdate}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof usersUpdateUser>>, TError,{userId: string;data: UserUpdate}, TContext> => {

const mutationKey = ['usersUpdateUser'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof usersUpdateUser>>, {userId: string;data: UserUpdate}> = (props) => {
          const {userId,data} = props ?? {};

          return  usersUpdateUser(userId,data,)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type UsersUpdateUserMutationResult = NonNullable<Awaited<ReturnType<typeof usersUpdateUser>>>
    export type UsersUpdateUserMutationBody = UserUpdate
    export type UsersUpdateUserMutationError = ErrorType<HTTPValidationError>

    /**
 * @summary Update User
 */
export const useUsersUpdateUser = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof usersUpdateUser>>, TError,{userId: string;data: UserUpdate}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof usersUpdateUser>>,
        TError,
        {userId: string;data: UserUpdate},
        TContext
      > => {
      return useMutation(getUsersUpdateUserMutationOptions(options), queryClient);
    }
    /**
 * Delete a user.
 * @summary Delete User
 */
export const usersDeleteUser = (
    userId: string,
 signal?: AbortSignal
) => {
      
      
      return customInstance<Message>(
      {url: `/api/v1/users/${userId}`, method: 'DELETE', signal
    },
      );
    }
  


export const getUsersDeleteUserMutationOptions = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof usersDeleteUser>>, TError,{userId: string}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof usersDeleteUser>>, TError,{userId: string}, TContext> => {

const mutationKey = ['usersDeleteUser'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof usersDeleteUser>>, {userId: string}> = (props) => {
          const {userId} = props ?? {};

          return  usersDeleteUser(userId,)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type UsersDeleteUserMutationResult = NonNullable<Awaited<ReturnType<typeof usersDeleteUser>>>
    
    export type UsersDeleteUserMutationError = ErrorType<HTTPValidationError>

    /**
 * @summary Delete User
 */
export const useUsersDeleteUser = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof usersDeleteUser>>, TError,{userId: string}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof usersDeleteUser>>,
        TError,
        {userId: string},
        TContext
      > => {
      return useMutation(getUsersDeleteUserMutationOptions(options), queryClient);
    }
    /**
 * Create new user without the need to be logged in.
 * @summary Register User
 */
export const usersRegisterUser = (
    userRegister: UserRegister,
 signal?: AbortSignal
) => {
      
      
      return customInstance<Message>(
      {url: `/api/v1/users/signup`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: userRegister, signal
    },
      );
    }
  


export const getUsersRegisterUserMutationOptions = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof usersRegisterUser>>, TError,{data: UserRegister}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof usersRegisterUser>>, TError,{data: UserRegister}, TContext> => {

const mutationKey = ['usersRegisterUser'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof usersRegisterUser>>, {data: UserRegister}> = (props) => {
          const {data} = props ?? {};

          return  usersRegisterUser(data,)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type UsersRegisterUserMutationResult = NonNullable<Awaited<ReturnType<typeof usersRegisterUser>>>
    export type UsersRegisterUserMutationBody = UserRegister
    export type UsersRegisterUserMutationError = ErrorType<HTTPValidationError>

    /**
 * @summary Register User
 */
export const useUsersRegisterUser = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof usersRegisterUser>>, TError,{data: UserRegister}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof usersRegisterUser>>,
        TError,
        {data: UserRegister},
        TContext
      > => {
      return useMutation(getUsersRegisterUserMutationOptions(options), queryClient);
    }
    /**
 * verify email and reset password.
 * @summary Verify Email
 */
export const usersVerifyEmail = (
    newAccount: NewAccount,
 signal?: AbortSignal
) => {
      
      
      return customInstance<Message>(
      {url: `/api/v1/users/verify-email/`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: newAccount, signal
    },
      );
    }
  


export const getUsersVerifyEmailMutationOptions = <TError = ErrorType<void | HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof usersVerifyEmail>>, TError,{data: NewAccount}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof usersVerifyEmail>>, TError,{data: NewAccount}, TContext> => {

const mutationKey = ['usersVerifyEmail'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof usersVerifyEmail>>, {data: NewAccount}> = (props) => {
          const {data} = props ?? {};

          return  usersVerifyEmail(data,)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type UsersVerifyEmailMutationResult = NonNullable<Awaited<ReturnType<typeof usersVerifyEmail>>>
    export type UsersVerifyEmailMutationBody = NewAccount
    export type UsersVerifyEmailMutationError = ErrorType<void | HTTPValidationError>

    /**
 * @summary Verify Email
 */
export const useUsersVerifyEmail = <TError = ErrorType<void | HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof usersVerifyEmail>>, TError,{data: NewAccount}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof usersVerifyEmail>>,
        TError,
        {data: NewAccount},
        TContext
      > => {
      return useMutation(getUsersVerifyEmailMutationOptions(options), queryClient);
    }
    