/**
 * Generated by orval v8.0.0-rc.2 🍺
 * Do not edit manually.
 * BarkByte
 * OpenAPI spec version: 0.1.0
 */
import * as zod from "zod";

/**
 * Retrieve users.
 * @summary Read Users
 */
export const usersReadUsersQuerySkipDefault = 0;
export const usersReadUsersQueryLimitDefault = 100;

export const usersReadUsersQueryParams = zod.object({
	skip: zod.number().default(usersReadUsersQuerySkipDefault),
	limit: zod.number().default(usersReadUsersQueryLimitDefault),
});

export const usersReadUsersResponseDataItemEmailMax = 255;

export const usersReadUsersResponseDataItemIsActiveDefault = false;
export const usersReadUsersResponseDataItemIsSuperuserDefault = false;
export const usersReadUsersResponseDataItemFullNameOneMax = 255;

export const usersReadUsersResponse = zod.object({
	data: zod.array(
		zod.object({
			email: zod.email().max(usersReadUsersResponseDataItemEmailMax),
			is_active: zod
				.boolean()
				.default(usersReadUsersResponseDataItemIsActiveDefault),
			is_superuser: zod
				.boolean()
				.default(usersReadUsersResponseDataItemIsSuperuserDefault),
			full_name: zod
				.union([
					zod.string().max(usersReadUsersResponseDataItemFullNameOneMax),
					zod.null(),
				])
				.optional(),
			id: zod.uuid(),
		}),
	),
	count: zod.number(),
});

/**
 * Create new user.
 * @summary Create User
 */
export const usersCreateUserBodyEmailMax = 255;

export const usersCreateUserBodyIsActiveDefault = false;
export const usersCreateUserBodyIsSuperuserDefault = false;
export const usersCreateUserBodyFullNameOneMax = 255;

export const usersCreateUserBodyPasswordMin = 8;
export const usersCreateUserBodyPasswordMax = 64;

export const usersCreateUserBody = zod.object({
	email: zod.email().max(usersCreateUserBodyEmailMax),
	is_active: zod.boolean().default(usersCreateUserBodyIsActiveDefault),
	is_superuser: zod.boolean().default(usersCreateUserBodyIsSuperuserDefault),
	full_name: zod
		.union([zod.string().max(usersCreateUserBodyFullNameOneMax), zod.null()])
		.optional(),
	password: zod
		.string()
		.min(usersCreateUserBodyPasswordMin)
		.max(usersCreateUserBodyPasswordMax),
});

export const usersCreateUserResponseEmailMax = 255;

export const usersCreateUserResponseIsActiveDefault = false;
export const usersCreateUserResponseIsSuperuserDefault = false;
export const usersCreateUserResponseFullNameOneMax = 255;

export const usersCreateUserResponse = zod.object({
	email: zod.email().max(usersCreateUserResponseEmailMax),
	is_active: zod.boolean().default(usersCreateUserResponseIsActiveDefault),
	is_superuser: zod
		.boolean()
		.default(usersCreateUserResponseIsSuperuserDefault),
	full_name: zod
		.union([
			zod.string().max(usersCreateUserResponseFullNameOneMax),
			zod.null(),
		])
		.optional(),
	id: zod.uuid(),
});

/**
 * Get current user.
 * @summary Read User Me
 */
export const usersReadUserMeResponseEmailMax = 255;

export const usersReadUserMeResponseIsActiveDefault = false;
export const usersReadUserMeResponseIsSuperuserDefault = false;
export const usersReadUserMeResponseFullNameOneMax = 255;

export const usersReadUserMeResponse = zod.object({
	email: zod.email().max(usersReadUserMeResponseEmailMax),
	is_active: zod.boolean().default(usersReadUserMeResponseIsActiveDefault),
	is_superuser: zod
		.boolean()
		.default(usersReadUserMeResponseIsSuperuserDefault),
	full_name: zod
		.union([
			zod.string().max(usersReadUserMeResponseFullNameOneMax),
			zod.null(),
		])
		.optional(),
	id: zod.uuid(),
});

/**
 * Delete own user.
 * @summary Delete User Me
 */
export const usersDeleteUserMeResponse = zod.object({
	message: zod.string(),
});

/**
 * Update own user.
 * @summary Update User Me
 */
export const usersUpdateUserMeBodyFullNameOneMax = 255;

export const usersUpdateUserMeBodyEmailOneMax = 255;

export const usersUpdateUserMeBody = zod.object({
	full_name: zod
		.union([zod.string().max(usersUpdateUserMeBodyFullNameOneMax), zod.null()])
		.optional(),
	email: zod
		.union([zod.email().max(usersUpdateUserMeBodyEmailOneMax), zod.null()])
		.optional(),
});

export const usersUpdateUserMeResponseEmailMax = 255;

export const usersUpdateUserMeResponseIsActiveDefault = false;
export const usersUpdateUserMeResponseIsSuperuserDefault = false;
export const usersUpdateUserMeResponseFullNameOneMax = 255;

export const usersUpdateUserMeResponse = zod.object({
	email: zod.email().max(usersUpdateUserMeResponseEmailMax),
	is_active: zod.boolean().default(usersUpdateUserMeResponseIsActiveDefault),
	is_superuser: zod
		.boolean()
		.default(usersUpdateUserMeResponseIsSuperuserDefault),
	full_name: zod
		.union([
			zod.string().max(usersUpdateUserMeResponseFullNameOneMax),
			zod.null(),
		])
		.optional(),
	id: zod.uuid(),
});

/**
 * Update own password.
 * @summary Update Password Me
 */
export const usersUpdatePasswordMeBodyCurrentPasswordMin = 8;
export const usersUpdatePasswordMeBodyCurrentPasswordMax = 64;

export const usersUpdatePasswordMeBodyNewPasswordMin = 8;
export const usersUpdatePasswordMeBodyNewPasswordMax = 64;

export const usersUpdatePasswordMeBody = zod.object({
	current_password: zod
		.string()
		.min(usersUpdatePasswordMeBodyCurrentPasswordMin)
		.max(usersUpdatePasswordMeBodyCurrentPasswordMax),
	new_password: zod
		.string()
		.min(usersUpdatePasswordMeBodyNewPasswordMin)
		.max(usersUpdatePasswordMeBodyNewPasswordMax),
});

export const usersUpdatePasswordMeResponse = zod.object({
	message: zod.string(),
});

/**
 * Create new user without the need to be logged in.
 * @summary Register User
 */
export const usersRegisterUserBodyEmailMax = 255;

export const usersRegisterUserBodyPasswordMin = 8;
export const usersRegisterUserBodyPasswordMax = 64;

export const usersRegisterUserBodyFullNameOneMax = 255;

export const usersRegisterUserBody = zod.object({
	email: zod.email().max(usersRegisterUserBodyEmailMax),
	password: zod
		.string()
		.min(usersRegisterUserBodyPasswordMin)
		.max(usersRegisterUserBodyPasswordMax),
	full_name: zod
		.union([zod.string().max(usersRegisterUserBodyFullNameOneMax), zod.null()])
		.optional(),
});

export const usersRegisterUserResponse = zod.object({
	message: zod.string(),
});

/**
 * verify email and reset password.
 * @summary Verify Email
 */
export const usersVerifyEmailBody = zod.object({
	token: zod.string(),
});

export const usersVerifyEmailResponse = zod.object({
	message: zod.string(),
});

/**
 * Get a specific user by id.
 * @summary Read User By Id
 */
export const usersReadUserByIdParams = zod.object({
	user_id: zod.uuid(),
});

export const usersReadUserByIdResponseEmailMax = 255;

export const usersReadUserByIdResponseIsActiveDefault = false;
export const usersReadUserByIdResponseIsSuperuserDefault = false;
export const usersReadUserByIdResponseFullNameOneMax = 255;

export const usersReadUserByIdResponse = zod.object({
	email: zod.email().max(usersReadUserByIdResponseEmailMax),
	is_active: zod.boolean().default(usersReadUserByIdResponseIsActiveDefault),
	is_superuser: zod
		.boolean()
		.default(usersReadUserByIdResponseIsSuperuserDefault),
	full_name: zod
		.union([
			zod.string().max(usersReadUserByIdResponseFullNameOneMax),
			zod.null(),
		])
		.optional(),
	id: zod.uuid(),
});

/**
 * Update a user.
 * @summary Update User
 */
export const usersUpdateUserParams = zod.object({
	user_id: zod.uuid(),
});

export const usersUpdateUserBodyEmailOneMax = 255;

export const usersUpdateUserBodyIsActiveDefault = false;
export const usersUpdateUserBodyIsSuperuserDefault = false;
export const usersUpdateUserBodyFullNameOneMax = 255;

export const usersUpdateUserBodyPasswordOneMin = 8;
export const usersUpdateUserBodyPasswordOneMax = 64;

export const usersUpdateUserBody = zod.object({
	email: zod
		.union([zod.email().max(usersUpdateUserBodyEmailOneMax), zod.null()])
		.optional(),
	is_active: zod.boolean().default(usersUpdateUserBodyIsActiveDefault),
	is_superuser: zod.boolean().default(usersUpdateUserBodyIsSuperuserDefault),
	full_name: zod
		.union([zod.string().max(usersUpdateUserBodyFullNameOneMax), zod.null()])
		.optional(),
	password: zod
		.union([
			zod
				.string()
				.min(usersUpdateUserBodyPasswordOneMin)
				.max(usersUpdateUserBodyPasswordOneMax),
			zod.null(),
		])
		.optional(),
});

export const usersUpdateUserResponseEmailMax = 255;

export const usersUpdateUserResponseIsActiveDefault = false;
export const usersUpdateUserResponseIsSuperuserDefault = false;
export const usersUpdateUserResponseFullNameOneMax = 255;

export const usersUpdateUserResponse = zod.object({
	email: zod.email().max(usersUpdateUserResponseEmailMax),
	is_active: zod.boolean().default(usersUpdateUserResponseIsActiveDefault),
	is_superuser: zod
		.boolean()
		.default(usersUpdateUserResponseIsSuperuserDefault),
	full_name: zod
		.union([
			zod.string().max(usersUpdateUserResponseFullNameOneMax),
			zod.null(),
		])
		.optional(),
	id: zod.uuid(),
});

/**
 * Delete a user.
 * @summary Delete User
 */
export const usersDeleteUserParams = zod.object({
	user_id: zod.uuid(),
});

export const usersDeleteUserResponse = zod.object({
	message: zod.string(),
});
