/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Timverse
 * OpenAPI spec version: 1.0.0
 */
import * as zod from "zod";

/**
 * Retrieve sub joinery types.
 * @summary Get Sjtypes
 */
export const subjoinerytypeGetSjtypesQuerySkipDefault = 0;
export const subjoinerytypeGetSjtypesQueryLimitDefault = 100;

export const SubjoinerytypeGetSjtypesQueryParams = zod.object({
	skip: zod.number().default(subjoinerytypeGetSjtypesQuerySkipDefault),
	limit: zod.number().default(subjoinerytypeGetSjtypesQueryLimitDefault),
});

export const subjoinerytypeGetSjtypesResponseDataItemLabelMax = 255;

export const SubjoinerytypeGetSjtypesResponse = zod.object({
	data: zod.array(
		zod.object({
			id: zod.uuid().optional(),
			joinery_type_id: zod.uuid(),
			label: zod
				.string()
				.min(1)
				.max(subjoinerytypeGetSjtypesResponseDataItemLabelMax),
		}),
	),
	count: zod.number(),
});

/**
 * Create sub joinery type.
 * @summary Create Sjtype
 */
export const subjoinerytypeCreateSjtypeBodyLabelMax = 255;

export const SubjoinerytypeCreateSjtypeBody = zod.object({
	joinery_type_id: zod.uuid(),
	label: zod.string().min(1).max(subjoinerytypeCreateSjtypeBodyLabelMax),
});

export const subjoinerytypeCreateSjtypeResponseLabelMax = 255;

export const SubjoinerytypeCreateSjtypeResponse = zod.object({
	id: zod.uuid().optional(),
	joinery_type_id: zod.uuid(),
	label: zod.string().min(1).max(subjoinerytypeCreateSjtypeResponseLabelMax),
});

/**
 * Update sub joinery type.
 * @summary Update Sjtype
 */
export const SubjoinerytypeUpdateSjtypeParams = zod.object({
	id: zod.uuid(),
});

export const subjoinerytypeUpdateSjtypeBodyLabelMax = 255;

export const SubjoinerytypeUpdateSjtypeBody = zod.object({
	joinery_type_id: zod.uuid(),
	label: zod.string().min(1).max(subjoinerytypeUpdateSjtypeBodyLabelMax),
});

export const subjoinerytypeUpdateSjtypeResponseLabelMax = 255;

export const SubjoinerytypeUpdateSjtypeResponse = zod.object({
	id: zod.uuid().optional(),
	joinery_type_id: zod.uuid(),
	label: zod.string().min(1).max(subjoinerytypeUpdateSjtypeResponseLabelMax),
});

/**
 * Delete sub joinery type ONLY if not in use.
 * @summary Delete Sjtype
 */
export const SubjoinerytypeDeleteSjtypeParams = zod.object({
	id: zod.uuid(),
});

export const SubjoinerytypeDeleteSjtypeResponse = zod.unknown();

/**
 * Retrieve sub joinery types for a specific joinery type.
 * @summary Get Sjtypes For Jtype
 */
export const SubjoinerytypeGetSjtypesForJtypeParams = zod.object({
	joinery_type_id: zod.uuid(),
});

export const subjoinerytypeGetSjtypesForJtypeQuerySkipDefault = 0;
export const subjoinerytypeGetSjtypesForJtypeQueryLimitDefault = 100;

export const SubjoinerytypeGetSjtypesForJtypeQueryParams = zod.object({
	skip: zod.number().default(subjoinerytypeGetSjtypesForJtypeQuerySkipDefault),
	limit: zod
		.number()
		.default(subjoinerytypeGetSjtypesForJtypeQueryLimitDefault),
});

export const subjoinerytypeGetSjtypesForJtypeResponseDataItemLabelMax = 255;

export const SubjoinerytypeGetSjtypesForJtypeResponse = zod.object({
	data: zod.array(
		zod.object({
			id: zod.uuid().optional(),
			joinery_type_id: zod.uuid(),
			label: zod
				.string()
				.min(1)
				.max(subjoinerytypeGetSjtypesForJtypeResponseDataItemLabelMax),
		}),
	),
	count: zod.number(),
});
