/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * BarkByte
 * OpenAPI spec version: 0.1.0
 */

import type {
	DataTag,
	DefinedInitialDataOptions,
	DefinedUseQueryResult,
	MutationFunction,
	QueryClient,
	QueryFunction,
	QueryKey,
	UndefinedInitialDataOptions,
	UseMutationOptions,
	UseMutationResult,
	UseQueryOptions,
	UseQueryResult,
} from "@tanstack/react-query";
import { useMutation, useQuery } from "@tanstack/react-query";

import type {
	HTTPValidationError,
	SubJoineryType,
	SubJoineryTypeCreate,
	SubJoineryTypes,
	SubjoinerytypeGetSjtypesForJtypeParams,
	SubjoinerytypeGetSjtypesParams,
} from "../../model";
import type { ErrorType } from "../../mutator/custom-instance";
import { customInstance } from "../../mutator/custom-instance";

/**
 * Retrieve sub joinery types.
 * @summary Get Sjtypes
 */
export const subjoinerytypeGetSjtypes = (
	params?: SubjoinerytypeGetSjtypesParams,
	signal?: AbortSignal,
) => {
	return customInstance<SubJoineryTypes>({
		url: `/api/v1/subjoinerytype/`,
		method: "GET",
		params,
		signal,
	});
};

export const getSubjoinerytypeGetSjtypesQueryKey = (
	params?: SubjoinerytypeGetSjtypesParams,
) => {
	return [`/api/v1/subjoinerytype/`, ...(params ? [params] : [])] as const;
};

export const getSubjoinerytypeGetSjtypesQueryOptions = <
	TData = Awaited<ReturnType<typeof subjoinerytypeGetSjtypes>>,
	TError = ErrorType<HTTPValidationError>,
>(
	params?: SubjoinerytypeGetSjtypesParams,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof subjoinerytypeGetSjtypes>>,
				TError,
				TData
			>
		>;
	},
) => {
	const { query: queryOptions } = options ?? {};

	const queryKey =
		queryOptions?.queryKey ?? getSubjoinerytypeGetSjtypesQueryKey(params);

	const queryFn: QueryFunction<
		Awaited<ReturnType<typeof subjoinerytypeGetSjtypes>>
	> = ({ signal }) => subjoinerytypeGetSjtypes(params, signal);

	return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
		Awaited<ReturnType<typeof subjoinerytypeGetSjtypes>>,
		TError,
		TData
	> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type SubjoinerytypeGetSjtypesQueryResult = NonNullable<
	Awaited<ReturnType<typeof subjoinerytypeGetSjtypes>>
>;
export type SubjoinerytypeGetSjtypesQueryError = ErrorType<HTTPValidationError>;

export function useSubjoinerytypeGetSjtypes<
	TData = Awaited<ReturnType<typeof subjoinerytypeGetSjtypes>>,
	TError = ErrorType<HTTPValidationError>,
>(
	params: undefined | SubjoinerytypeGetSjtypesParams,
	options: {
		query: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof subjoinerytypeGetSjtypes>>,
				TError,
				TData
			>
		> &
			Pick<
				DefinedInitialDataOptions<
					Awaited<ReturnType<typeof subjoinerytypeGetSjtypes>>,
					TError,
					Awaited<ReturnType<typeof subjoinerytypeGetSjtypes>>
				>,
				"initialData"
			>;
	},
	queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useSubjoinerytypeGetSjtypes<
	TData = Awaited<ReturnType<typeof subjoinerytypeGetSjtypes>>,
	TError = ErrorType<HTTPValidationError>,
>(
	params?: SubjoinerytypeGetSjtypesParams,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof subjoinerytypeGetSjtypes>>,
				TError,
				TData
			>
		> &
			Pick<
				UndefinedInitialDataOptions<
					Awaited<ReturnType<typeof subjoinerytypeGetSjtypes>>,
					TError,
					Awaited<ReturnType<typeof subjoinerytypeGetSjtypes>>
				>,
				"initialData"
			>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useSubjoinerytypeGetSjtypes<
	TData = Awaited<ReturnType<typeof subjoinerytypeGetSjtypes>>,
	TError = ErrorType<HTTPValidationError>,
>(
	params?: SubjoinerytypeGetSjtypesParams,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof subjoinerytypeGetSjtypes>>,
				TError,
				TData
			>
		>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get Sjtypes
 */

export function useSubjoinerytypeGetSjtypes<
	TData = Awaited<ReturnType<typeof subjoinerytypeGetSjtypes>>,
	TError = ErrorType<HTTPValidationError>,
>(
	params?: SubjoinerytypeGetSjtypesParams,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof subjoinerytypeGetSjtypes>>,
				TError,
				TData
			>
		>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
} {
	const queryOptions = getSubjoinerytypeGetSjtypesQueryOptions(params, options);

	const query = useQuery(queryOptions, queryClient) as UseQueryResult<
		TData,
		TError
	> & { queryKey: DataTag<QueryKey, TData, TError> };

	return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * Create sub joinery type.
 * @summary Create Sjtype
 */
export const subjoinerytypeCreateSjtype = (
	subJoineryTypeCreate: SubJoineryTypeCreate,
	signal?: AbortSignal,
) => {
	return customInstance<SubJoineryType>({
		url: `/api/v1/subjoinerytype/`,
		method: "POST",
		headers: { "Content-Type": "application/json" },
		data: subJoineryTypeCreate,
		signal,
	});
};

export const getSubjoinerytypeCreateSjtypeMutationOptions = <
	TError = ErrorType<HTTPValidationError>,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof subjoinerytypeCreateSjtype>>,
		TError,
		{ data: SubJoineryTypeCreate },
		TContext
	>;
}): UseMutationOptions<
	Awaited<ReturnType<typeof subjoinerytypeCreateSjtype>>,
	TError,
	{ data: SubJoineryTypeCreate },
	TContext
> => {
	const mutationKey = ["subjoinerytypeCreateSjtype"];
	const { mutation: mutationOptions } = options
		? options.mutation &&
			"mutationKey" in options.mutation &&
			options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey } };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof subjoinerytypeCreateSjtype>>,
		{ data: SubJoineryTypeCreate }
	> = (props) => {
		const { data } = props ?? {};

		return subjoinerytypeCreateSjtype(data);
	};

	return { mutationFn, ...mutationOptions };
};

export type SubjoinerytypeCreateSjtypeMutationResult = NonNullable<
	Awaited<ReturnType<typeof subjoinerytypeCreateSjtype>>
>;
export type SubjoinerytypeCreateSjtypeMutationBody = SubJoineryTypeCreate;
export type SubjoinerytypeCreateSjtypeMutationError =
	ErrorType<HTTPValidationError>;

/**
 * @summary Create Sjtype
 */
export const useSubjoinerytypeCreateSjtype = <
	TError = ErrorType<HTTPValidationError>,
	TContext = unknown,
>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof subjoinerytypeCreateSjtype>>,
			TError,
			{ data: SubJoineryTypeCreate },
			TContext
		>;
	},
	queryClient?: QueryClient,
): UseMutationResult<
	Awaited<ReturnType<typeof subjoinerytypeCreateSjtype>>,
	TError,
	{ data: SubJoineryTypeCreate },
	TContext
> => {
	return useMutation(
		getSubjoinerytypeCreateSjtypeMutationOptions(options),
		queryClient,
	);
};
/**
 * Update sub joinery type.
 * @summary Update Sjtype
 */
export const subjoinerytypeUpdateSjtype = (
	id: string,
	subJoineryTypeCreate: SubJoineryTypeCreate,
	signal?: AbortSignal,
) => {
	return customInstance<SubJoineryType>({
		url: `/api/v1/subjoinerytype/${id}`,
		method: "PUT",
		headers: { "Content-Type": "application/json" },
		data: subJoineryTypeCreate,
		signal,
	});
};

export const getSubjoinerytypeUpdateSjtypeMutationOptions = <
	TError = ErrorType<HTTPValidationError>,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof subjoinerytypeUpdateSjtype>>,
		TError,
		{ id: string; data: SubJoineryTypeCreate },
		TContext
	>;
}): UseMutationOptions<
	Awaited<ReturnType<typeof subjoinerytypeUpdateSjtype>>,
	TError,
	{ id: string; data: SubJoineryTypeCreate },
	TContext
> => {
	const mutationKey = ["subjoinerytypeUpdateSjtype"];
	const { mutation: mutationOptions } = options
		? options.mutation &&
			"mutationKey" in options.mutation &&
			options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey } };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof subjoinerytypeUpdateSjtype>>,
		{ id: string; data: SubJoineryTypeCreate }
	> = (props) => {
		const { id, data } = props ?? {};

		return subjoinerytypeUpdateSjtype(id, data);
	};

	return { mutationFn, ...mutationOptions };
};

export type SubjoinerytypeUpdateSjtypeMutationResult = NonNullable<
	Awaited<ReturnType<typeof subjoinerytypeUpdateSjtype>>
>;
export type SubjoinerytypeUpdateSjtypeMutationBody = SubJoineryTypeCreate;
export type SubjoinerytypeUpdateSjtypeMutationError =
	ErrorType<HTTPValidationError>;

/**
 * @summary Update Sjtype
 */
export const useSubjoinerytypeUpdateSjtype = <
	TError = ErrorType<HTTPValidationError>,
	TContext = unknown,
>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof subjoinerytypeUpdateSjtype>>,
			TError,
			{ id: string; data: SubJoineryTypeCreate },
			TContext
		>;
	},
	queryClient?: QueryClient,
): UseMutationResult<
	Awaited<ReturnType<typeof subjoinerytypeUpdateSjtype>>,
	TError,
	{ id: string; data: SubJoineryTypeCreate },
	TContext
> => {
	return useMutation(
		getSubjoinerytypeUpdateSjtypeMutationOptions(options),
		queryClient,
	);
};
/**
 * Delete sub joinery type ONLY if not in use.
 * @summary Delete Sjtype
 */
export const subjoinerytypeDeleteSjtype = (
	id: string,
	signal?: AbortSignal,
) => {
	return customInstance<unknown>({
		url: `/api/v1/subjoinerytype/${id}`,
		method: "DELETE",
		signal,
	});
};

export const getSubjoinerytypeDeleteSjtypeMutationOptions = <
	TError = ErrorType<HTTPValidationError>,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof subjoinerytypeDeleteSjtype>>,
		TError,
		{ id: string },
		TContext
	>;
}): UseMutationOptions<
	Awaited<ReturnType<typeof subjoinerytypeDeleteSjtype>>,
	TError,
	{ id: string },
	TContext
> => {
	const mutationKey = ["subjoinerytypeDeleteSjtype"];
	const { mutation: mutationOptions } = options
		? options.mutation &&
			"mutationKey" in options.mutation &&
			options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey } };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof subjoinerytypeDeleteSjtype>>,
		{ id: string }
	> = (props) => {
		const { id } = props ?? {};

		return subjoinerytypeDeleteSjtype(id);
	};

	return { mutationFn, ...mutationOptions };
};

export type SubjoinerytypeDeleteSjtypeMutationResult = NonNullable<
	Awaited<ReturnType<typeof subjoinerytypeDeleteSjtype>>
>;

export type SubjoinerytypeDeleteSjtypeMutationError =
	ErrorType<HTTPValidationError>;

/**
 * @summary Delete Sjtype
 */
export const useSubjoinerytypeDeleteSjtype = <
	TError = ErrorType<HTTPValidationError>,
	TContext = unknown,
>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof subjoinerytypeDeleteSjtype>>,
			TError,
			{ id: string },
			TContext
		>;
	},
	queryClient?: QueryClient,
): UseMutationResult<
	Awaited<ReturnType<typeof subjoinerytypeDeleteSjtype>>,
	TError,
	{ id: string },
	TContext
> => {
	return useMutation(
		getSubjoinerytypeDeleteSjtypeMutationOptions(options),
		queryClient,
	);
};
/**
 * Retrieve sub joinery types for a specific joinery type.
 * @summary Get Sjtypes For Jtype
 */
export const subjoinerytypeGetSjtypesForJtype = (
	joineryTypeId: string,
	params?: SubjoinerytypeGetSjtypesForJtypeParams,
	signal?: AbortSignal,
) => {
	return customInstance<SubJoineryTypes>({
		url: `/api/v1/subjoinerytype/${joineryTypeId}/`,
		method: "GET",
		params,
		signal,
	});
};

export const getSubjoinerytypeGetSjtypesForJtypeQueryKey = (
	joineryTypeId: string,
	params?: SubjoinerytypeGetSjtypesForJtypeParams,
) => {
	return [
		`/api/v1/subjoinerytype/${joineryTypeId}/`,
		...(params ? [params] : []),
	] as const;
};

export const getSubjoinerytypeGetSjtypesForJtypeQueryOptions = <
	TData = Awaited<ReturnType<typeof subjoinerytypeGetSjtypesForJtype>>,
	TError = ErrorType<HTTPValidationError>,
>(
	joineryTypeId: string,
	params?: SubjoinerytypeGetSjtypesForJtypeParams,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof subjoinerytypeGetSjtypesForJtype>>,
				TError,
				TData
			>
		>;
	},
) => {
	const { query: queryOptions } = options ?? {};

	const queryKey =
		queryOptions?.queryKey ??
		getSubjoinerytypeGetSjtypesForJtypeQueryKey(joineryTypeId, params);

	const queryFn: QueryFunction<
		Awaited<ReturnType<typeof subjoinerytypeGetSjtypesForJtype>>
	> = ({ signal }) =>
		subjoinerytypeGetSjtypesForJtype(joineryTypeId, params, signal);

	return {
		queryKey,
		queryFn,
		enabled: !!joineryTypeId,
		...queryOptions,
	} as UseQueryOptions<
		Awaited<ReturnType<typeof subjoinerytypeGetSjtypesForJtype>>,
		TError,
		TData
	> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type SubjoinerytypeGetSjtypesForJtypeQueryResult = NonNullable<
	Awaited<ReturnType<typeof subjoinerytypeGetSjtypesForJtype>>
>;
export type SubjoinerytypeGetSjtypesForJtypeQueryError =
	ErrorType<HTTPValidationError>;

export function useSubjoinerytypeGetSjtypesForJtype<
	TData = Awaited<ReturnType<typeof subjoinerytypeGetSjtypesForJtype>>,
	TError = ErrorType<HTTPValidationError>,
>(
	joineryTypeId: string,
	params: undefined | SubjoinerytypeGetSjtypesForJtypeParams,
	options: {
		query: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof subjoinerytypeGetSjtypesForJtype>>,
				TError,
				TData
			>
		> &
			Pick<
				DefinedInitialDataOptions<
					Awaited<ReturnType<typeof subjoinerytypeGetSjtypesForJtype>>,
					TError,
					Awaited<ReturnType<typeof subjoinerytypeGetSjtypesForJtype>>
				>,
				"initialData"
			>;
	},
	queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useSubjoinerytypeGetSjtypesForJtype<
	TData = Awaited<ReturnType<typeof subjoinerytypeGetSjtypesForJtype>>,
	TError = ErrorType<HTTPValidationError>,
>(
	joineryTypeId: string,
	params?: SubjoinerytypeGetSjtypesForJtypeParams,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof subjoinerytypeGetSjtypesForJtype>>,
				TError,
				TData
			>
		> &
			Pick<
				UndefinedInitialDataOptions<
					Awaited<ReturnType<typeof subjoinerytypeGetSjtypesForJtype>>,
					TError,
					Awaited<ReturnType<typeof subjoinerytypeGetSjtypesForJtype>>
				>,
				"initialData"
			>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useSubjoinerytypeGetSjtypesForJtype<
	TData = Awaited<ReturnType<typeof subjoinerytypeGetSjtypesForJtype>>,
	TError = ErrorType<HTTPValidationError>,
>(
	joineryTypeId: string,
	params?: SubjoinerytypeGetSjtypesForJtypeParams,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof subjoinerytypeGetSjtypesForJtype>>,
				TError,
				TData
			>
		>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get Sjtypes For Jtype
 */

export function useSubjoinerytypeGetSjtypesForJtype<
	TData = Awaited<ReturnType<typeof subjoinerytypeGetSjtypesForJtype>>,
	TError = ErrorType<HTTPValidationError>,
>(
	joineryTypeId: string,
	params?: SubjoinerytypeGetSjtypesForJtypeParams,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof subjoinerytypeGetSjtypesForJtype>>,
				TError,
				TData
			>
		>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
} {
	const queryOptions = getSubjoinerytypeGetSjtypesForJtypeQueryOptions(
		joineryTypeId,
		params,
		options,
	);

	const query = useQuery(queryOptions, queryClient) as UseQueryResult<
		TData,
		TError
	> & { queryKey: DataTag<QueryKey, TData, TError> };

	return { ...query, queryKey: queryOptions.queryKey };
}
