/**
 * Generated by orval v8.0.0-rc.2 🍺
 * Do not edit manually.
 * BarkByte
 * OpenAPI spec version: 0.1.0
 */
import * as zod from "zod";

/**
 * Retrieve all fastener types.
 * @summary Get Fastener Types
 */
export const fastenertypeGetFastenerTypesQuerySkipDefault = 0;
export const fastenertypeGetFastenerTypesQueryLimitDefault = 100;

export const fastenertypeGetFastenerTypesQueryParams = zod.object({
	skip: zod.number().default(fastenertypeGetFastenerTypesQuerySkipDefault),
	limit: zod.number().default(fastenertypeGetFastenerTypesQueryLimitDefault),
});

export const fastenertypeGetFastenerTypesResponseDataItemLabelMax = 255;

export const fastenertypeGetFastenerTypesResponse = zod.object({
	count: zod.number(),
	data: zod.array(
		zod.object({
			id: zod.uuid().optional(),
			label: zod
				.string()
				.min(1)
				.max(fastenertypeGetFastenerTypesResponseDataItemLabelMax),
		}),
	),
});

/**
 * Create fastener type.
 * @summary Create Fastener Type
 */
export const fastenertypeCreateFastenerTypeBodyLabelMax = 255;

export const fastenertypeCreateFastenerTypeBody = zod.object({
	label: zod.string().min(1).max(fastenertypeCreateFastenerTypeBodyLabelMax),
});

export const fastenertypeCreateFastenerTypeResponseLabelMax = 255;

export const fastenertypeCreateFastenerTypeResponse = zod.object({
	id: zod.uuid().optional(),
	label: zod
		.string()
		.min(1)
		.max(fastenertypeCreateFastenerTypeResponseLabelMax),
});

/**
 * Delete fastener type ONLY if not in use.
 * @summary Delete Fastener Type
 */
export const fastenertypeDeleteFastenerTypeParams = zod.object({
	id: zod.uuid(),
});

export const fastenertypeDeleteFastenerTypeResponse = zod.unknown();

/**
 * Update fastener type.
 * @summary Update Fastener Type
 */
export const fastenertypeUpdateFastenerTypeParams = zod.object({
	id: zod.uuid(),
});

export const fastenertypeUpdateFastenerTypeBodyLabelMax = 255;

export const fastenertypeUpdateFastenerTypeBody = zod.object({
	label: zod.string().min(1).max(fastenertypeUpdateFastenerTypeBodyLabelMax),
});

export const fastenertypeUpdateFastenerTypeResponseLabelMax = 255;

export const fastenertypeUpdateFastenerTypeResponse = zod.object({
	id: zod.uuid().optional(),
	label: zod
		.string()
		.min(1)
		.max(fastenertypeUpdateFastenerTypeResponseLabelMax),
});
