/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * BarkByte
 * OpenAPI spec version: 0.1.0
 */

import type {
	DataTag,
	DefinedInitialDataOptions,
	DefinedUseQueryResult,
	MutationFunction,
	QueryClient,
	QueryFunction,
	QueryKey,
	UndefinedInitialDataOptions,
	UseMutationOptions,
	UseMutationResult,
	UseQueryOptions,
	UseQueryResult,
} from "@tanstack/react-query";
import { useMutation, useQuery } from "@tanstack/react-query";

import type {
	FastenerType,
	FastenerTypeCreate,
	FastenerTypes,
	FastenertypeGetFastenerTypesParams,
	HTTPValidationError,
} from "../../model";
import type { ErrorType } from "../../mutator/custom-instance";
import { customInstance } from "../../mutator/custom-instance";

/**
 * Retrieve all fastener types.
 * @summary Get Fastener Types
 */
export const fastenertypeGetFastenerTypes = (
	params?: FastenertypeGetFastenerTypesParams,
	signal?: AbortSignal,
) => {
	return customInstance<FastenerTypes>({
		url: `/api/v1/fastenertype/`,
		method: "GET",
		params,
		signal,
	});
};

export const getFastenertypeGetFastenerTypesQueryKey = (
	params?: FastenertypeGetFastenerTypesParams,
) => {
	return [`/api/v1/fastenertype/`, ...(params ? [params] : [])] as const;
};

export const getFastenertypeGetFastenerTypesQueryOptions = <
	TData = Awaited<ReturnType<typeof fastenertypeGetFastenerTypes>>,
	TError = ErrorType<HTTPValidationError>,
>(
	params?: FastenertypeGetFastenerTypesParams,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof fastenertypeGetFastenerTypes>>,
				TError,
				TData
			>
		>;
	},
) => {
	const { query: queryOptions } = options ?? {};

	const queryKey =
		queryOptions?.queryKey ?? getFastenertypeGetFastenerTypesQueryKey(params);

	const queryFn: QueryFunction<
		Awaited<ReturnType<typeof fastenertypeGetFastenerTypes>>
	> = ({ signal }) => fastenertypeGetFastenerTypes(params, signal);

	return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
		Awaited<ReturnType<typeof fastenertypeGetFastenerTypes>>,
		TError,
		TData
	> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type FastenertypeGetFastenerTypesQueryResult = NonNullable<
	Awaited<ReturnType<typeof fastenertypeGetFastenerTypes>>
>;
export type FastenertypeGetFastenerTypesQueryError =
	ErrorType<HTTPValidationError>;

export function useFastenertypeGetFastenerTypes<
	TData = Awaited<ReturnType<typeof fastenertypeGetFastenerTypes>>,
	TError = ErrorType<HTTPValidationError>,
>(
	params: undefined | FastenertypeGetFastenerTypesParams,
	options: {
		query: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof fastenertypeGetFastenerTypes>>,
				TError,
				TData
			>
		> &
			Pick<
				DefinedInitialDataOptions<
					Awaited<ReturnType<typeof fastenertypeGetFastenerTypes>>,
					TError,
					Awaited<ReturnType<typeof fastenertypeGetFastenerTypes>>
				>,
				"initialData"
			>;
	},
	queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useFastenertypeGetFastenerTypes<
	TData = Awaited<ReturnType<typeof fastenertypeGetFastenerTypes>>,
	TError = ErrorType<HTTPValidationError>,
>(
	params?: FastenertypeGetFastenerTypesParams,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof fastenertypeGetFastenerTypes>>,
				TError,
				TData
			>
		> &
			Pick<
				UndefinedInitialDataOptions<
					Awaited<ReturnType<typeof fastenertypeGetFastenerTypes>>,
					TError,
					Awaited<ReturnType<typeof fastenertypeGetFastenerTypes>>
				>,
				"initialData"
			>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useFastenertypeGetFastenerTypes<
	TData = Awaited<ReturnType<typeof fastenertypeGetFastenerTypes>>,
	TError = ErrorType<HTTPValidationError>,
>(
	params?: FastenertypeGetFastenerTypesParams,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof fastenertypeGetFastenerTypes>>,
				TError,
				TData
			>
		>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get Fastener Types
 */

export function useFastenertypeGetFastenerTypes<
	TData = Awaited<ReturnType<typeof fastenertypeGetFastenerTypes>>,
	TError = ErrorType<HTTPValidationError>,
>(
	params?: FastenertypeGetFastenerTypesParams,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof fastenertypeGetFastenerTypes>>,
				TError,
				TData
			>
		>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
} {
	const queryOptions = getFastenertypeGetFastenerTypesQueryOptions(
		params,
		options,
	);

	const query = useQuery(queryOptions, queryClient) as UseQueryResult<
		TData,
		TError
	> & { queryKey: DataTag<QueryKey, TData, TError> };

	return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * Create fastener type.
 * @summary Create Fastener Type
 */
export const fastenertypeCreateFastenerType = (
	fastenerTypeCreate: FastenerTypeCreate,
	signal?: AbortSignal,
) => {
	return customInstance<FastenerType>({
		url: `/api/v1/fastenertype/`,
		method: "POST",
		headers: { "Content-Type": "application/json" },
		data: fastenerTypeCreate,
		signal,
	});
};

export const getFastenertypeCreateFastenerTypeMutationOptions = <
	TError = ErrorType<HTTPValidationError>,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof fastenertypeCreateFastenerType>>,
		TError,
		{ data: FastenerTypeCreate },
		TContext
	>;
}): UseMutationOptions<
	Awaited<ReturnType<typeof fastenertypeCreateFastenerType>>,
	TError,
	{ data: FastenerTypeCreate },
	TContext
> => {
	const mutationKey = ["fastenertypeCreateFastenerType"];
	const { mutation: mutationOptions } = options
		? options.mutation &&
			"mutationKey" in options.mutation &&
			options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey } };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof fastenertypeCreateFastenerType>>,
		{ data: FastenerTypeCreate }
	> = (props) => {
		const { data } = props ?? {};

		return fastenertypeCreateFastenerType(data);
	};

	return { mutationFn, ...mutationOptions };
};

export type FastenertypeCreateFastenerTypeMutationResult = NonNullable<
	Awaited<ReturnType<typeof fastenertypeCreateFastenerType>>
>;
export type FastenertypeCreateFastenerTypeMutationBody = FastenerTypeCreate;
export type FastenertypeCreateFastenerTypeMutationError =
	ErrorType<HTTPValidationError>;

/**
 * @summary Create Fastener Type
 */
export const useFastenertypeCreateFastenerType = <
	TError = ErrorType<HTTPValidationError>,
	TContext = unknown,
>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof fastenertypeCreateFastenerType>>,
			TError,
			{ data: FastenerTypeCreate },
			TContext
		>;
	},
	queryClient?: QueryClient,
): UseMutationResult<
	Awaited<ReturnType<typeof fastenertypeCreateFastenerType>>,
	TError,
	{ data: FastenerTypeCreate },
	TContext
> => {
	return useMutation(
		getFastenertypeCreateFastenerTypeMutationOptions(options),
		queryClient,
	);
};
/**
 * Update fastener type.
 * @summary Update Fastener Type
 */
export const fastenertypeUpdateFastenerType = (
	id: string,
	fastenerTypeCreate: FastenerTypeCreate,
	signal?: AbortSignal,
) => {
	return customInstance<FastenerType>({
		url: `/api/v1/fastenertype/${id}`,
		method: "PUT",
		headers: { "Content-Type": "application/json" },
		data: fastenerTypeCreate,
		signal,
	});
};

export const getFastenertypeUpdateFastenerTypeMutationOptions = <
	TError = ErrorType<HTTPValidationError>,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof fastenertypeUpdateFastenerType>>,
		TError,
		{ id: string; data: FastenerTypeCreate },
		TContext
	>;
}): UseMutationOptions<
	Awaited<ReturnType<typeof fastenertypeUpdateFastenerType>>,
	TError,
	{ id: string; data: FastenerTypeCreate },
	TContext
> => {
	const mutationKey = ["fastenertypeUpdateFastenerType"];
	const { mutation: mutationOptions } = options
		? options.mutation &&
			"mutationKey" in options.mutation &&
			options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey } };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof fastenertypeUpdateFastenerType>>,
		{ id: string; data: FastenerTypeCreate }
	> = (props) => {
		const { id, data } = props ?? {};

		return fastenertypeUpdateFastenerType(id, data);
	};

	return { mutationFn, ...mutationOptions };
};

export type FastenertypeUpdateFastenerTypeMutationResult = NonNullable<
	Awaited<ReturnType<typeof fastenertypeUpdateFastenerType>>
>;
export type FastenertypeUpdateFastenerTypeMutationBody = FastenerTypeCreate;
export type FastenertypeUpdateFastenerTypeMutationError =
	ErrorType<HTTPValidationError>;

/**
 * @summary Update Fastener Type
 */
export const useFastenertypeUpdateFastenerType = <
	TError = ErrorType<HTTPValidationError>,
	TContext = unknown,
>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof fastenertypeUpdateFastenerType>>,
			TError,
			{ id: string; data: FastenerTypeCreate },
			TContext
		>;
	},
	queryClient?: QueryClient,
): UseMutationResult<
	Awaited<ReturnType<typeof fastenertypeUpdateFastenerType>>,
	TError,
	{ id: string; data: FastenerTypeCreate },
	TContext
> => {
	return useMutation(
		getFastenertypeUpdateFastenerTypeMutationOptions(options),
		queryClient,
	);
};
/**
 * Delete fastener type ONLY if not in use.
 * @summary Delete Fastener Type
 */
export const fastenertypeDeleteFastenerType = (
	id: string,
	signal?: AbortSignal,
) => {
	return customInstance<unknown>({
		url: `/api/v1/fastenertype/${id}`,
		method: "DELETE",
		signal,
	});
};

export const getFastenertypeDeleteFastenerTypeMutationOptions = <
	TError = ErrorType<HTTPValidationError>,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof fastenertypeDeleteFastenerType>>,
		TError,
		{ id: string },
		TContext
	>;
}): UseMutationOptions<
	Awaited<ReturnType<typeof fastenertypeDeleteFastenerType>>,
	TError,
	{ id: string },
	TContext
> => {
	const mutationKey = ["fastenertypeDeleteFastenerType"];
	const { mutation: mutationOptions } = options
		? options.mutation &&
			"mutationKey" in options.mutation &&
			options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey } };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof fastenertypeDeleteFastenerType>>,
		{ id: string }
	> = (props) => {
		const { id } = props ?? {};

		return fastenertypeDeleteFastenerType(id);
	};

	return { mutationFn, ...mutationOptions };
};

export type FastenertypeDeleteFastenerTypeMutationResult = NonNullable<
	Awaited<ReturnType<typeof fastenertypeDeleteFastenerType>>
>;

export type FastenertypeDeleteFastenerTypeMutationError =
	ErrorType<HTTPValidationError>;

/**
 * @summary Delete Fastener Type
 */
export const useFastenertypeDeleteFastenerType = <
	TError = ErrorType<HTTPValidationError>,
	TContext = unknown,
>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof fastenertypeDeleteFastenerType>>,
			TError,
			{ id: string },
			TContext
		>;
	},
	queryClient?: QueryClient,
): UseMutationResult<
	Awaited<ReturnType<typeof fastenertypeDeleteFastenerType>>,
	TError,
	{ id: string },
	TContext
> => {
	return useMutation(
		getFastenertypeDeleteFastenerTypeMutationOptions(options),
		queryClient,
	);
};
