/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * BarkByte
 * OpenAPI spec version: 1.1.0
 */

import type {
	MutationFunction,
	QueryClient,
	UseMutationOptions,
	UseMutationResult,
} from "@tanstack/react-query";
import { useMutation } from "@tanstack/react-query";

import type {
	BodyLoginLoginAccessToken,
	HTTPValidationError,
	Message,
	NewPassword,
	Token,
	UserPublic,
} from "../../model";
import type { ErrorType } from "../../mutator/custom-instance";
import { customInstance } from "../../mutator/custom-instance";

/**
 * OAuth2 compatible token login, get an access token for future requests
 * @summary Login Access Token
 */
export const loginLoginAccessToken = (
	bodyLoginLoginAccessToken: BodyLoginLoginAccessToken,
	signal?: AbortSignal,
) => {
	const formUrlEncoded = new URLSearchParams();
	if (
		bodyLoginLoginAccessToken.grant_type !== undefined &&
		bodyLoginLoginAccessToken.grant_type !== null
	) {
		formUrlEncoded.append(`grant_type`, bodyLoginLoginAccessToken.grant_type);
	}
	formUrlEncoded.append(`username`, bodyLoginLoginAccessToken.username);
	formUrlEncoded.append(`password`, bodyLoginLoginAccessToken.password);
	if (bodyLoginLoginAccessToken.scope !== undefined) {
		formUrlEncoded.append(`scope`, bodyLoginLoginAccessToken.scope);
	}
	if (
		bodyLoginLoginAccessToken.client_id !== undefined &&
		bodyLoginLoginAccessToken.client_id !== null
	) {
		formUrlEncoded.append(`client_id`, bodyLoginLoginAccessToken.client_id);
	}
	if (
		bodyLoginLoginAccessToken.client_secret !== undefined &&
		bodyLoginLoginAccessToken.client_secret !== null
	) {
		formUrlEncoded.append(
			`client_secret`,
			bodyLoginLoginAccessToken.client_secret,
		);
	}

	return customInstance<Token>({
		url: `/api/v1/login/access-token`,
		method: "POST",
		headers: { "Content-Type": "application/x-www-form-urlencoded" },
		data: formUrlEncoded,
		signal,
	});
};

export const getLoginLoginAccessTokenMutationOptions = <
	TError = ErrorType<void | HTTPValidationError>,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof loginLoginAccessToken>>,
		TError,
		{ data: BodyLoginLoginAccessToken },
		TContext
	>;
}): UseMutationOptions<
	Awaited<ReturnType<typeof loginLoginAccessToken>>,
	TError,
	{ data: BodyLoginLoginAccessToken },
	TContext
> => {
	const mutationKey = ["loginLoginAccessToken"];
	const { mutation: mutationOptions } = options
		? options.mutation &&
			"mutationKey" in options.mutation &&
			options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey } };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof loginLoginAccessToken>>,
		{ data: BodyLoginLoginAccessToken }
	> = (props) => {
		const { data } = props ?? {};

		return loginLoginAccessToken(data);
	};

	return { mutationFn, ...mutationOptions };
};

export type LoginLoginAccessTokenMutationResult = NonNullable<
	Awaited<ReturnType<typeof loginLoginAccessToken>>
>;
export type LoginLoginAccessTokenMutationBody = BodyLoginLoginAccessToken;
export type LoginLoginAccessTokenMutationError =
	ErrorType<void | HTTPValidationError>;

/**
 * @summary Login Access Token
 */
export const useLoginLoginAccessToken = <
	TError = ErrorType<void | HTTPValidationError>,
	TContext = unknown,
>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof loginLoginAccessToken>>,
			TError,
			{ data: BodyLoginLoginAccessToken },
			TContext
		>;
	},
	queryClient?: QueryClient,
): UseMutationResult<
	Awaited<ReturnType<typeof loginLoginAccessToken>>,
	TError,
	{ data: BodyLoginLoginAccessToken },
	TContext
> => {
	return useMutation(
		getLoginLoginAccessTokenMutationOptions(options),
		queryClient,
	);
};
/**
 * Test access token
 * @summary Test Token
 */
export const loginTestToken = (signal?: AbortSignal) => {
	return customInstance<UserPublic>({
		url: `/api/v1/login/test-token`,
		method: "POST",
		signal,
	});
};

export const getLoginTestTokenMutationOptions = <
	TError = ErrorType<unknown>,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof loginTestToken>>,
		TError,
		void,
		TContext
	>;
}): UseMutationOptions<
	Awaited<ReturnType<typeof loginTestToken>>,
	TError,
	void,
	TContext
> => {
	const mutationKey = ["loginTestToken"];
	const { mutation: mutationOptions } = options
		? options.mutation &&
			"mutationKey" in options.mutation &&
			options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey } };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof loginTestToken>>,
		void
	> = () => {
		return loginTestToken();
	};

	return { mutationFn, ...mutationOptions };
};

export type LoginTestTokenMutationResult = NonNullable<
	Awaited<ReturnType<typeof loginTestToken>>
>;

export type LoginTestTokenMutationError = ErrorType<unknown>;

/**
 * @summary Test Token
 */
export const useLoginTestToken = <
	TError = ErrorType<unknown>,
	TContext = unknown,
>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof loginTestToken>>,
			TError,
			void,
			TContext
		>;
	},
	queryClient?: QueryClient,
): UseMutationResult<
	Awaited<ReturnType<typeof loginTestToken>>,
	TError,
	void,
	TContext
> => {
	return useMutation(getLoginTestTokenMutationOptions(options), queryClient);
};
/**
 * Password Recovery
 * @summary Recover Password
 */
export const loginRecoverPassword = (email: string, signal?: AbortSignal) => {
	return customInstance<Message>({
		url: `/api/v1/password-recovery/${email}`,
		method: "POST",
		signal,
	});
};

export const getLoginRecoverPasswordMutationOptions = <
	TError = ErrorType<HTTPValidationError>,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof loginRecoverPassword>>,
		TError,
		{ email: string },
		TContext
	>;
}): UseMutationOptions<
	Awaited<ReturnType<typeof loginRecoverPassword>>,
	TError,
	{ email: string },
	TContext
> => {
	const mutationKey = ["loginRecoverPassword"];
	const { mutation: mutationOptions } = options
		? options.mutation &&
			"mutationKey" in options.mutation &&
			options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey } };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof loginRecoverPassword>>,
		{ email: string }
	> = (props) => {
		const { email } = props ?? {};

		return loginRecoverPassword(email);
	};

	return { mutationFn, ...mutationOptions };
};

export type LoginRecoverPasswordMutationResult = NonNullable<
	Awaited<ReturnType<typeof loginRecoverPassword>>
>;

export type LoginRecoverPasswordMutationError = ErrorType<HTTPValidationError>;

/**
 * @summary Recover Password
 */
export const useLoginRecoverPassword = <
	TError = ErrorType<HTTPValidationError>,
	TContext = unknown,
>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof loginRecoverPassword>>,
			TError,
			{ email: string },
			TContext
		>;
	},
	queryClient?: QueryClient,
): UseMutationResult<
	Awaited<ReturnType<typeof loginRecoverPassword>>,
	TError,
	{ email: string },
	TContext
> => {
	return useMutation(
		getLoginRecoverPasswordMutationOptions(options),
		queryClient,
	);
};
/**
 * Reset password
 * @summary Reset Password
 */
export const loginResetPassword = (
	newPassword: NewPassword,
	signal?: AbortSignal,
) => {
	return customInstance<Message>({
		url: `/api/v1/reset-password/`,
		method: "POST",
		headers: { "Content-Type": "application/json" },
		data: newPassword,
		signal,
	});
};

export const getLoginResetPasswordMutationOptions = <
	TError = ErrorType<void | HTTPValidationError>,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof loginResetPassword>>,
		TError,
		{ data: NewPassword },
		TContext
	>;
}): UseMutationOptions<
	Awaited<ReturnType<typeof loginResetPassword>>,
	TError,
	{ data: NewPassword },
	TContext
> => {
	const mutationKey = ["loginResetPassword"];
	const { mutation: mutationOptions } = options
		? options.mutation &&
			"mutationKey" in options.mutation &&
			options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey } };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof loginResetPassword>>,
		{ data: NewPassword }
	> = (props) => {
		const { data } = props ?? {};

		return loginResetPassword(data);
	};

	return { mutationFn, ...mutationOptions };
};

export type LoginResetPasswordMutationResult = NonNullable<
	Awaited<ReturnType<typeof loginResetPassword>>
>;
export type LoginResetPasswordMutationBody = NewPassword;
export type LoginResetPasswordMutationError =
	ErrorType<void | HTTPValidationError>;

/**
 * @summary Reset Password
 */
export const useLoginResetPassword = <
	TError = ErrorType<void | HTTPValidationError>,
	TContext = unknown,
>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof loginResetPassword>>,
			TError,
			{ data: NewPassword },
			TContext
		>;
	},
	queryClient?: QueryClient,
): UseMutationResult<
	Awaited<ReturnType<typeof loginResetPassword>>,
	TError,
	{ data: NewPassword },
	TContext
> => {
	return useMutation(
		getLoginResetPasswordMutationOptions(options),
		queryClient,
	);
};
/**
 * @summary Set Password
 */
export const loginSetPassword = (
	newPassword: NewPassword,
	signal?: AbortSignal,
) => {
	return customInstance<Token>({
		url: `/api/v1/set-password`,
		method: "POST",
		headers: { "Content-Type": "application/json" },
		data: newPassword,
		signal,
	});
};

export const getLoginSetPasswordMutationOptions = <
	TError = ErrorType<void | HTTPValidationError>,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof loginSetPassword>>,
		TError,
		{ data: NewPassword },
		TContext
	>;
}): UseMutationOptions<
	Awaited<ReturnType<typeof loginSetPassword>>,
	TError,
	{ data: NewPassword },
	TContext
> => {
	const mutationKey = ["loginSetPassword"];
	const { mutation: mutationOptions } = options
		? options.mutation &&
			"mutationKey" in options.mutation &&
			options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey } };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof loginSetPassword>>,
		{ data: NewPassword }
	> = (props) => {
		const { data } = props ?? {};

		return loginSetPassword(data);
	};

	return { mutationFn, ...mutationOptions };
};

export type LoginSetPasswordMutationResult = NonNullable<
	Awaited<ReturnType<typeof loginSetPassword>>
>;
export type LoginSetPasswordMutationBody = NewPassword;
export type LoginSetPasswordMutationError =
	ErrorType<void | HTTPValidationError>;

/**
 * @summary Set Password
 */
export const useLoginSetPassword = <
	TError = ErrorType<void | HTTPValidationError>,
	TContext = unknown,
>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof loginSetPassword>>,
			TError,
			{ data: NewPassword },
			TContext
		>;
	},
	queryClient?: QueryClient,
): UseMutationResult<
	Awaited<ReturnType<typeof loginSetPassword>>,
	TError,
	{ data: NewPassword },
	TContext
> => {
	return useMutation(getLoginSetPasswordMutationOptions(options), queryClient);
};
