/**
 * Generated by orval v8.0.0-rc.2 🍺
 * Do not edit manually.
 * BarkByte
 * OpenAPI spec version: 0.1.0
 */
import * as zod from "zod";

/**
 * OAuth2 compatible token login, get an access token for future requests
 * @summary Login Access Token
 */
export const loginLoginAccessTokenResponseTokenTypeDefault = "bearer";

export const loginLoginAccessTokenResponse = zod.object({
	access_token: zod.string(),
	token_type: zod
		.string()
		.default(loginLoginAccessTokenResponseTokenTypeDefault),
});

/**
 * Test access token
 * @summary Test Token
 */
export const loginTestTokenResponseEmailMax = 255;

export const loginTestTokenResponseIsActiveDefault = false;
export const loginTestTokenResponseIsSuperuserDefault = false;
export const loginTestTokenResponseFullNameOneMax = 255;

export const loginTestTokenResponse = zod.object({
	email: zod.email().max(loginTestTokenResponseEmailMax),
	is_active: zod.boolean().default(loginTestTokenResponseIsActiveDefault),
	is_superuser: zod.boolean().default(loginTestTokenResponseIsSuperuserDefault),
	full_name: zod
		.union([zod.string().max(loginTestTokenResponseFullNameOneMax), zod.null()])
		.optional(),
	id: zod.uuid(),
});

/**
 * Password Recovery
 * @summary Recover Password
 */
export const loginRecoverPasswordParams = zod.object({
	email: zod.string(),
});

export const loginRecoverPasswordResponse = zod.object({
	message: zod.string(),
});

/**
 * Reset password
 * @summary Reset Password
 */
export const loginResetPasswordBodyNewPasswordMin = 8;
export const loginResetPasswordBodyNewPasswordMax = 64;

export const loginResetPasswordBody = zod.object({
	token: zod.string(),
	new_password: zod
		.string()
		.min(loginResetPasswordBodyNewPasswordMin)
		.max(loginResetPasswordBodyNewPasswordMax),
});

export const loginResetPasswordResponse = zod.object({
	message: zod.string(),
});
