/**
 * Generated by orval v8.0.0-rc.2 🍺
 * Do not edit manually.
 * BarkByte
 * OpenAPI spec version: 0.1.0
 */
import * as zod from "zod";

/**
 * OAuth2 compatible token login, get an access token for future requests
 * @summary Login Access Token
 */
export const loginLoginAccessTokenResponseTokenTypeDefault = "bearer";

export const loginLoginAccessTokenResponse = zod.object({
	access_token: zod.string(),
	token_type: zod
		.string()
		.default(loginLoginAccessTokenResponseTokenTypeDefault),
});

/**
 * Test access token
 * @summary Test Token
 */
export const loginTestTokenResponse = zod.object({
	email: zod.email(),
	full_name: zod.union([zod.string(), zod.null()]).optional(),
	id: zod.uuid(),
	is_active: zod.boolean(),
	is_superuser: zod.boolean(),
});

/**
 * Password Recovery
 * @summary Recover Password
 */
export const loginRecoverPasswordParams = zod.object({
	email: zod.string(),
});

export const loginRecoverPasswordResponse = zod.object({
	message: zod.string(),
});

/**
 * Reset password
 * @summary Reset Password
 */
export const loginResetPasswordBodyNewPasswordMin = 8;
export const loginResetPasswordBodyNewPasswordMax = 64;

export const loginResetPasswordBody = zod.object({
	new_password: zod
		.string()
		.min(loginResetPasswordBodyNewPasswordMin)
		.max(loginResetPasswordBodyNewPasswordMax),
	token: zod.string(),
});

export const loginResetPasswordResponse = zod.object({
	message: zod.string(),
});
