/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Timverse
 * OpenAPI spec version: 0.1.0
 */
import * as zod from "zod";

/**
 * OAuth2 compatible token login, get an access token for future requests
 * @summary Login Access Token
 */
export const loginLoginAccessTokenResponseTokenTypeDefault = `bearer`;

export const LoginLoginAccessTokenResponse = zod.object({
	access_token: zod.string(),
	token_type: zod
		.string()
		.default(loginLoginAccessTokenResponseTokenTypeDefault),
});

/**
 * Test access token
 * @summary Test Token
 */
export const LoginTestTokenResponse = zod.object({
	email: zod.email(),
	is_active: zod.boolean(),
	is_superuser: zod.boolean(),
	full_name: zod.union([zod.string(), zod.null()]).optional(),
	id: zod.uuid(),
});

/**
 * Password Recovery
 * @summary Recover Password
 */
export const LoginRecoverPasswordParams = zod.object({
	email: zod.string(),
});

export const LoginRecoverPasswordResponse = zod.object({
	message: zod.string(),
});

/**
 * Reset password
 * @summary Reset Password
 */
export const loginResetPasswordBodyNewPasswordMin = 8;
export const loginResetPasswordBodyNewPasswordMax = 64;

export const LoginResetPasswordBody = zod.object({
	token: zod.string(),
	new_password: zod
		.string()
		.min(loginResetPasswordBodyNewPasswordMin)
		.max(loginResetPasswordBodyNewPasswordMax),
});

export const LoginResetPasswordResponse = zod.object({
	message: zod.string(),
});
