/**
 * Generated by orval v8.0.0-rc.2 🍺
 * Do not edit manually.
 * BarkByte
 * OpenAPI spec version: 0.1.0
 */
import * as zod from "zod";

/**
 * Get all users.
 * @summary Get All Users
 */
export const privateGetAllUsersResponseItem = zod.object({
	email: zod.email(),
	full_name: zod.union([zod.string(), zod.null()]).optional(),
	id: zod.uuid(),
	is_active: zod.boolean(),
	is_superuser: zod.boolean(),
});
export const privateGetAllUsersResponse = zod.array(
	privateGetAllUsersResponseItem,
);

/**
 * Create a new user.
 * @summary Create User
 */
export const privateCreateUserBodyIsVerifiedDefault = "no";

export const privateCreateUserBody = zod.object({
	email: zod.string(),
	full_name: zod.string(),
	is_verified: zod.boolean().default(privateCreateUserBodyIsVerifiedDefault),
	password: zod.string(),
});

export const privateCreateUserResponse = zod.object({
	email: zod.email(),
	full_name: zod.union([zod.string(), zod.null()]).optional(),
	id: zod.uuid(),
	is_active: zod.boolean(),
	is_superuser: zod.boolean(),
});
