/**
 * Generated by orval v8.0.0-rc.2 🍺
 * Do not edit manually.
 * BarkByte
 * OpenAPI spec version: 0.1.0
 */

import type {
	DataTag,
	DefinedInitialDataOptions,
	DefinedUseQueryResult,
	MutationFunction,
	QueryClient,
	QueryFunction,
	QueryKey,
	UndefinedInitialDataOptions,
	UseMutationOptions,
	UseMutationResult,
	UseQueryOptions,
	UseQueryResult,
} from "@tanstack/react-query";
import { useMutation, useQuery } from "@tanstack/react-query";

import type {
	HTTPValidationError,
	PrivateUserCreate,
	UserPublic,
} from "../../model";

/**
 * Get all users.
 * @summary Get All Users
 */
export type privateGetAllUsersResponse200 = {
	data: UserPublic[];
	status: 200;
};

export type privateGetAllUsersResponseSuccess =
	privateGetAllUsersResponse200 & {
		headers: Headers;
	};

export type privateGetAllUsersResponse = privateGetAllUsersResponseSuccess;

export const getPrivateGetAllUsersUrl = () => {
	return `/api/v1/private/users/`;
};

export const privateGetAllUsers = async (
	options?: RequestInit,
): Promise<privateGetAllUsersResponse> => {
	const res = await fetch(getPrivateGetAllUsersUrl(), {
		...options,
		method: "GET",
	});

	const body = [204, 205, 304].includes(res.status) ? null : await res.text();

	const data: privateGetAllUsersResponse["data"] = body ? JSON.parse(body) : {};
	return {
		data,
		status: res.status,
		headers: res.headers,
	} as privateGetAllUsersResponse;
};

export const getPrivateGetAllUsersQueryKey = () => {
	return [`/api/v1/private/users/`] as const;
};

export const getPrivateGetAllUsersQueryOptions = <
	TData = Awaited<ReturnType<typeof privateGetAllUsers>>,
	TError = unknown,
>(options?: {
	query?: Partial<
		UseQueryOptions<
			Awaited<ReturnType<typeof privateGetAllUsers>>,
			TError,
			TData
		>
	>;
	fetch?: RequestInit;
}) => {
	const { query: queryOptions, fetch: fetchOptions } = options ?? {};

	const queryKey = queryOptions?.queryKey ?? getPrivateGetAllUsersQueryKey();

	const queryFn: QueryFunction<
		Awaited<ReturnType<typeof privateGetAllUsers>>
	> = ({ signal }) => privateGetAllUsers({ signal, ...fetchOptions });

	return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
		Awaited<ReturnType<typeof privateGetAllUsers>>,
		TError,
		TData
	> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type PrivateGetAllUsersQueryResult = NonNullable<
	Awaited<ReturnType<typeof privateGetAllUsers>>
>;
export type PrivateGetAllUsersQueryError = unknown;

export function usePrivateGetAllUsers<
	TData = Awaited<ReturnType<typeof privateGetAllUsers>>,
	TError = unknown,
>(
	options: {
		query: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof privateGetAllUsers>>,
				TError,
				TData
			>
		> &
			Pick<
				DefinedInitialDataOptions<
					Awaited<ReturnType<typeof privateGetAllUsers>>,
					TError,
					Awaited<ReturnType<typeof privateGetAllUsers>>
				>,
				"initialData"
			>;
		fetch?: RequestInit;
	},
	queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function usePrivateGetAllUsers<
	TData = Awaited<ReturnType<typeof privateGetAllUsers>>,
	TError = unknown,
>(
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof privateGetAllUsers>>,
				TError,
				TData
			>
		> &
			Pick<
				UndefinedInitialDataOptions<
					Awaited<ReturnType<typeof privateGetAllUsers>>,
					TError,
					Awaited<ReturnType<typeof privateGetAllUsers>>
				>,
				"initialData"
			>;
		fetch?: RequestInit;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function usePrivateGetAllUsers<
	TData = Awaited<ReturnType<typeof privateGetAllUsers>>,
	TError = unknown,
>(
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof privateGetAllUsers>>,
				TError,
				TData
			>
		>;
		fetch?: RequestInit;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get All Users
 */

export function usePrivateGetAllUsers<
	TData = Awaited<ReturnType<typeof privateGetAllUsers>>,
	TError = unknown,
>(
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof privateGetAllUsers>>,
				TError,
				TData
			>
		>;
		fetch?: RequestInit;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
} {
	const queryOptions = getPrivateGetAllUsersQueryOptions(options);

	const query = useQuery(queryOptions, queryClient) as UseQueryResult<
		TData,
		TError
	> & { queryKey: DataTag<QueryKey, TData, TError> };

	query.queryKey = queryOptions.queryKey;

	return query;
}

/**
 * Create a new user.
 * @summary Create User
 */
export type privateCreateUserResponse200 = {
	data: UserPublic;
	status: 200;
};

export type privateCreateUserResponse422 = {
	data: HTTPValidationError;
	status: 422;
};

export type privateCreateUserResponseSuccess = privateCreateUserResponse200 & {
	headers: Headers;
};
export type privateCreateUserResponseError = privateCreateUserResponse422 & {
	headers: Headers;
};

export type privateCreateUserResponse =
	| privateCreateUserResponseSuccess
	| privateCreateUserResponseError;

export const getPrivateCreateUserUrl = () => {
	return `/api/v1/private/users/`;
};

export const privateCreateUser = async (
	privateUserCreate: PrivateUserCreate,
	options?: RequestInit,
): Promise<privateCreateUserResponse> => {
	const res = await fetch(getPrivateCreateUserUrl(), {
		...options,
		method: "POST",
		headers: { "Content-Type": "application/json", ...options?.headers },
		body: JSON.stringify(privateUserCreate),
	});

	const body = [204, 205, 304].includes(res.status) ? null : await res.text();

	const data: privateCreateUserResponse["data"] = body ? JSON.parse(body) : {};
	return {
		data,
		status: res.status,
		headers: res.headers,
	} as privateCreateUserResponse;
};

export const getPrivateCreateUserMutationOptions = <
	TError = HTTPValidationError,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof privateCreateUser>>,
		TError,
		{ data: PrivateUserCreate },
		TContext
	>;
	fetch?: RequestInit;
}): UseMutationOptions<
	Awaited<ReturnType<typeof privateCreateUser>>,
	TError,
	{ data: PrivateUserCreate },
	TContext
> => {
	const mutationKey = ["privateCreateUser"];
	const { mutation: mutationOptions, fetch: fetchOptions } = options
		? options.mutation &&
			"mutationKey" in options.mutation &&
			options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey }, fetch: undefined };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof privateCreateUser>>,
		{ data: PrivateUserCreate }
	> = (props) => {
		const { data } = props ?? {};

		return privateCreateUser(data, fetchOptions);
	};

	return { mutationFn, ...mutationOptions };
};

export type PrivateCreateUserMutationResult = NonNullable<
	Awaited<ReturnType<typeof privateCreateUser>>
>;
export type PrivateCreateUserMutationBody = PrivateUserCreate;
export type PrivateCreateUserMutationError = HTTPValidationError;

/**
 * @summary Create User
 */
export const usePrivateCreateUser = <
	TError = HTTPValidationError,
	TContext = unknown,
>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof privateCreateUser>>,
			TError,
			{ data: PrivateUserCreate },
			TContext
		>;
		fetch?: RequestInit;
	},
	queryClient?: QueryClient,
): UseMutationResult<
	Awaited<ReturnType<typeof privateCreateUser>>,
	TError,
	{ data: PrivateUserCreate },
	TContext
> => {
	const mutationOptions = getPrivateCreateUserMutationOptions(options);

	return useMutation(mutationOptions, queryClient);
};
