/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Timverse
 * OpenAPI spec version: 1.0.0
 */

import type {
	DataTag,
	DefinedInitialDataOptions,
	DefinedUseQueryResult,
	MutationFunction,
	QueryClient,
	QueryFunction,
	QueryKey,
	UndefinedInitialDataOptions,
	UseMutationOptions,
	UseMutationResult,
	UseQueryOptions,
	UseQueryResult,
} from "@tanstack/react-query";
import { useMutation, useQuery } from "@tanstack/react-query";

import type {
	HTTPValidationError,
	PrivateUserCreate,
	UserPublic,
} from "../../model";
import type { ErrorType } from "../../mutator/custom-instance";
import { customInstance } from "../../mutator/custom-instance";

/**
 * Get all users.
 * @summary Get All Users
 */
export const privateGetAllUsers = (signal?: AbortSignal) => {
	return customInstance<UserPublic[]>({
		url: `/api/v1/private/users/`,
		method: "GET",
		signal,
	});
};

export const getPrivateGetAllUsersQueryKey = () => {
	return [`/api/v1/private/users/`] as const;
};

export const getPrivateGetAllUsersQueryOptions = <
	TData = Awaited<ReturnType<typeof privateGetAllUsers>>,
	TError = ErrorType<unknown>,
>(options?: {
	query?: Partial<
		UseQueryOptions<
			Awaited<ReturnType<typeof privateGetAllUsers>>,
			TError,
			TData
		>
	>;
}) => {
	const { query: queryOptions } = options ?? {};

	const queryKey = queryOptions?.queryKey ?? getPrivateGetAllUsersQueryKey();

	const queryFn: QueryFunction<
		Awaited<ReturnType<typeof privateGetAllUsers>>
	> = ({ signal }) => privateGetAllUsers(signal);

	return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
		Awaited<ReturnType<typeof privateGetAllUsers>>,
		TError,
		TData
	> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type PrivateGetAllUsersQueryResult = NonNullable<
	Awaited<ReturnType<typeof privateGetAllUsers>>
>;
export type PrivateGetAllUsersQueryError = ErrorType<unknown>;

export function usePrivateGetAllUsers<
	TData = Awaited<ReturnType<typeof privateGetAllUsers>>,
	TError = ErrorType<unknown>,
>(
	options: {
		query: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof privateGetAllUsers>>,
				TError,
				TData
			>
		> &
			Pick<
				DefinedInitialDataOptions<
					Awaited<ReturnType<typeof privateGetAllUsers>>,
					TError,
					Awaited<ReturnType<typeof privateGetAllUsers>>
				>,
				"initialData"
			>;
	},
	queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function usePrivateGetAllUsers<
	TData = Awaited<ReturnType<typeof privateGetAllUsers>>,
	TError = ErrorType<unknown>,
>(
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof privateGetAllUsers>>,
				TError,
				TData
			>
		> &
			Pick<
				UndefinedInitialDataOptions<
					Awaited<ReturnType<typeof privateGetAllUsers>>,
					TError,
					Awaited<ReturnType<typeof privateGetAllUsers>>
				>,
				"initialData"
			>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function usePrivateGetAllUsers<
	TData = Awaited<ReturnType<typeof privateGetAllUsers>>,
	TError = ErrorType<unknown>,
>(
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof privateGetAllUsers>>,
				TError,
				TData
			>
		>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get All Users
 */

export function usePrivateGetAllUsers<
	TData = Awaited<ReturnType<typeof privateGetAllUsers>>,
	TError = ErrorType<unknown>,
>(
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof privateGetAllUsers>>,
				TError,
				TData
			>
		>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
} {
	const queryOptions = getPrivateGetAllUsersQueryOptions(options);

	const query = useQuery(queryOptions, queryClient) as UseQueryResult<
		TData,
		TError
	> & { queryKey: DataTag<QueryKey, TData, TError> };

	return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * Create a new user.
 * @summary Create User
 */
export const privateCreateUser = (
	privateUserCreate: PrivateUserCreate,
	signal?: AbortSignal,
) => {
	return customInstance<UserPublic>({
		url: `/api/v1/private/users/`,
		method: "POST",
		headers: { "Content-Type": "application/json" },
		data: privateUserCreate,
		signal,
	});
};

export const getPrivateCreateUserMutationOptions = <
	TError = ErrorType<HTTPValidationError>,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof privateCreateUser>>,
		TError,
		{ data: PrivateUserCreate },
		TContext
	>;
}): UseMutationOptions<
	Awaited<ReturnType<typeof privateCreateUser>>,
	TError,
	{ data: PrivateUserCreate },
	TContext
> => {
	const mutationKey = ["privateCreateUser"];
	const { mutation: mutationOptions } = options
		? options.mutation &&
			"mutationKey" in options.mutation &&
			options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey } };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof privateCreateUser>>,
		{ data: PrivateUserCreate }
	> = (props) => {
		const { data } = props ?? {};

		return privateCreateUser(data);
	};

	return { mutationFn, ...mutationOptions };
};

export type PrivateCreateUserMutationResult = NonNullable<
	Awaited<ReturnType<typeof privateCreateUser>>
>;
export type PrivateCreateUserMutationBody = PrivateUserCreate;
export type PrivateCreateUserMutationError = ErrorType<HTTPValidationError>;

/**
 * @summary Create User
 */
export const usePrivateCreateUser = <
	TError = ErrorType<HTTPValidationError>,
	TContext = unknown,
>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof privateCreateUser>>,
			TError,
			{ data: PrivateUserCreate },
			TContext
		>;
	},
	queryClient?: QueryClient,
): UseMutationResult<
	Awaited<ReturnType<typeof privateCreateUser>>,
	TError,
	{ data: PrivateUserCreate },
	TContext
> => {
	return useMutation(getPrivateCreateUserMutationOptions(options), queryClient);
};
