/**
 * Generated by orval v8.0.0-rc.2 🍺
 * Do not edit manually.
 * BarkByte
 * OpenAPI spec version: 0.1.0
 */
import * as zod from "zod";

/**
 * Get all users.
 * @summary Get All Users
 */
export const privateGetAllUsersResponseEmailMax = 255;

export const privateGetAllUsersResponseIsActiveDefault = false;
export const privateGetAllUsersResponseIsSuperuserDefault = false;
export const privateGetAllUsersResponseFullNameOneMax = 255;

export const privateGetAllUsersResponseItem = zod.object({
	email: zod.email().max(privateGetAllUsersResponseEmailMax),
	is_active: zod.boolean().default(privateGetAllUsersResponseIsActiveDefault),
	is_superuser: zod
		.boolean()
		.default(privateGetAllUsersResponseIsSuperuserDefault),
	full_name: zod
		.union([
			zod.string().max(privateGetAllUsersResponseFullNameOneMax),
			zod.null(),
		])
		.optional(),
	id: zod.uuid(),
});
export const privateGetAllUsersResponse = zod.array(
	privateGetAllUsersResponseItem,
);

/**
 * Create a new user.
 * @summary Create User
 */
export const privateCreateUserBodyIsVerifiedDefault = false;

export const privateCreateUserBody = zod.object({
	email: zod.string(),
	password: zod.string(),
	full_name: zod.string(),
	is_verified: zod.boolean().default(privateCreateUserBodyIsVerifiedDefault),
});

export const privateCreateUserResponseEmailMax = 255;

export const privateCreateUserResponseIsActiveDefault = false;
export const privateCreateUserResponseIsSuperuserDefault = false;
export const privateCreateUserResponseFullNameOneMax = 255;

export const privateCreateUserResponse = zod.object({
	email: zod.email().max(privateCreateUserResponseEmailMax),
	is_active: zod.boolean().default(privateCreateUserResponseIsActiveDefault),
	is_superuser: zod
		.boolean()
		.default(privateCreateUserResponseIsSuperuserDefault),
	full_name: zod
		.union([
			zod.string().max(privateCreateUserResponseFullNameOneMax),
			zod.null(),
		])
		.optional(),
	id: zod.uuid(),
});
