/**
 * Generated by orval v8.0.0-rc.2 🍺
 * Do not edit manually.
 * BarkByte
 * OpenAPI spec version: 0.1.0
 */
import * as zod from "zod";

/**
 * Retrieve loading direction.
 * @summary Get Loading Directions
 */
export const loadingdirectionGetLoadingDirectionsQuerySkipDefault = 0;
export const loadingdirectionGetLoadingDirectionsQueryLimitDefault = 100;

export const loadingdirectionGetLoadingDirectionsQueryParams = zod.object({
	skip: zod
		.number()
		.default(loadingdirectionGetLoadingDirectionsQuerySkipDefault),
	limit: zod
		.number()
		.default(loadingdirectionGetLoadingDirectionsQueryLimitDefault),
});

export const loadingdirectionGetLoadingDirectionsResponseDataItemLabelMax = 255;

export const loadingdirectionGetLoadingDirectionsResponse = zod.object({
	count: zod.number(),
	data: zod.array(
		zod.object({
			id: zod.uuid().optional(),
			label: zod
				.string()
				.min(1)
				.max(loadingdirectionGetLoadingDirectionsResponseDataItemLabelMax),
		}),
	),
});

/**
 * Create loading direction.
 * @summary Create Loading Direction
 */
export const loadingdirectionCreateLoadingDirectionBodyLabelMax = 255;

export const loadingdirectionCreateLoadingDirectionBody = zod.object({
	label: zod
		.string()
		.min(1)
		.max(loadingdirectionCreateLoadingDirectionBodyLabelMax),
});

export const loadingdirectionCreateLoadingDirectionResponseLabelMax = 255;

export const loadingdirectionCreateLoadingDirectionResponse = zod.object({
	id: zod.uuid().optional(),
	label: zod
		.string()
		.min(1)
		.max(loadingdirectionCreateLoadingDirectionResponseLabelMax),
});

/**
 * Delete loading direction ONLY if not in use.
 * @summary Delete Loading Direction
 */
export const loadingdirectionDeleteLoadingDirectionParams = zod.object({
	id: zod.uuid(),
});

export const loadingdirectionDeleteLoadingDirectionResponse = zod.unknown();

/**
 * Update loading direction.
 * @summary Update Loading Direction
 */
export const loadingdirectionUpdateLoadingDirectionParams = zod.object({
	id: zod.uuid(),
});

export const loadingdirectionUpdateLoadingDirectionBodyLabelMax = 255;

export const loadingdirectionUpdateLoadingDirectionBody = zod.object({
	label: zod
		.string()
		.min(1)
		.max(loadingdirectionUpdateLoadingDirectionBodyLabelMax),
});

export const loadingdirectionUpdateLoadingDirectionResponseLabelMax = 255;

export const loadingdirectionUpdateLoadingDirectionResponse = zod.object({
	id: zod.uuid().optional(),
	label: zod
		.string()
		.min(1)
		.max(loadingdirectionUpdateLoadingDirectionResponseLabelMax),
});
