/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Timverse
 * OpenAPI spec version: 1.0.0
 */
import * as zod from "zod";

/**
 * Retrieve loading direction.
 * @summary Get Loading Directions
 */
export const loadingdirectionGetLoadingDirectionsQuerySkipDefault = 0;
export const loadingdirectionGetLoadingDirectionsQueryLimitDefault = 100;

export const LoadingdirectionGetLoadingDirectionsQueryParams = zod.object({
	skip: zod
		.number()
		.default(loadingdirectionGetLoadingDirectionsQuerySkipDefault),
	limit: zod
		.number()
		.default(loadingdirectionGetLoadingDirectionsQueryLimitDefault),
});

export const loadingdirectionGetLoadingDirectionsResponseDataItemLabelMax = 255;

export const LoadingdirectionGetLoadingDirectionsResponse = zod.object({
	data: zod.array(
		zod.object({
			id: zod.uuid().optional(),
			label: zod
				.string()
				.min(1)
				.max(loadingdirectionGetLoadingDirectionsResponseDataItemLabelMax),
		}),
	),
	count: zod.number(),
});

/**
 * Create loading direction.
 * @summary Create Loading Direction
 */
export const loadingdirectionCreateLoadingDirectionBodyLabelMax = 255;

export const LoadingdirectionCreateLoadingDirectionBody = zod.object({
	label: zod
		.string()
		.min(1)
		.max(loadingdirectionCreateLoadingDirectionBodyLabelMax),
});

export const loadingdirectionCreateLoadingDirectionResponseLabelMax = 255;

export const LoadingdirectionCreateLoadingDirectionResponse = zod.object({
	id: zod.uuid().optional(),
	label: zod
		.string()
		.min(1)
		.max(loadingdirectionCreateLoadingDirectionResponseLabelMax),
});

/**
 * Update loading direction.
 * @summary Update Loading Direction
 */
export const LoadingdirectionUpdateLoadingDirectionParams = zod.object({
	id: zod.uuid(),
});

export const loadingdirectionUpdateLoadingDirectionBodyLabelMax = 255;

export const LoadingdirectionUpdateLoadingDirectionBody = zod.object({
	label: zod
		.string()
		.min(1)
		.max(loadingdirectionUpdateLoadingDirectionBodyLabelMax),
});

export const loadingdirectionUpdateLoadingDirectionResponseLabelMax = 255;

export const LoadingdirectionUpdateLoadingDirectionResponse = zod.object({
	id: zod.uuid().optional(),
	label: zod
		.string()
		.min(1)
		.max(loadingdirectionUpdateLoadingDirectionResponseLabelMax),
});

/**
 * Delete loading direction ONLY if not in use.
 * @summary Delete Loading Direction
 */
export const LoadingdirectionDeleteLoadingDirectionParams = zod.object({
	id: zod.uuid(),
});

export const LoadingdirectionDeleteLoadingDirectionResponse = zod.unknown();
