"""Add DOI table and link from specimen

Revision ID: 0a459bb4abe8
Revises: 441ec59c0855
Create Date: 2025-11-27 22:14:19.657878

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '0a459bb4abe8'
down_revision: Union[str, None] = '441ec59c0855'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('doi',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('link', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('ref_title', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('authors', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('pub_year', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('link')
    )
    op.add_column('specimen', sa.Column('doi_id', sa.Uuid(), nullable=False))
    op.create_foreign_key(None, 'specimen', 'doi', ['doi_id'], ['id'])
    op.drop_column('specimen', 'author')
    op.drop_column('specimen', 'is_approved')
    op.drop_column('specimen', 'reference_title')
    op.drop_column('specimen', 'publication_year')
    op.drop_column('specimen', 'doi')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.add_column('specimen', sa.Column('doi', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('specimen', sa.Column('publication_year', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('specimen', sa.Column('reference_title', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('specimen', sa.Column('is_approved', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('specimen', sa.Column('author', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'specimen', type_='foreignkey')
    op.drop_column('specimen', 'doi_id')
    op.drop_table('doi')
    # ### end Alembic commands ###
