"""removed reinforcement, added in moisture percentage

Revision ID: 1da82a9985f8
Revises: c9692d272de0
Create Date: 2025-10-01 17:29:36.285762

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1da82a9985f8'
down_revision: Union[str, None] = 'c9692d272de0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('specimen', sa.Column('moisture_percentage', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False))
    op.drop_column('specimen', 'reinforcement')
    sa.Enum('NONE', 'STRAP', 'BLOCKING', name='reinforcement').drop(op.get_bind())
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('NONE', 'STRAP', 'BLOCKING', name='reinforcement').create(op.get_bind())
    op.add_column('specimen', sa.Column('reinforcement', postgresql.ENUM('NONE', 'STRAP', 'BLOCKING', name='reinforcement', create_type=False), autoincrement=False, nullable=True))
    op.drop_column('specimen', 'moisture_percentage')
    # ### end Alembic commands ###
