"""not unique label joinery type

Revision ID: 28fb6e9fce4b
Revises: 4b0e92013309
Create Date: 2025-09-09 14:47:27.977980

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '28fb6e9fce4b'
down_revision: Union[str, None] = '4b0e92013309'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('joinerytype_label_key'), 'joinerytype', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('joinerytype_label_key'), 'joinerytype', ['label'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
