"""add dowel, update some enums

Revision ID: 29cad80d2c42
Revises: ebcabed554c5
Create Date: 2025-09-08 18:54:10.374619

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from alembic_postgresql_enum import TableReference

# revision identifiers, used by Alembic.
revision: str = '29cad80d2c42'
down_revision: Union[str, None] = 'ebcabed554c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'failuremode', ['label'])
    op.add_column('specimen', sa.Column('dowel', sa.Boolean(), nullable=False))
    op.create_unique_constraint(None, 'specimen', ['doi'])
    op.sync_enum_values(
        enum_schema='public',
        enum_name='testloadingtype',
        new_values=['CYCLIC', 'MONOTONIC', 'MONOTONICANDCYCLIC'],
        affected_columns=[TableReference(table_schema='public', table_name='specimen', column_name='e_test_loading_type')],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        enum_schema='public',
        enum_name='testloadingtype',
        new_values=['CYCLIC', 'MONOTONIC'],
        affected_columns=[TableReference(table_schema='public', table_name='specimen', column_name='e_test_loading_type')],
        enum_values_to_rename=[],
    )
    op.drop_constraint(None, 'specimen', type_='unique')
    op.drop_column('specimen', 'dowel')
    op.drop_constraint(None, 'failuremode', type_='unique')
    # ### end Alembic commands ###
