"""remove FEMA P795 from yield point method enum

Revision ID: 2c1937cc9803
Revises: a2563f8e2add
Create Date: 2026-04-16 16:44:09.560469

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from alembic_postgresql_enum import TableReference
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2c1937cc9803'
down_revision: Union[str, None] = 'a2563f8e2add'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('specimen', 'moisture_percentage',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('specimen', 'e_test_loading_type',
               existing_type=postgresql.ENUM('CYCLIC', 'MONOTONIC', 'MONOTONICANDCYCLIC', name='testloadingtype'),
               nullable=False)
    op.alter_column('specimen', 'e_yield_point_method',
               existing_type=postgresql.ENUM('CEN16', 'EEEP', 'FEMAP795', name='yieldpointmethod'),
               nullable=False)
    op.alter_column('specimen', 'e_stiffness',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('specimen', 'e_yield_displacement',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('specimen', 'e_yield_force',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('specimen', 'e_max_displacement',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('specimen', 'e_max_force',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('specimen', 'e_ultimate_displacement',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('specimen', 'e_ultimate_force',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('specimen', 'e_ductility',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.sync_enum_values(
        enum_schema='public',
        enum_name='yieldpointmethod',
        new_values=['CEN16', 'EEEP'],
        affected_columns=[TableReference(table_schema='public', table_name='specimen', column_name='e_yield_point_method')],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        enum_schema='public',
        enum_name='yieldpointmethod',
        new_values=['CEN16', 'EEEP', 'FEMAP795'],
        affected_columns=[TableReference(table_schema='public', table_name='specimen', column_name='e_yield_point_method')],
        enum_values_to_rename=[],
    )
    op.alter_column('specimen', 'e_ductility',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('specimen', 'e_ultimate_force',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('specimen', 'e_ultimate_displacement',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('specimen', 'e_max_force',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('specimen', 'e_max_displacement',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('specimen', 'e_yield_force',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('specimen', 'e_yield_displacement',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('specimen', 'e_stiffness',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('specimen', 'e_yield_point_method',
               existing_type=postgresql.ENUM('CEN16', 'EEEP', 'FEMAP795', name='yieldpointmethod'),
               nullable=True)
    op.alter_column('specimen', 'e_test_loading_type',
               existing_type=postgresql.ENUM('CYCLIC', 'MONOTONIC', 'MONOTONICANDCYCLIC', name='testloadingtype'),
               nullable=True)
    op.alter_column('specimen', 'moisture_percentage',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    # ### end Alembic commands ###
