"""removing e measurement unit

Revision ID: 324633d326fb
Revises: 66119ed7f2d9
Create Date: 2025-12-18 17:44:00.893312

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '324633d326fb'
down_revision: Union[str, None] = '66119ed7f2d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('specimen', 'e_measurement_unit')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('specimen', sa.Column('e_measurement_unit', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
