"""adding loading direction table

Revision ID: 4d9d54f9a67b
Revises: 510bd0cb73ba
Create Date: 2025-09-10 16:56:35.706769

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '4d9d54f9a67b'
down_revision: Union[str, None] = '510bd0cb73ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('loadingdirection',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('label', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('specimenloadingdirection',
    sa.Column('specimen_id', sa.Uuid(), nullable=False),
    sa.Column('loading_direction_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['loading_direction_id'], ['loadingdirection.id'], ),
    sa.ForeignKeyConstraint(['specimen_id'], ['specimen.id'], ),
    sa.PrimaryKeyConstraint('specimen_id', 'loading_direction_id')
    )
    op.drop_column('specimen', 'loading_direction')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('specimen', sa.Column('loading_direction', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_table('specimenloadingdirection')
    op.drop_table('loadingdirection')
    # ### end Alembic commands ###
