"""drop Loading Direction enum

Revision ID: 510bd0cb73ba
Revises: 0e0b369df122
Create Date: 2025-09-10 16:36:25.980196

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '510bd0cb73ba'
down_revision: Union[str, None] = '0e0b369df122'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('specimen', 'loading_direction',
               existing_type=postgresql.ENUM('INPLANESHEAR', 'OUTPLANESHEAR', 'INPLANETENSION', 'OUTPLANETENSION', name='loadingdirection'),
               type_=sqlmodel.sql.sqltypes.AutoString(length=255),
               existing_nullable=False)
    sa.Enum('INPLANESHEAR', 'OUTPLANESHEAR', 'INPLANETENSION', 'OUTPLANETENSION', name='loadingdirection').drop(op.get_bind())
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('INPLANESHEAR', 'OUTPLANESHEAR', 'INPLANETENSION', 'OUTPLANETENSION', name='loadingdirection').create(op.get_bind())
    op.alter_column('specimen', 'loading_direction',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=255),
               type_=postgresql.ENUM('INPLANESHEAR', 'OUTPLANESHEAR', 'INPLANETENSION', 'OUTPLANETENSION', name='loadingdirection'),
               existing_nullable=False)
    # ### end Alembic commands ###
