"""element_dimension character limit increase

Revision ID: 66119ed7f2d9
Revises: 00bb2bddcf1e
Create Date: 2025-12-18 17:26:37.948831

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '66119ed7f2d9'
down_revision: Union[str, None] = '00bb2bddcf1e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('specimen', 'element_dimension',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(length=1000),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('specimen', 'element_dimension',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=1000),
               type_=sa.TEXT(),
               existing_nullable=False)
    # ### end Alembic commands ###
