"""removing reinforcement_mechanical_properties

Revision ID: 6c4f6d2a3de0
Revises: 1da82a9985f8
Create Date: 2025-10-15 02:45:03.209783

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '6c4f6d2a3de0'
down_revision: Union[str, None] = '1da82a9985f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('specimen', 'reinforcement_mechanical_properties')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('specimen', sa.Column('reinforcement_mechanical_properties', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
