"""add sub joinery type

Revision ID: 84416e21e4b3
Revises: 9e2a440b1ed2
Create Date: 2025-09-09 20:14:29.944207

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '84416e21e4b3'
down_revision: Union[str, None] = '9e2a440b1ed2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subjoinerytype',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('joinery_type_id', sa.Uuid(), nullable=False),
    sa.Column('label', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.ForeignKeyConstraint(['joinery_type_id'], ['joinerytype.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('specimen', sa.Column('sub_joinery_type_id', sa.Uuid(), nullable=False))
    op.create_foreign_key(None, 'specimen', 'subjoinerytype', ['sub_joinery_type_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'specimen', type_='foreignkey')
    op.drop_column('specimen', 'sub_joinery_type_id')
    op.drop_table('subjoinerytype')
    # ### end Alembic commands ###
