"""joinerytype update

Revision ID: 9e2a440b1ed2
Revises: c09e087327b9
Create Date: 2025-09-09 15:20:25.992172

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '9e2a440b1ed2'
down_revision: Union[str, None] = 'c09e087327b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('specimen', sa.Column('joinery_type_id', sa.Uuid(), nullable=False))
    op.create_foreign_key(None, 'specimen', 'joinerytype', ['joinery_type_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'specimen', type_='foreignkey')
    op.drop_column('specimen', 'joinery_type_id')
    # ### end Alembic commands ###
