"""add pending specimen comments

Revision ID: a2563f8e2add
Revises: 20511c826214
Create Date: 2026-03-17 19:54:47.908684

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'a2563f8e2add'
down_revision: Union[str, None] = '324633d326fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pendingspecimen', sa.Column('comment_by_author', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pendingspecimen', 'comment_by_author')
    # ### end Alembic commands ###
