"""Add cascade delete to specimen link tables

Revision ID: e8eb0057bb95
Revises: 0a459bb4abe8
Create Date: 2025-11-28 23:58:25.412478

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'e8eb0057bb95'
down_revision: Union[str, None] = '0a459bb4abe8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('specimenfailuremode_specimen_id_fkey'), 'specimenfailuremode', type_='foreignkey')
    op.create_foreign_key(None, 'specimenfailuremode', 'specimen', ['specimen_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('specimenfastenertype_specimen_id_fkey'), 'specimenfastenertype', type_='foreignkey')
    op.create_foreign_key(None, 'specimenfastenertype', 'specimen', ['specimen_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('specimenloadingdirection_specimen_id_fkey'), 'specimenloadingdirection', type_='foreignkey')
    op.create_foreign_key(None, 'specimenloadingdirection', 'specimen', ['specimen_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'specimenloadingdirection', type_='foreignkey')
    op.create_foreign_key(op.f('specimenloadingdirection_specimen_id_fkey'), 'specimenloadingdirection', 'specimen', ['specimen_id'], ['id'])
    op.drop_constraint(None, 'specimenfastenertype', type_='foreignkey')
    op.create_foreign_key(op.f('specimenfastenertype_specimen_id_fkey'), 'specimenfastenertype', 'specimen', ['specimen_id'], ['id'])
    op.drop_constraint(None, 'specimenfailuremode', type_='foreignkey')
    op.create_foreign_key(op.f('specimenfailuremode_specimen_id_fkey'), 'specimenfailuremode', 'specimen', ['specimen_id'], ['id'])
    # ### end Alembic commands ###
