"""add_failuremode_and_enums

Revision ID: ebcabed554c5
Revises: 3e824684c864
Create Date: 2025-08-19 19:48:09.852743

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'ebcabed554c5'
down_revision: Union[str, None] = '3e824684c864'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('CEN16', 'EEEP', name='yieldpointmethod').create(op.get_bind())
    sa.Enum('CYCLIC', 'MONOTONIC', name='testloadingtype').create(op.get_bind())
    sa.Enum('NONE', 'STRAP', 'BLOCKING', name='reinforcement').create(op.get_bind())
    sa.Enum('CONVENTIONAL', 'RESEARCHANDDEVELOPMENT', name='practice').create(op.get_bind())
    sa.Enum('INPLANESHEAR', 'OUTPLANESHEAR', 'INPLANETENSION', 'OUTPLANETENSION', name='loadingdirection').create(op.get_bind())
    sa.Enum('NAIL', 'SCREW', 'BOLT', name='fastenertype').create(op.get_bind())
    sa.Enum('HOLDOWN', 'SPLINEJOINT', name='joinerytype').create(op.get_bind())
    sa.Enum('WALLFLOOR', 'WALLWALL', name='assemblytype').create(op.get_bind())
    op.create_table('failuremode',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('label', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('specimenfailuremode',
    sa.Column('specimen_id', sa.Uuid(), nullable=False),
    sa.Column('failure_mode_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['failure_mode_id'], ['failuremode.id'], ),
    sa.ForeignKeyConstraint(['specimen_id'], ['specimen.id'], ),
    sa.PrimaryKeyConstraint('specimen_id', 'failure_mode_id')
    )
    op.alter_column('specimen', 'assembly_type',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Enum('WALLFLOOR', 'WALLWALL', name='assemblytype'),
               existing_nullable=False,
               postgresql_using='assembly_type::assemblytype')
    op.alter_column('specimen', 'joinery_type',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Enum('HOLDOWN', 'SPLINEJOINT', name='joinerytype'),
               existing_nullable=False,
               postgresql_using='joinery_type::joinerytype')
    op.alter_column('specimen', 'fastener_type',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Enum('NAIL', 'SCREW', 'BOLT', name='fastenertype'),
               existing_nullable=False,
               postgresql_using='fastener_type::fastenertype')
    op.alter_column('specimen', 'loading_direction',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Enum('INPLANESHEAR', 'OUTPLANESHEAR', 'INPLANETENSION', 'OUTPLANETENSION', name='loadingdirection'),
               existing_nullable=False,
               postgresql_using='loading_direction::loadingdirection')
    op.alter_column('specimen', 'practice',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Enum('CONVENTIONAL', 'RESEARCHANDDEVELOPMENT', name='practice'),
               existing_nullable=False,
               postgresql_using='practice::practice')
    op.alter_column('specimen', 'reinforcement',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Enum('NONE', 'STRAP', 'BLOCKING', name='reinforcement'),
               existing_nullable=True,
               postgresql_using='reinforcement::reinforcement')
    op.alter_column('specimen', 'fastener_numbers',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('specimen', 'e_test_loading_type',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Enum('CYCLIC', 'MONOTONIC', name='testloadingtype'),
               existing_nullable=True,
               postgresql_using='e_test_loading_type::testloadingtype')
    op.alter_column('specimen', 'e_yield_point_method',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Enum('CEN16', 'EEEP', name='yieldpointmethod'),
               existing_nullable=True,
               postgresql_using='e_yield_point_method::yieldpointmethod')
    op.drop_column('specimen', 'e_qualitative_failure_meaure')
    op.drop_column('specimen', 'e_description')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('specimen', sa.Column('e_description', sa.VARCHAR(length=1024), autoincrement=False, nullable=True))
    op.add_column('specimen', sa.Column('e_qualitative_failure_meaure', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.alter_column('specimen', 'e_yield_point_method',
               existing_type=sa.Enum('CEN16', 'EEEP', name='yieldpointmethod'),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('specimen', 'e_test_loading_type',
               existing_type=sa.Enum('CYCLIC', 'MONOTONIC', name='testloadingtype'),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('specimen', 'fastener_numbers',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('specimen', 'reinforcement',
               existing_type=sa.Enum('NONE', 'STRAP', 'BLOCKING', name='reinforcement'),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('specimen', 'practice',
               existing_type=sa.Enum('CONVENTIONAL', 'RESEARCHANDDEVELOPMENT', name='practice'),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.alter_column('specimen', 'loading_direction',
               existing_type=sa.Enum('INPLANESHEAR', 'OUTPLANESHEAR', 'INPLANETENSION', 'OUTPLANETENSION', name='loadingdirection'),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.alter_column('specimen', 'fastener_type',
               existing_type=sa.Enum('NAIL', 'SCREW', 'BOLT', name='fastenertype'),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.alter_column('specimen', 'joinery_type',
               existing_type=sa.Enum('HOLDOWN', 'SPLINEJOINT', name='joinerytype'),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.alter_column('specimen', 'assembly_type',
               existing_type=sa.Enum('WALLFLOOR', 'WALLWALL', name='assemblytype'),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.drop_table('specimenfailuremode')
    op.drop_table('failuremode')
    sa.Enum('WALLFLOOR', 'WALLWALL', name='assemblytype').drop(op.get_bind())
    sa.Enum('HOLDOWN', 'SPLINEJOINT', name='joinerytype').drop(op.get_bind())
    sa.Enum('NAIL', 'SCREW', 'BOLT', name='fastenertype').drop(op.get_bind())
    sa.Enum('INPLANESHEAR', 'OUTPLANESHEAR', 'INPLANETENSION', 'OUTPLANETENSION', name='loadingdirection').drop(op.get_bind())
    sa.Enum('CONVENTIONAL', 'RESEARCHANDDEVELOPMENT', name='practice').drop(op.get_bind())
    sa.Enum('NONE', 'STRAP', 'BLOCKING', name='reinforcement').drop(op.get_bind())
    sa.Enum('CYCLIC', 'MONOTONIC', name='testloadingtype').drop(op.get_bind())
    sa.Enum('CEN16', 'EEEP', name='yieldpointmethod').drop(op.get_bind())
    # ### end Alembic commands ###
