"""removing doi uniqueness for now

Revision ID: ec248ebf0da9
Revises: 5f161af60c30
Create Date: 2025-11-10 21:38:08.616186

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'ec248ebf0da9'
down_revision: Union[str, None] = '5f161af60c30'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('specimen_doi_key'), 'specimen', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('specimen_doi_key'), 'specimen', ['doi'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
