"""expand connector_mechanical_properties

Revision ID: fff0dc2fd410
Revises: 6c4f6d2a3de0
Create Date: 2025-11-10 19:40:28.631478

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'fff0dc2fd410'
down_revision: Union[str, None] = '6c4f6d2a3de0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('specimen', 'wood_mechanical_properties',
               existing_type=sa.VARCHAR(length=255),
               type_=sqlmodel.sql.sqltypes.AutoString(length=500),
               existing_nullable=True)
    op.alter_column('specimen', 'connector_mechanical_properties',
               existing_type=sa.VARCHAR(length=255),
               type_=sqlmodel.sql.sqltypes.AutoString(length=500),
               existing_nullable=True)
    op.alter_column('specimen', 'fastener_mechanical_properties',
               existing_type=sa.VARCHAR(length=255),
               type_=sqlmodel.sql.sqltypes.AutoString(length=500),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('specimen', 'fastener_mechanical_properties',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=500),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('specimen', 'connector_mechanical_properties',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=500),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('specimen', 'wood_mechanical_properties',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=500),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    # ### end Alembic commands ###
