/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * BarkByte
 * OpenAPI spec version: 0.1.0
 */

export type AssemblyType = (typeof AssemblyType)[keyof typeof AssemblyType];

export const AssemblyType = {
	"Wall-Floor": "Wall-Floor",
	"Wall-Wall": "Wall-Wall",
	"Wall-Floor_&_Wall-Wall": "Wall-Floor & Wall-Wall",
} as const;
