/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * BarkByte
 * OpenAPI spec version: 1.1.0
 */

export interface BodyLoginLoginAccessToken {
	grant_type?: string | null;
	username: string;
	password: string;
	scope?: string;
	client_id?: string | null;
	client_secret?: string | null;
}
