/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Timverse
 * OpenAPI spec version: 0.1.0
 */

export interface Doi {
	id?: string;
	/**
	 * @minLength 1
	 * @maxLength 255
	 */
	link: string;
	/**
	 * @minLength 1
	 * @maxLength 255
	 */
	ref_title: string;
	/**
	 * @minLength 1
	 * @maxLength 255
	 */
	authors: string;
	pub_year: number;
}
