/**
 * Generated by orval v8.0.0-rc.2 🍺
 * Do not edit manually.
 * BarkByte
 * OpenAPI spec version: 0.1.0
 */

export interface DOICreate {
	authors: string;
	link: string;
	pub_year: number;
	ref_title: string;
}
