/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * BarkByte
 * OpenAPI spec version: 0.1.0
 */

/**
 * What you return via API.
 */
export interface DOIPublic {
	link: string;
	ref_title: string;
	authors: string;
	pub_year: number;
	id: string;
}
