/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Timverse
 * OpenAPI spec version: 0.1.0
 */
import type { DOIPublic } from './dOIPublic';

export interface DOIsPublic {
  data: DOIPublic[];
  count: number;
}
