/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Timverse
 * OpenAPI spec version: 0.1.0
 */

export type FailureModeType = typeof FailureModeType[keyof typeof FailureModeType];


export const FailureModeType = {
  WOOD: 'WOOD',
  DOWEL: 'DOWEL',
  CONNECTOR: 'CONNECTOR',
  OTHER: 'OTHER',
} as const;
