/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * BarkByte
 * OpenAPI spec version: 0.1.0
 */
import type { FailureMode } from "./failureMode";

export interface FailureModes {
	data: FailureMode[];
	count: number;
}
