/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Timverse
 * OpenAPI spec version: 1.2.0
 */
import type { FailureModeType } from "./failureModeType";

export interface FailureModeCreate {
	/**
	 * @minLength 1
	 * @maxLength 255
	 */
	label: string;
	type: FailureModeType;
}
