/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Timverse
 * OpenAPI spec version: 1.2.0
 */

export interface FastenerType {
	id?: string;
	/**
	 * @minLength 1
	 * @maxLength 255
	 */
	label: string;
}
