/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Timverse
 * OpenAPI spec version: 1.0.0
 */

export interface FastenerTypeCreate {
	/**
	 * @minLength 1
	 * @maxLength 255
	 */
	label: string;
}
