/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * BarkByte
 * OpenAPI spec version: 1.1.0
 */
import type { FastenerType } from "./fastenerType";

export interface FastenerTypes {
	data: FastenerType[];
	count: number;
}
