/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Timverse
 * OpenAPI spec version: 1.0.0
 */
import type { JoineryType } from "./joineryType";

export interface JoineryTypes {
	data: JoineryType[];
	count: number;
}
