/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * BarkByte
 * OpenAPI spec version: 1.1.0
 */

export interface JoineryTypeCreate {
	/**
	 * @minLength 1
	 * @maxLength 255
	 */
	label: string;
	has_dowel: boolean;
}
