/**
 * Generated by orval v8.0.0-rc.2 🍺
 * Do not edit manually.
 * BarkByte
 * OpenAPI spec version: 0.1.0
 */
import type { LoadingDirection } from "./loadingDirection";

export interface LoadingDirections {
	count: number;
	data: LoadingDirection[];
}
