/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Timverse
 * OpenAPI spec version: 1.0.0
 */
import type { LoadingDirection } from "./loadingDirection";

export interface LoadingDirections {
	data: LoadingDirection[];
	count: number;
}
