/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * BarkByte
 * OpenAPI spec version: 0.1.0
 */

export interface NewPassword {
	token: string;
	/**
	 * @minLength 8
	 * @maxLength 64
	 */
	new_password: string;
}
