/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * BarkByte
 * OpenAPI spec version: 0.1.0
 */
import type { PendingSpecimenPublicChangedData } from "./pendingSpecimenPublicChangedData";
import type { PendingStatus } from "./pendingStatus";

export interface PendingSpecimenPublic {
	comment_by_author?: string | null;
	specimen_id?: string | null;
	changed_by_user_id: string;
	changed_data: PendingSpecimenPublicChangedData;
	id: string;
	status: PendingStatus;
	created_at: string;
	reviewer_id?: string | null;
	comment_by_reviewer?: string | null;
	reviewed_at?: string | null;
}
