/**
 * Generated by orval v8.0.0-rc.2 🍺
 * Do not edit manually.
 * BarkByte
 * OpenAPI spec version: 0.1.0
 */
import type { PendingSpecimenPublic } from "./pendingSpecimenPublic";

/**
 * Response model for listing multiple pending specimens.
 */
export interface PendingSpecimensPublic {
	count: number;
	pending_specimens: PendingSpecimenPublic[];
}
