/**
 * Generated by orval v8.0.0-rc.2 🍺
 * Do not edit manually.
 * BarkByte
 * OpenAPI spec version: 0.1.0
 */
import type { PendingSpecimenUpdateAssemblyType } from "./pendingSpecimenUpdateAssemblyType";
import type { PendingSpecimenUpdateConnectionDescription } from "./pendingSpecimenUpdateConnectionDescription";
import type { PendingSpecimenUpdateConnector } from "./pendingSpecimenUpdateConnector";
import type { PendingSpecimenUpdateConnectorMechanicalProperties } from "./pendingSpecimenUpdateConnectorMechanicalProperties";
import type { PendingSpecimenUpdateDowel } from "./pendingSpecimenUpdateDowel";
import type { PendingSpecimenUpdateEDate } from "./pendingSpecimenUpdateEDate";
import type { PendingSpecimenUpdateEDuctility } from "./pendingSpecimenUpdateEDuctility";
import type { PendingSpecimenUpdateElementDimension } from "./pendingSpecimenUpdateElementDimension";
import type { PendingSpecimenUpdateEMaxDisplacement } from "./pendingSpecimenUpdateEMaxDisplacement";
import type { PendingSpecimenUpdateEMaxForce } from "./pendingSpecimenUpdateEMaxForce";
import type { PendingSpecimenUpdateEMeasurementUnit } from "./pendingSpecimenUpdateEMeasurementUnit";
import type { PendingSpecimenUpdateEQfmDescription } from "./pendingSpecimenUpdateEQfmDescription";
import type { PendingSpecimenUpdateEQualitativeFailureMeasure } from "./pendingSpecimenUpdateEQualitativeFailureMeasure";
import type { PendingSpecimenUpdateEStiffness } from "./pendingSpecimenUpdateEStiffness";
import type { PendingSpecimenUpdateETestLoadingType } from "./pendingSpecimenUpdateETestLoadingType";
import type { PendingSpecimenUpdateEUltimateDisplacement } from "./pendingSpecimenUpdateEUltimateDisplacement";
import type { PendingSpecimenUpdateEUltimateForce } from "./pendingSpecimenUpdateEUltimateForce";
import type { PendingSpecimenUpdateEYieldDisplacement } from "./pendingSpecimenUpdateEYieldDisplacement";
import type { PendingSpecimenUpdateEYieldForce } from "./pendingSpecimenUpdateEYieldForce";
import type { PendingSpecimenUpdateEYieldPointMethod } from "./pendingSpecimenUpdateEYieldPointMethod";
import type { PendingSpecimenUpdateFastenerMechanicalProperties } from "./pendingSpecimenUpdateFastenerMechanicalProperties";
import type { PendingSpecimenUpdateFastenerNumbers } from "./pendingSpecimenUpdateFastenerNumbers";
import type { PendingSpecimenUpdateFastenerTypeIds } from "./pendingSpecimenUpdateFastenerTypeIds";
import type { PendingSpecimenUpdateJoineryTypeId } from "./pendingSpecimenUpdateJoineryTypeId";
import type { PendingSpecimenUpdateLoadingDirectionIds } from "./pendingSpecimenUpdateLoadingDirectionIds";
import type { PendingSpecimenUpdateMoisturePercentage } from "./pendingSpecimenUpdateMoisturePercentage";
import type { PendingSpecimenUpdateNote } from "./pendingSpecimenUpdateNote";
import type { PendingSpecimenUpdatePractice } from "./pendingSpecimenUpdatePractice";
import type { PendingSpecimenUpdateReplicateTests } from "./pendingSpecimenUpdateReplicateTests";
import type { PendingSpecimenUpdateSpecimenReferenceId } from "./pendingSpecimenUpdateSpecimenReferenceId";
import type { PendingSpecimenUpdateSubJoineryTypeId } from "./pendingSpecimenUpdateSubJoineryTypeId";
import type { PendingSpecimenUpdateWoodMechanicalProperties } from "./pendingSpecimenUpdateWoodMechanicalProperties";
import type { PendingSpecimenUpdateWoodType } from "./pendingSpecimenUpdateWoodType";

/**
 * Body for updating the pending specimen's changed_data.
 */
export interface PendingSpecimenUpdate {
	assembly_type?: PendingSpecimenUpdateAssemblyType;
	connection_description?: PendingSpecimenUpdateConnectionDescription;
	connector?: PendingSpecimenUpdateConnector;
	connector_mechanical_properties?: PendingSpecimenUpdateConnectorMechanicalProperties;
	dowel?: PendingSpecimenUpdateDowel;
	e_date?: PendingSpecimenUpdateEDate;
	e_ductility?: PendingSpecimenUpdateEDuctility;
	e_max_displacement?: PendingSpecimenUpdateEMaxDisplacement;
	e_max_force?: PendingSpecimenUpdateEMaxForce;
	e_measurement_unit?: PendingSpecimenUpdateEMeasurementUnit;
	e_qfm_description?: PendingSpecimenUpdateEQfmDescription;
	e_qualitative_failure_measure?: PendingSpecimenUpdateEQualitativeFailureMeasure;
	e_stiffness?: PendingSpecimenUpdateEStiffness;
	e_test_loading_type?: PendingSpecimenUpdateETestLoadingType;
	e_ultimate_displacement?: PendingSpecimenUpdateEUltimateDisplacement;
	e_ultimate_force?: PendingSpecimenUpdateEUltimateForce;
	e_yield_displacement?: PendingSpecimenUpdateEYieldDisplacement;
	e_yield_force?: PendingSpecimenUpdateEYieldForce;
	e_yield_point_method?: PendingSpecimenUpdateEYieldPointMethod;
	element_dimension?: PendingSpecimenUpdateElementDimension;
	fastener_mechanical_properties?: PendingSpecimenUpdateFastenerMechanicalProperties;
	fastener_numbers?: PendingSpecimenUpdateFastenerNumbers;
	fastener_type_ids?: PendingSpecimenUpdateFastenerTypeIds;
	joinery_type_id?: PendingSpecimenUpdateJoineryTypeId;
	loading_direction_ids?: PendingSpecimenUpdateLoadingDirectionIds;
	moisture_percentage?: PendingSpecimenUpdateMoisturePercentage;
	note?: PendingSpecimenUpdateNote;
	practice?: PendingSpecimenUpdatePractice;
	replicate_tests?: PendingSpecimenUpdateReplicateTests;
	specimen_reference_id?: PendingSpecimenUpdateSpecimenReferenceId;
	sub_joinery_type_id?: PendingSpecimenUpdateSubJoineryTypeId;
	wood_mechanical_properties?: PendingSpecimenUpdateWoodMechanicalProperties;
	wood_type?: PendingSpecimenUpdateWoodType;
}
