/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Timverse
 * OpenAPI spec version: 1.2.0
 */
import type { AssemblyType } from "./assemblyType";
import type { Practice } from "./practice";
import type { TestLoadingType } from "./testLoadingType";
import type { YieldPointMethod } from "./yieldPointMethod";

/**
 * Body for submitting or editing specimen changes under review.
 */
export interface PendingSpecimenUpdate {
	comment_by_author?: string | null;
	specimen_reference_id?: string | null;
	replicate_tests?: number | null;
	note?: string | null;
	dowel?: boolean | null;
	connector?: boolean | null;
	assembly_type?: AssemblyType | null;
	practice?: Practice | null;
	connection_description?: string | null;
	element_dimension?: string | null;
	fastener_numbers?: number | null;
	moisture_percentage?: string | null;
	wood_type?: string | null;
	wood_mechanical_properties?: string | null;
	connector_mechanical_properties?: string | null;
	fastener_mechanical_properties?: string | null;
	e_date?: string | null;
	e_test_loading_type?: TestLoadingType | null;
	e_yield_point_method?: YieldPointMethod | null;
	e_stiffness?: number | null;
	e_yield_displacement?: number | null;
	e_yield_force?: number | null;
	e_max_displacement?: number | null;
	e_max_force?: number | null;
	e_ultimate_displacement?: number | null;
	e_ultimate_force?: number | null;
	e_ductility?: number | null;
	e_qfm_description?: string | null;
	e_qualitative_failure_measure?: string[] | null;
	fastener_type_ids?: string[] | null;
	loading_direction_ids?: string[] | null;
	joinery_type_id?: string | null;
	sub_joinery_type_id?: string | null;
}
