/**
 * Generated by orval v8.0.0-rc.2 🍺
 * Do not edit manually.
 * BarkByte
 * OpenAPI spec version: 0.1.0
 */
import type { PendingSpecimenPublicChangedData } from "./pendingSpecimenPublicChangedData";
import type { PendingSpecimenPublicCommentByReviewer } from "./pendingSpecimenPublicCommentByReviewer";
import type { PendingSpecimenPublicReviewedAt } from "./pendingSpecimenPublicReviewedAt";
import type { PendingSpecimenPublicReviewerId } from "./pendingSpecimenPublicReviewerId";
import type { PendingSpecimenPublicSpecimenId } from "./pendingSpecimenPublicSpecimenId";
import type { PendingStatus } from "./pendingStatus";

export interface PendingSpecimenPublic {
	changed_by_user_id: string;
	changed_data: PendingSpecimenPublicChangedData;
	comment_by_reviewer?: PendingSpecimenPublicCommentByReviewer;
	created_at: string;
	id: string;
	reviewed_at?: PendingSpecimenPublicReviewedAt;
	reviewer_id?: PendingSpecimenPublicReviewerId;
	specimen_id?: PendingSpecimenPublicSpecimenId;
	status: PendingStatus;
}
