/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * BarkByte
 * OpenAPI spec version: 1.1.0
 */
import type { PendingStatus } from "./pendingStatus";

export type PendingSpecimensListPendingSpecimensParams = {
	status?: PendingStatus | null;
};
