/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * BarkByte
 * OpenAPI spec version: 0.1.0
 */
import type { PendingSpecimenPublic } from "./pendingSpecimenPublic";

/**
 * Response model for listing multiple pending specimens.
 */
export interface PendingSpecimensPublic {
	pending_specimens: PendingSpecimenPublic[];
	count: number;
}
