/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Timverse
 * OpenAPI spec version: 1.2.0
 */
import type { AssemblyType } from "./assemblyType";
import type { Practice } from "./practice";
import type { TestLoadingType } from "./testLoadingType";
import type { YieldPointMethod } from "./yieldPointMethod";

/**
 * Body for submitting a brand new specimen for review.
 */
export interface PendingSpecimenCreate {
	comment_by_author?: string | null;
	specimen_reference_id: string;
	replicate_tests: number;
	note?: string | null;
	dowel: boolean;
	connector: boolean;
	assembly_type: AssemblyType;
	practice: Practice;
	connection_description?: string | null;
	/** @maxLength 1000 */
	element_dimension: string;
	fastener_numbers: number;
	moisture_percentage?: string | null;
	wood_type?: string | null;
	wood_mechanical_properties?: string | null;
	connector_mechanical_properties?: string | null;
	fastener_mechanical_properties?: string | null;
	e_date?: string | null;
	e_test_loading_type: TestLoadingType;
	e_yield_point_method: YieldPointMethod;
	e_stiffness: number;
	e_yield_displacement: number;
	e_yield_force: number;
	e_max_displacement: number;
	e_max_force: number;
	e_ultimate_displacement: number;
	e_ultimate_force: number;
	e_ductility: number;
	e_qfm_description?: string | null;
	doi_id: string;
	e_qualitative_failure_measure: string[];
	fastener_type_ids: string[];
	loading_direction_ids: string[];
	joinery_type_id: string;
	sub_joinery_type_id: string;
}
