/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Timverse
 * OpenAPI spec version: 1.0.0
 */

export type PendingStatus = (typeof PendingStatus)[keyof typeof PendingStatus];

export const PendingStatus = {
	pending: "pending",
	approved: "approved",
	rejected: "rejected",
} as const;
