/**
 * Generated by orval v8.0.0-rc.2 🍺
 * Do not edit manually.
 * BarkByte
 * OpenAPI spec version: 0.1.0
 */

export type PendingStatus = (typeof PendingStatus)[keyof typeof PendingStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PendingStatus = {
	pending: "pending",
	approved: "approved",
	rejected: "rejected",
} as const;
