/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Timverse
 * OpenAPI spec version: 0.1.0
 */

export type Practice = (typeof Practice)[keyof typeof Practice];

export const Practice = {
	Conventional: "Conventional",
	Research_and_Development: "Research and Development",
} as const;
