/**
 * Generated by orval v8.0.0-rc.2 🍺
 * Do not edit manually.
 * BarkByte
 * OpenAPI spec version: 0.1.0
 */

export type Practice = (typeof Practice)[keyof typeof Practice];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const Practice = {
	Conventional: "Conventional",
	Research_and_Development: "Research and Development",
} as const;
