/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Timverse
 * OpenAPI spec version: 0.1.0
 */

export interface PrivateUserCreate {
	email: string;
	password: string;
	full_name: string;
	is_verified?: boolean;
}
