/**
 * Generated by orval v8.0.0-rc.2 🍺
 * Do not edit manually.
 * BarkByte
 * OpenAPI spec version: 0.1.0
 */

export interface PrivateUserCreate {
	email: string;
	password: string;
	full_name: string;
	is_verified?: boolean;
}
