/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Timverse
 * OpenAPI spec version: 1.2.0
 */
import type { SpecimenPublic } from "./specimenPublic";

export interface SpecimensPublic {
	data: SpecimenPublic[];
	count: number;
}
