/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * BarkByte
 * OpenAPI spec version: 1.1.0
 */

export interface SpecimenFilterOptionsPublic {
	assembly_types: string[];
	practices: string[];
	joinery_types: string[];
	sub_joinery_types: string[];
	loading_types: string[];
	failure_modes: string[];
	uploader: string[];
}
