/**
 * Generated by orval v8.0.0-rc.2 🍺
 * Do not edit manually.
 * BarkByte
 * OpenAPI spec version: 0.1.0
 */
import type { AssemblyType } from "./assemblyType";
import type { Practice } from "./practice";
import type { SpecimenCreateConnectorMechanicalProperties } from "./specimenCreateConnectorMechanicalProperties";
import type { SpecimenCreateEDate } from "./specimenCreateEDate";
import type { SpecimenCreateEDuctility } from "./specimenCreateEDuctility";
import type { SpecimenCreateEMaxDisplacement } from "./specimenCreateEMaxDisplacement";
import type { SpecimenCreateEMaxForce } from "./specimenCreateEMaxForce";
import type { SpecimenCreateEMeasurementUnit } from "./specimenCreateEMeasurementUnit";
import type { SpecimenCreateEQfmDescription } from "./specimenCreateEQfmDescription";
import type { SpecimenCreateEStiffness } from "./specimenCreateEStiffness";
import type { SpecimenCreateETestLoadingType } from "./specimenCreateETestLoadingType";
import type { SpecimenCreateEUltimateDisplacement } from "./specimenCreateEUltimateDisplacement";
import type { SpecimenCreateEUltimateForce } from "./specimenCreateEUltimateForce";
import type { SpecimenCreateEYieldDisplacement } from "./specimenCreateEYieldDisplacement";
import type { SpecimenCreateEYieldForce } from "./specimenCreateEYieldForce";
import type { SpecimenCreateEYieldPointMethod } from "./specimenCreateEYieldPointMethod";
import type { SpecimenCreateFastenerMechanicalProperties } from "./specimenCreateFastenerMechanicalProperties";
import type { SpecimenCreateNote } from "./specimenCreateNote";
import type { SpecimenCreateWoodMechanicalProperties } from "./specimenCreateWoodMechanicalProperties";
import type { SpecimenCreateWoodType } from "./specimenCreateWoodType";

export interface SpecimenCreate {
	assembly_type: AssemblyType;
	connection_description: string;
	connector: boolean;
	connector_mechanical_properties?: SpecimenCreateConnectorMechanicalProperties;
	doi_id: string;
	dowel: boolean;
	e_date?: SpecimenCreateEDate;
	e_ductility?: SpecimenCreateEDuctility;
	e_max_displacement?: SpecimenCreateEMaxDisplacement;
	e_max_force?: SpecimenCreateEMaxForce;
	e_measurement_unit?: SpecimenCreateEMeasurementUnit;
	e_qfm_description?: SpecimenCreateEQfmDescription;
	e_qualitative_failure_measure: string[];
	e_stiffness?: SpecimenCreateEStiffness;
	e_test_loading_type?: SpecimenCreateETestLoadingType;
	e_ultimate_displacement?: SpecimenCreateEUltimateDisplacement;
	e_ultimate_force?: SpecimenCreateEUltimateForce;
	e_yield_displacement?: SpecimenCreateEYieldDisplacement;
	e_yield_force?: SpecimenCreateEYieldForce;
	e_yield_point_method?: SpecimenCreateEYieldPointMethod;
	element_dimension: string;
	fastener_mechanical_properties?: SpecimenCreateFastenerMechanicalProperties;
	fastener_numbers: number;
	fastener_type_ids: string[];
	joinery_type_id: string;
	loading_direction_ids: string[];
	moisture_percentage: string;
	note?: SpecimenCreateNote;
	practice: Practice;
	replicate_tests: number;
	specimen_reference_id: string;
	sub_joinery_type_id: string;
	wood_mechanical_properties?: SpecimenCreateWoodMechanicalProperties;
	wood_type?: SpecimenCreateWoodType;
}
