/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Timverse
 * OpenAPI spec version: 0.1.0
 */

export interface SubJoineryType {
	id?: string;
	joinery_type_id: string;
	/**
	 * @minLength 1
	 * @maxLength 255
	 */
	label: string;
}
