/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * BarkByte
 * OpenAPI spec version: 1.1.0
 */
import type { SubJoineryType } from "./subJoineryType";

export interface SubJoineryTypes {
	data: SubJoineryType[];
	count: number;
}
