/**
 * Generated by orval v8.0.0-rc.2 🍺
 * Do not edit manually.
 * BarkByte
 * OpenAPI spec version: 0.1.0
 */

export type TestLoadingType =
	(typeof TestLoadingType)[keyof typeof TestLoadingType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const TestLoadingType = {
	Cyclic: "Cyclic",
	Monotonic: "Monotonic",
	Monotonic_and_Cyclic: "Monotonic and Cyclic",
} as const;
