/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Timverse
 * OpenAPI spec version: 0.1.0
 */

export interface UpdatePassword {
	/**
	 * @minLength 8
	 * @maxLength 64
	 */
	current_password: string;
	/**
	 * @minLength 8
	 * @maxLength 64
	 */
	new_password: string;
}
