/**
 * Generated by orval v8.0.0-rc.2 🍺
 * Do not edit manually.
 * BarkByte
 * OpenAPI spec version: 0.1.0
 */
import type { UserUpdateMeEmail } from "./userUpdateMeEmail";
import type { UserUpdateMeFullName } from "./userUpdateMeFullName";
import type { UserUpdateMeIsActive } from "./userUpdateMeIsActive";

export interface UserUpdateMe {
	email?: UserUpdateMeEmail;
	full_name?: UserUpdateMeFullName;
	is_active?: UserUpdateMeIsActive;
}
