/**
 * Generated by orval v8.0.0-rc.2 🍺
 * Do not edit manually.
 * BarkByte
 * OpenAPI spec version: 0.1.0
 */
import type { UserPublicFullName } from "./userPublicFullName";

export interface UserPublic {
	email: string;
	full_name?: UserPublicFullName;
	id: string;
	is_active: boolean;
	is_superuser: boolean;
}
