/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Timverse
 * OpenAPI spec version: 1.2.0
 */

export interface UserRegister {
	/** @maxLength 255 */
	email: string;
	/**
	 * @minLength 8
	 * @maxLength 64
	 */
	password: string;
	full_name?: string | null;
}
