/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * BarkByte
 * OpenAPI spec version: 0.1.0
 */
import type { UserPublic } from "./userPublic";

export interface UsersPublic {
	data: UserPublic[];
	count: number;
}
