/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Timverse
 * OpenAPI spec version: 1.0.0
 */

export interface UserUpdate {
	is_active?: boolean | null;
	is_superuser?: boolean | null;
	full_name?: string | null;
	email?: string | null;
}
