/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Timverse
 * OpenAPI spec version: 1.2.0
 */

export interface UserUpdateMe {
	is_active?: boolean | null;
	full_name?: string | null;
	email?: string | null;
}
