/**
 * Generated by orval v8.0.0-rc.2 🍺
 * Do not edit manually.
 * BarkByte
 * OpenAPI spec version: 0.1.0
 */
import type { UserUpdateEmail } from "./userUpdateEmail";
import type { UserUpdateFullName } from "./userUpdateFullName";
import type { UserUpdateIsActive } from "./userUpdateIsActive";
import type { UserUpdateIsSuperuser } from "./userUpdateIsSuperuser";

export interface UserUpdate {
	email?: UserUpdateEmail;
	full_name?: UserUpdateFullName;
	is_active?: UserUpdateIsActive;
	is_superuser?: UserUpdateIsSuperuser;
}
