/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Timverse
 * OpenAPI spec version: 1.2.0
 */

export interface UserCreate {
	email: string;
	is_active: boolean;
	is_superuser: boolean;
	full_name?: string | null;
	/**
	 * @minLength 8
	 * @maxLength 64
	 */
	password: string;
}
