/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * BarkByte
 * OpenAPI spec version: 1.1.0
 */

export interface UserPublic {
	email: string;
	is_active: boolean;
	is_superuser: boolean;
	full_name?: string | null;
	id: string;
}
