/**
 * Generated by orval v8.0.0-rc.2 🍺
 * Do not edit manually.
 * BarkByte
 * OpenAPI spec version: 0.1.0
 */
import type { UserUpdateEmail } from "./userUpdateEmail";
import type { UserUpdateFullName } from "./userUpdateFullName";
import type { UserUpdatePassword } from "./userUpdatePassword";

export interface UserUpdate {
	email?: UserUpdateEmail;
	is_active?: boolean;
	is_superuser?: boolean;
	full_name?: UserUpdateFullName;
	password?: UserUpdatePassword;
}
