/**
 * Generated by orval v8.0.0-rc.2 🍺
 * Do not edit manually.
 * BarkByte
 * OpenAPI spec version: 0.1.0
 */
import type { UserRegisterFullName } from "./userRegisterFullName";

export interface UserRegister {
	/** @maxLength 255 */
	email: string;
	/**
	 * @minLength 8
	 * @maxLength 64
	 */
	password: string;
	full_name?: UserRegisterFullName;
}
