/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Timverse
 * OpenAPI spec version: 1.0.0
 */
import type { UserPublic } from "./userPublic";

export interface UsersPublic {
	data: UserPublic[];
	count: number;
}
