/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * BarkByte
 * OpenAPI spec version: 1.1.0
 */

export interface ValidationError {
	loc: (string | number)[];
	msg: string;
	type: string;
}
