/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * BarkByte
 * OpenAPI spec version: 1.1.0
 */

export type YieldPointMethod =
	(typeof YieldPointMethod)[keyof typeof YieldPointMethod];

export const YieldPointMethod = {
	"CEN_1/6": "CEN 1/6",
	EEEP: "EEEP",
} as const;
