/**
 * Generated by orval v8.0.0-rc.2 🍺
 * Do not edit manually.
 * BarkByte
 * OpenAPI spec version: 0.1.0
 */

export type YieldPointMethod =
	(typeof YieldPointMethod)[keyof typeof YieldPointMethod];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const YieldPointMethod = {
	"CEN_1/6": "CEN 1/6",
	EEEP: "EEEP",
	FEMA_P795: "FEMA P795",
} as const;
