/**
 * Generated by orval v8.0.0-rc.2 🍺
 * Do not edit manually.
 * BarkByte
 * OpenAPI spec version: 0.1.0
 */
import * as zod from "zod";

/**
 * List pending specimens, optionally filtered by status.
If no status is provided, all pending specimens are returned.
 * @summary List Pending Specimens
 */
export const pendingSpecimensListPendingSpecimensQueryParams = zod.object({
	status: zod
		.union([zod.enum(["pending", "approved", "rejected"]), zod.null()])
		.optional(),
});

export const pendingSpecimensListPendingSpecimensResponse = zod
	.object({
		count: zod.number(),
		pending_specimens: zod.array(
			zod.object({
				changed_by_user_id: zod.uuid(),
				changed_data: zod.record(zod.string(), zod.unknown()),
				comment_by_reviewer: zod.union([zod.string(), zod.null()]).optional(),
				created_at: zod.iso.datetime({}),
				id: zod.uuid(),
				reviewed_at: zod.union([zod.iso.datetime({}), zod.null()]).optional(),
				reviewer_id: zod.union([zod.uuid(), zod.null()]).optional(),
				specimen_id: zod.union([zod.uuid(), zod.null()]).optional(),
				status: zod.enum(["pending", "approved", "rejected"]),
			}),
		),
	})
	.describe("Response model for listing multiple pending specimens.");

/**
 * List all pending specimens.
 * @summary List Approved Specimen Trail
 */
export const pendingSpecimensListApprovedSpecimenTrailParams = zod.object({
	specimen_id: zod.uuid(),
});

export const pendingSpecimensListApprovedSpecimenTrailResponse = zod
	.object({
		count: zod.number(),
		pending_specimens: zod.array(
			zod.object({
				changed_by_user_id: zod.uuid(),
				changed_data: zod.record(zod.string(), zod.unknown()),
				comment_by_reviewer: zod.union([zod.string(), zod.null()]).optional(),
				created_at: zod.iso.datetime({}),
				id: zod.uuid(),
				reviewed_at: zod.union([zod.iso.datetime({}), zod.null()]).optional(),
				reviewer_id: zod.union([zod.uuid(), zod.null()]).optional(),
				specimen_id: zod.union([zod.uuid(), zod.null()]).optional(),
				status: zod.enum(["pending", "approved", "rejected"]),
			}),
		),
	})
	.describe("Response model for listing multiple pending specimens.");

/**
 * Delete a pending specimen (only allowed while status is PENDING).
 * @summary Delete Pending Specimen
 */
export const pendingSpecimensDeletePendingSpecimenParams = zod.object({
	pending_id: zod.uuid(),
});

export const pendingSpecimensDeletePendingSpecimenResponse = zod.object({
	changed_by_user_id: zod.uuid(),
	changed_data: zod.record(zod.string(), zod.unknown()),
	comment_by_reviewer: zod.union([zod.string(), zod.null()]).optional(),
	created_at: zod.iso.datetime({}),
	id: zod.uuid(),
	reviewed_at: zod.union([zod.iso.datetime({}), zod.null()]).optional(),
	reviewer_id: zod.union([zod.uuid(), zod.null()]).optional(),
	specimen_id: zod.union([zod.uuid(), zod.null()]).optional(),
	status: zod.enum(["pending", "approved", "rejected"]),
});

/**
 * Update the changed_data of an existing pending specimen
before it is approved/rejected.
 * @summary Update Pending Specimen
 */
export const pendingSpecimensUpdatePendingSpecimenParams = zod.object({
	pending_id: zod.uuid(),
});

export const pendingSpecimensUpdatePendingSpecimenBody = zod
	.object({
		assembly_type: zod
			.union([
				zod.enum(["Wall-Floor", "Wall-Wall", "Wall-Floor & Wall-Wall"]),
				zod.null(),
			])
			.optional(),
		connection_description: zod.union([zod.string(), zod.null()]).optional(),
		connector: zod.union([zod.boolean(), zod.null()]).optional(),
		connector_mechanical_properties: zod
			.union([zod.string(), zod.null()])
			.optional(),
		dowel: zod.union([zod.boolean(), zod.null()]).optional(),
		e_date: zod.union([zod.string(), zod.null()]).optional(),
		e_ductility: zod.union([zod.number(), zod.null()]).optional(),
		e_max_displacement: zod.union([zod.number(), zod.null()]).optional(),
		e_max_force: zod.union([zod.number(), zod.null()]).optional(),
		e_measurement_unit: zod.union([zod.string(), zod.null()]).optional(),
		e_qfm_description: zod.union([zod.string(), zod.null()]).optional(),
		e_qualitative_failure_measure: zod
			.union([zod.array(zod.uuid()), zod.null()])
			.optional(),
		e_stiffness: zod.union([zod.number(), zod.null()]).optional(),
		e_test_loading_type: zod
			.union([
				zod.enum(["Cyclic", "Monotonic", "Monotonic and Cyclic"]),
				zod.null(),
			])
			.optional(),
		e_ultimate_displacement: zod.union([zod.number(), zod.null()]).optional(),
		e_ultimate_force: zod.union([zod.number(), zod.null()]).optional(),
		e_yield_displacement: zod.union([zod.number(), zod.null()]).optional(),
		e_yield_force: zod.union([zod.number(), zod.null()]).optional(),
		e_yield_point_method: zod
			.union([zod.enum(["CEN 1/6", "EEEP", "FEMA P795"]), zod.null()])
			.optional(),
		element_dimension: zod.union([zod.string(), zod.null()]).optional(),
		fastener_mechanical_properties: zod
			.union([zod.string(), zod.null()])
			.optional(),
		fastener_numbers: zod.union([zod.number(), zod.null()]).optional(),
		fastener_type_ids: zod
			.union([zod.array(zod.uuid()), zod.null()])
			.optional(),
		joinery_type_id: zod.union([zod.uuid(), zod.null()]).optional(),
		loading_direction_ids: zod
			.union([zod.array(zod.uuid()), zod.null()])
			.optional(),
		moisture_percentage: zod.union([zod.string(), zod.null()]).optional(),
		note: zod.union([zod.string(), zod.null()]).optional(),
		practice: zod
			.union([
				zod.enum(["Conventional", "Research and Development"]),
				zod.null(),
			])
			.optional(),
		replicate_tests: zod.union([zod.number(), zod.null()]).optional(),
		specimen_reference_id: zod.union([zod.string(), zod.null()]).optional(),
		sub_joinery_type_id: zod.union([zod.uuid(), zod.null()]).optional(),
		wood_mechanical_properties: zod
			.union([zod.string(), zod.null()])
			.optional(),
		wood_type: zod.union([zod.string(), zod.null()]).optional(),
	})
	.describe("Body for updating the pending specimen's changed_data.");

export const pendingSpecimensUpdatePendingSpecimenResponse = zod.object({
	changed_by_user_id: zod.uuid(),
	changed_data: zod.record(zod.string(), zod.unknown()),
	comment_by_reviewer: zod.union([zod.string(), zod.null()]).optional(),
	created_at: zod.iso.datetime({}),
	id: zod.uuid(),
	reviewed_at: zod.union([zod.iso.datetime({}), zod.null()]).optional(),
	reviewer_id: zod.union([zod.uuid(), zod.null()]).optional(),
	specimen_id: zod.union([zod.uuid(), zod.null()]).optional(),
	status: zod.enum(["pending", "approved", "rejected"]),
});

/**
 * Approve a pending specimen and apply it to the specimen table.
 * @summary Approve Pending Specimen
 */
export const pendingSpecimensApprovePendingSpecimenParams = zod.object({
	pending_id: zod.uuid(),
});

export const pendingSpecimensApprovePendingSpecimenBody = zod
	.object({
		comment: zod.string(),
	})
	.describe("Body for approve or reject actions.");

export const pendingSpecimensApprovePendingSpecimenResponse = zod.object({
	changed_by_user_id: zod.uuid(),
	changed_data: zod.record(zod.string(), zod.unknown()),
	comment_by_reviewer: zod.union([zod.string(), zod.null()]).optional(),
	created_at: zod.iso.datetime({}),
	id: zod.uuid(),
	reviewed_at: zod.union([zod.iso.datetime({}), zod.null()]).optional(),
	reviewer_id: zod.union([zod.uuid(), zod.null()]).optional(),
	specimen_id: zod.union([zod.uuid(), zod.null()]).optional(),
	status: zod.enum(["pending", "approved", "rejected"]),
});

/**
 * Reject a pending specimen without touching the specimen table.
 * @summary Reject Pending Specimen Route
 */
export const pendingSpecimensRejectPendingSpecimenRouteParams = zod.object({
	pending_id: zod.uuid(),
});

export const pendingSpecimensRejectPendingSpecimenRouteBody = zod
	.object({
		comment: zod.string(),
	})
	.describe("Body for approve or reject actions.");

export const pendingSpecimensRejectPendingSpecimenRouteResponse = zod.object({
	changed_by_user_id: zod.uuid(),
	changed_data: zod.record(zod.string(), zod.unknown()),
	comment_by_reviewer: zod.union([zod.string(), zod.null()]).optional(),
	created_at: zod.iso.datetime({}),
	id: zod.uuid(),
	reviewed_at: zod.union([zod.iso.datetime({}), zod.null()]).optional(),
	reviewer_id: zod.union([zod.uuid(), zod.null()]).optional(),
	specimen_id: zod.union([zod.uuid(), zod.null()]).optional(),
	status: zod.enum(["pending", "approved", "rejected"]),
});
