/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Timverse
 * OpenAPI spec version: 1.2.0
 */

import type {
	DataTag,
	DefinedInitialDataOptions,
	DefinedUseQueryResult,
	MutationFunction,
	QueryClient,
	QueryFunction,
	QueryKey,
	UndefinedInitialDataOptions,
	UseMutationOptions,
	UseMutationResult,
	UseQueryOptions,
	UseQueryResult,
} from "@tanstack/react-query";
import { useMutation, useQuery } from "@tanstack/react-query";

import type {
	HTTPValidationError,
	PendingSpecimenPublic,
	PendingSpecimenReview,
	PendingSpecimensListPendingSpecimensParams,
	PendingSpecimensPublic,
	PendingSpecimenUpdate,
} from "../../model";
import type { ErrorType } from "../../mutator/custom-instance";
import { customInstance } from "../../mutator/custom-instance";

/**
 * Approve a pending specimen and apply it to the specimen table.
 * @summary Approve Pending Specimen
 */
export const pendingSpecimensApprovePendingSpecimen = (
	pendingId: string,
	pendingSpecimenReview: PendingSpecimenReview,
	signal?: AbortSignal,
) => {
	return customInstance<PendingSpecimenPublic>({
		url: `/api/v1/pending-specimens/${pendingId}/approve`,
		method: "POST",
		headers: { "Content-Type": "application/json" },
		data: pendingSpecimenReview,
		signal,
	});
};

export const getPendingSpecimensApprovePendingSpecimenMutationOptions = <
	TError = ErrorType<HTTPValidationError>,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof pendingSpecimensApprovePendingSpecimen>>,
		TError,
		{ pendingId: string; data: PendingSpecimenReview },
		TContext
	>;
}): UseMutationOptions<
	Awaited<ReturnType<typeof pendingSpecimensApprovePendingSpecimen>>,
	TError,
	{ pendingId: string; data: PendingSpecimenReview },
	TContext
> => {
	const mutationKey = ["pendingSpecimensApprovePendingSpecimen"];
	const { mutation: mutationOptions } = options
		? options.mutation &&
			"mutationKey" in options.mutation &&
			options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey } };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof pendingSpecimensApprovePendingSpecimen>>,
		{ pendingId: string; data: PendingSpecimenReview }
	> = (props) => {
		const { pendingId, data } = props ?? {};

		return pendingSpecimensApprovePendingSpecimen(pendingId, data);
	};

	return { mutationFn, ...mutationOptions };
};

export type PendingSpecimensApprovePendingSpecimenMutationResult = NonNullable<
	Awaited<ReturnType<typeof pendingSpecimensApprovePendingSpecimen>>
>;
export type PendingSpecimensApprovePendingSpecimenMutationBody =
	PendingSpecimenReview;
export type PendingSpecimensApprovePendingSpecimenMutationError =
	ErrorType<HTTPValidationError>;

/**
 * @summary Approve Pending Specimen
 */
export const usePendingSpecimensApprovePendingSpecimen = <
	TError = ErrorType<HTTPValidationError>,
	TContext = unknown,
>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof pendingSpecimensApprovePendingSpecimen>>,
			TError,
			{ pendingId: string; data: PendingSpecimenReview },
			TContext
		>;
	},
	queryClient?: QueryClient,
): UseMutationResult<
	Awaited<ReturnType<typeof pendingSpecimensApprovePendingSpecimen>>,
	TError,
	{ pendingId: string; data: PendingSpecimenReview },
	TContext
> => {
	return useMutation(
		getPendingSpecimensApprovePendingSpecimenMutationOptions(options),
		queryClient,
	);
};
/**
 * Reject a pending specimen without touching the specimen table.
 * @summary Reject Pending Specimen Route
 */
export const pendingSpecimensRejectPendingSpecimenRoute = (
	pendingId: string,
	pendingSpecimenReview: PendingSpecimenReview,
	signal?: AbortSignal,
) => {
	return customInstance<PendingSpecimenPublic>({
		url: `/api/v1/pending-specimens/${pendingId}/reject`,
		method: "POST",
		headers: { "Content-Type": "application/json" },
		data: pendingSpecimenReview,
		signal,
	});
};

export const getPendingSpecimensRejectPendingSpecimenRouteMutationOptions = <
	TError = ErrorType<HTTPValidationError>,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof pendingSpecimensRejectPendingSpecimenRoute>>,
		TError,
		{ pendingId: string; data: PendingSpecimenReview },
		TContext
	>;
}): UseMutationOptions<
	Awaited<ReturnType<typeof pendingSpecimensRejectPendingSpecimenRoute>>,
	TError,
	{ pendingId: string; data: PendingSpecimenReview },
	TContext
> => {
	const mutationKey = ["pendingSpecimensRejectPendingSpecimenRoute"];
	const { mutation: mutationOptions } = options
		? options.mutation &&
			"mutationKey" in options.mutation &&
			options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey } };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof pendingSpecimensRejectPendingSpecimenRoute>>,
		{ pendingId: string; data: PendingSpecimenReview }
	> = (props) => {
		const { pendingId, data } = props ?? {};

		return pendingSpecimensRejectPendingSpecimenRoute(pendingId, data);
	};

	return { mutationFn, ...mutationOptions };
};

export type PendingSpecimensRejectPendingSpecimenRouteMutationResult =
	NonNullable<
		Awaited<ReturnType<typeof pendingSpecimensRejectPendingSpecimenRoute>>
	>;
export type PendingSpecimensRejectPendingSpecimenRouteMutationBody =
	PendingSpecimenReview;
export type PendingSpecimensRejectPendingSpecimenRouteMutationError =
	ErrorType<HTTPValidationError>;

/**
 * @summary Reject Pending Specimen Route
 */
export const usePendingSpecimensRejectPendingSpecimenRoute = <
	TError = ErrorType<HTTPValidationError>,
	TContext = unknown,
>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof pendingSpecimensRejectPendingSpecimenRoute>>,
			TError,
			{ pendingId: string; data: PendingSpecimenReview },
			TContext
		>;
	},
	queryClient?: QueryClient,
): UseMutationResult<
	Awaited<ReturnType<typeof pendingSpecimensRejectPendingSpecimenRoute>>,
	TError,
	{ pendingId: string; data: PendingSpecimenReview },
	TContext
> => {
	return useMutation(
		getPendingSpecimensRejectPendingSpecimenRouteMutationOptions(options),
		queryClient,
	);
};
/**
 * Update the changed_data of an existing pending specimen
before it is approved/rejected.
 * @summary Update Pending Specimen
 */
export const pendingSpecimensUpdatePendingSpecimen = (
	pendingId: string,
	pendingSpecimenUpdate: PendingSpecimenUpdate,
	signal?: AbortSignal,
) => {
	return customInstance<PendingSpecimenPublic>({
		url: `/api/v1/pending-specimens/${pendingId}`,
		method: "PUT",
		headers: { "Content-Type": "application/json" },
		data: pendingSpecimenUpdate,
		signal,
	});
};

export const getPendingSpecimensUpdatePendingSpecimenMutationOptions = <
	TError = ErrorType<HTTPValidationError>,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof pendingSpecimensUpdatePendingSpecimen>>,
		TError,
		{ pendingId: string; data: PendingSpecimenUpdate },
		TContext
	>;
}): UseMutationOptions<
	Awaited<ReturnType<typeof pendingSpecimensUpdatePendingSpecimen>>,
	TError,
	{ pendingId: string; data: PendingSpecimenUpdate },
	TContext
> => {
	const mutationKey = ["pendingSpecimensUpdatePendingSpecimen"];
	const { mutation: mutationOptions } = options
		? options.mutation &&
			"mutationKey" in options.mutation &&
			options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey } };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof pendingSpecimensUpdatePendingSpecimen>>,
		{ pendingId: string; data: PendingSpecimenUpdate }
	> = (props) => {
		const { pendingId, data } = props ?? {};

		return pendingSpecimensUpdatePendingSpecimen(pendingId, data);
	};

	return { mutationFn, ...mutationOptions };
};

export type PendingSpecimensUpdatePendingSpecimenMutationResult = NonNullable<
	Awaited<ReturnType<typeof pendingSpecimensUpdatePendingSpecimen>>
>;
export type PendingSpecimensUpdatePendingSpecimenMutationBody =
	PendingSpecimenUpdate;
export type PendingSpecimensUpdatePendingSpecimenMutationError =
	ErrorType<HTTPValidationError>;

/**
 * @summary Update Pending Specimen
 */
export const usePendingSpecimensUpdatePendingSpecimen = <
	TError = ErrorType<HTTPValidationError>,
	TContext = unknown,
>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof pendingSpecimensUpdatePendingSpecimen>>,
			TError,
			{ pendingId: string; data: PendingSpecimenUpdate },
			TContext
		>;
	},
	queryClient?: QueryClient,
): UseMutationResult<
	Awaited<ReturnType<typeof pendingSpecimensUpdatePendingSpecimen>>,
	TError,
	{ pendingId: string; data: PendingSpecimenUpdate },
	TContext
> => {
	return useMutation(
		getPendingSpecimensUpdatePendingSpecimenMutationOptions(options),
		queryClient,
	);
};
/**
 * Delete a pending specimen (only allowed while status is PENDING).
 * @summary Delete Pending Specimen
 */
export const pendingSpecimensDeletePendingSpecimen = (
	pendingId: string,
	signal?: AbortSignal,
) => {
	return customInstance<PendingSpecimenPublic>({
		url: `/api/v1/pending-specimens/${pendingId}`,
		method: "DELETE",
		signal,
	});
};

export const getPendingSpecimensDeletePendingSpecimenMutationOptions = <
	TError = ErrorType<HTTPValidationError>,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof pendingSpecimensDeletePendingSpecimen>>,
		TError,
		{ pendingId: string },
		TContext
	>;
}): UseMutationOptions<
	Awaited<ReturnType<typeof pendingSpecimensDeletePendingSpecimen>>,
	TError,
	{ pendingId: string },
	TContext
> => {
	const mutationKey = ["pendingSpecimensDeletePendingSpecimen"];
	const { mutation: mutationOptions } = options
		? options.mutation &&
			"mutationKey" in options.mutation &&
			options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey } };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof pendingSpecimensDeletePendingSpecimen>>,
		{ pendingId: string }
	> = (props) => {
		const { pendingId } = props ?? {};

		return pendingSpecimensDeletePendingSpecimen(pendingId);
	};

	return { mutationFn, ...mutationOptions };
};

export type PendingSpecimensDeletePendingSpecimenMutationResult = NonNullable<
	Awaited<ReturnType<typeof pendingSpecimensDeletePendingSpecimen>>
>;

export type PendingSpecimensDeletePendingSpecimenMutationError =
	ErrorType<HTTPValidationError>;

/**
 * @summary Delete Pending Specimen
 */
export const usePendingSpecimensDeletePendingSpecimen = <
	TError = ErrorType<HTTPValidationError>,
	TContext = unknown,
>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof pendingSpecimensDeletePendingSpecimen>>,
			TError,
			{ pendingId: string },
			TContext
		>;
	},
	queryClient?: QueryClient,
): UseMutationResult<
	Awaited<ReturnType<typeof pendingSpecimensDeletePendingSpecimen>>,
	TError,
	{ pendingId: string },
	TContext
> => {
	return useMutation(
		getPendingSpecimensDeletePendingSpecimenMutationOptions(options),
		queryClient,
	);
};
/**
 * List pending specimens, optionally filtered by status.
If no status is provided, all pending specimens are returned.
 * @summary List Pending Specimens
 */
export const pendingSpecimensListPendingSpecimens = (
	params?: PendingSpecimensListPendingSpecimensParams,
	signal?: AbortSignal,
) => {
	return customInstance<PendingSpecimensPublic>({
		url: `/api/v1/pending-specimens/`,
		method: "GET",
		params,
		signal,
	});
};

export const getPendingSpecimensListPendingSpecimensQueryKey = (
	params?: PendingSpecimensListPendingSpecimensParams,
) => {
	return [`/api/v1/pending-specimens/`, ...(params ? [params] : [])] as const;
};

export const getPendingSpecimensListPendingSpecimensQueryOptions = <
	TData = Awaited<ReturnType<typeof pendingSpecimensListPendingSpecimens>>,
	TError = ErrorType<HTTPValidationError>,
>(
	params?: PendingSpecimensListPendingSpecimensParams,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof pendingSpecimensListPendingSpecimens>>,
				TError,
				TData
			>
		>;
	},
) => {
	const { query: queryOptions } = options ?? {};

	const queryKey =
		queryOptions?.queryKey ??
		getPendingSpecimensListPendingSpecimensQueryKey(params);

	const queryFn: QueryFunction<
		Awaited<ReturnType<typeof pendingSpecimensListPendingSpecimens>>
	> = ({ signal }) => pendingSpecimensListPendingSpecimens(params, signal);

	return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
		Awaited<ReturnType<typeof pendingSpecimensListPendingSpecimens>>,
		TError,
		TData
	> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type PendingSpecimensListPendingSpecimensQueryResult = NonNullable<
	Awaited<ReturnType<typeof pendingSpecimensListPendingSpecimens>>
>;
export type PendingSpecimensListPendingSpecimensQueryError =
	ErrorType<HTTPValidationError>;

export function usePendingSpecimensListPendingSpecimens<
	TData = Awaited<ReturnType<typeof pendingSpecimensListPendingSpecimens>>,
	TError = ErrorType<HTTPValidationError>,
>(
	params: undefined | PendingSpecimensListPendingSpecimensParams,
	options: {
		query: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof pendingSpecimensListPendingSpecimens>>,
				TError,
				TData
			>
		> &
			Pick<
				DefinedInitialDataOptions<
					Awaited<ReturnType<typeof pendingSpecimensListPendingSpecimens>>,
					TError,
					Awaited<ReturnType<typeof pendingSpecimensListPendingSpecimens>>
				>,
				"initialData"
			>;
	},
	queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function usePendingSpecimensListPendingSpecimens<
	TData = Awaited<ReturnType<typeof pendingSpecimensListPendingSpecimens>>,
	TError = ErrorType<HTTPValidationError>,
>(
	params?: PendingSpecimensListPendingSpecimensParams,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof pendingSpecimensListPendingSpecimens>>,
				TError,
				TData
			>
		> &
			Pick<
				UndefinedInitialDataOptions<
					Awaited<ReturnType<typeof pendingSpecimensListPendingSpecimens>>,
					TError,
					Awaited<ReturnType<typeof pendingSpecimensListPendingSpecimens>>
				>,
				"initialData"
			>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function usePendingSpecimensListPendingSpecimens<
	TData = Awaited<ReturnType<typeof pendingSpecimensListPendingSpecimens>>,
	TError = ErrorType<HTTPValidationError>,
>(
	params?: PendingSpecimensListPendingSpecimensParams,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof pendingSpecimensListPendingSpecimens>>,
				TError,
				TData
			>
		>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary List Pending Specimens
 */

export function usePendingSpecimensListPendingSpecimens<
	TData = Awaited<ReturnType<typeof pendingSpecimensListPendingSpecimens>>,
	TError = ErrorType<HTTPValidationError>,
>(
	params?: PendingSpecimensListPendingSpecimensParams,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof pendingSpecimensListPendingSpecimens>>,
				TError,
				TData
			>
		>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
} {
	const queryOptions = getPendingSpecimensListPendingSpecimensQueryOptions(
		params,
		options,
	);

	const query = useQuery(queryOptions, queryClient) as UseQueryResult<
		TData,
		TError
	> & { queryKey: DataTag<QueryKey, TData, TError> };

	return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * List all pending specimens.
 * @summary List Approved Specimen Trail
 */
export const pendingSpecimensListApprovedSpecimenTrail = (
	specimenId: string,
	signal?: AbortSignal,
) => {
	return customInstance<PendingSpecimensPublic>({
		url: `/api/v1/pending-specimens/specimen/${specimenId}`,
		method: "GET",
		signal,
	});
};

export const getPendingSpecimensListApprovedSpecimenTrailQueryKey = (
	specimenId: string,
) => {
	return [`/api/v1/pending-specimens/specimen/${specimenId}`] as const;
};

export const getPendingSpecimensListApprovedSpecimenTrailQueryOptions = <
	TData = Awaited<ReturnType<typeof pendingSpecimensListApprovedSpecimenTrail>>,
	TError = ErrorType<HTTPValidationError>,
>(
	specimenId: string,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof pendingSpecimensListApprovedSpecimenTrail>>,
				TError,
				TData
			>
		>;
	},
) => {
	const { query: queryOptions } = options ?? {};

	const queryKey =
		queryOptions?.queryKey ??
		getPendingSpecimensListApprovedSpecimenTrailQueryKey(specimenId);

	const queryFn: QueryFunction<
		Awaited<ReturnType<typeof pendingSpecimensListApprovedSpecimenTrail>>
	> = ({ signal }) =>
		pendingSpecimensListApprovedSpecimenTrail(specimenId, signal);

	return {
		queryKey,
		queryFn,
		enabled: !!specimenId,
		...queryOptions,
	} as UseQueryOptions<
		Awaited<ReturnType<typeof pendingSpecimensListApprovedSpecimenTrail>>,
		TError,
		TData
	> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type PendingSpecimensListApprovedSpecimenTrailQueryResult = NonNullable<
	Awaited<ReturnType<typeof pendingSpecimensListApprovedSpecimenTrail>>
>;
export type PendingSpecimensListApprovedSpecimenTrailQueryError =
	ErrorType<HTTPValidationError>;

export function usePendingSpecimensListApprovedSpecimenTrail<
	TData = Awaited<ReturnType<typeof pendingSpecimensListApprovedSpecimenTrail>>,
	TError = ErrorType<HTTPValidationError>,
>(
	specimenId: string,
	options: {
		query: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof pendingSpecimensListApprovedSpecimenTrail>>,
				TError,
				TData
			>
		> &
			Pick<
				DefinedInitialDataOptions<
					Awaited<ReturnType<typeof pendingSpecimensListApprovedSpecimenTrail>>,
					TError,
					Awaited<ReturnType<typeof pendingSpecimensListApprovedSpecimenTrail>>
				>,
				"initialData"
			>;
	},
	queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function usePendingSpecimensListApprovedSpecimenTrail<
	TData = Awaited<ReturnType<typeof pendingSpecimensListApprovedSpecimenTrail>>,
	TError = ErrorType<HTTPValidationError>,
>(
	specimenId: string,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof pendingSpecimensListApprovedSpecimenTrail>>,
				TError,
				TData
			>
		> &
			Pick<
				UndefinedInitialDataOptions<
					Awaited<ReturnType<typeof pendingSpecimensListApprovedSpecimenTrail>>,
					TError,
					Awaited<ReturnType<typeof pendingSpecimensListApprovedSpecimenTrail>>
				>,
				"initialData"
			>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function usePendingSpecimensListApprovedSpecimenTrail<
	TData = Awaited<ReturnType<typeof pendingSpecimensListApprovedSpecimenTrail>>,
	TError = ErrorType<HTTPValidationError>,
>(
	specimenId: string,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof pendingSpecimensListApprovedSpecimenTrail>>,
				TError,
				TData
			>
		>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary List Approved Specimen Trail
 */

export function usePendingSpecimensListApprovedSpecimenTrail<
	TData = Awaited<ReturnType<typeof pendingSpecimensListApprovedSpecimenTrail>>,
	TError = ErrorType<HTTPValidationError>,
>(
	specimenId: string,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof pendingSpecimensListApprovedSpecimenTrail>>,
				TError,
				TData
			>
		>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
} {
	const queryOptions = getPendingSpecimensListApprovedSpecimenTrailQueryOptions(
		specimenId,
		options,
	);

	const query = useQuery(queryOptions, queryClient) as UseQueryResult<
		TData,
		TError
	> & { queryKey: DataTag<QueryKey, TData, TError> };

	return { ...query, queryKey: queryOptions.queryKey };
}
