/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as LayoutTeamRouteImport } from './routes/_layout/team'
import { Route as LayoutSettingsRouteImport } from './routes/_layout/settings'
import { Route as LayoutReferencesRouteImport } from './routes/_layout/references'
import { Route as LayoutDashboardRouteImport } from './routes/_layout/dashboard'
import { Route as LayoutCompareRouteImport } from './routes/_layout/compare'
import { Route as LayoutAuthenticatedRouteImport } from './routes/_layout/_authenticated'
import { Route as AuthSignupRouteImport } from './routes/_auth/signup'
import { Route as AuthSetPasswordRouteImport } from './routes/_auth/set-password'
import { Route as AuthResetPasswordRouteImport } from './routes/_auth/reset-password'
import { Route as AuthRecoverPasswordRouteImport } from './routes/_auth/recover-password'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as LayoutSpecimensIndexRouteImport } from './routes/_layout/specimens/index'
import { Route as LayoutSpecimensSpecimenIdRouteImport } from './routes/_layout/specimens/$specimenId'
import { Route as LayoutAuthenticatedAdminRouteImport } from './routes/_layout/_authenticated/admin'
import { Route as LayoutAuthenticatedSpecimensPendingRouteImport } from './routes/_layout/_authenticated/specimens/pending'
import { Route as LayoutAuthenticatedSpecimensNewRouteImport } from './routes/_layout/_authenticated/specimens/new'

const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutTeamRoute = LayoutTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSettingsRoute = LayoutSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutReferencesRoute = LayoutReferencesRouteImport.update({
  id: '/references',
  path: '/references',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutDashboardRoute = LayoutDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutCompareRoute = LayoutCompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAuthenticatedRoute = LayoutAuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => LayoutRoute,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSetPasswordRoute = AuthSetPasswordRouteImport.update({
  id: '/set-password',
  path: '/set-password',
  getParentRoute: () => AuthRoute,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AuthRoute,
} as any)
const AuthRecoverPasswordRoute = AuthRecoverPasswordRouteImport.update({
  id: '/recover-password',
  path: '/recover-password',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const LayoutSpecimensIndexRoute = LayoutSpecimensIndexRouteImport.update({
  id: '/specimens/',
  path: '/specimens/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSpecimensSpecimenIdRoute =
  LayoutSpecimensSpecimenIdRouteImport.update({
    id: '/specimens/$specimenId',
    path: '/specimens/$specimenId',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutAuthenticatedAdminRoute =
  LayoutAuthenticatedAdminRouteImport.update({
    id: '/admin',
    path: '/admin',
    getParentRoute: () => LayoutAuthenticatedRoute,
  } as any)
const LayoutAuthenticatedSpecimensPendingRoute =
  LayoutAuthenticatedSpecimensPendingRouteImport.update({
    id: '/specimens/pending',
    path: '/specimens/pending',
    getParentRoute: () => LayoutAuthenticatedRoute,
  } as any)
const LayoutAuthenticatedSpecimensNewRoute =
  LayoutAuthenticatedSpecimensNewRouteImport.update({
    id: '/specimens/new',
    path: '/specimens/new',
    getParentRoute: () => LayoutAuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof LayoutIndexRoute
  '/verify-email': typeof VerifyEmailRoute
  '/login': typeof AuthLoginRoute
  '/recover-password': typeof AuthRecoverPasswordRoute
  '/reset-password': typeof AuthResetPasswordRoute
  '/set-password': typeof AuthSetPasswordRoute
  '/signup': typeof AuthSignupRoute
  '/compare': typeof LayoutCompareRoute
  '/dashboard': typeof LayoutDashboardRoute
  '/references': typeof LayoutReferencesRoute
  '/settings': typeof LayoutSettingsRoute
  '/team': typeof LayoutTeamRoute
  '/admin': typeof LayoutAuthenticatedAdminRoute
  '/specimens/$specimenId': typeof LayoutSpecimensSpecimenIdRoute
  '/specimens/': typeof LayoutSpecimensIndexRoute
  '/specimens/new': typeof LayoutAuthenticatedSpecimensNewRoute
  '/specimens/pending': typeof LayoutAuthenticatedSpecimensPendingRoute
}
export interface FileRoutesByTo {
  '/': typeof LayoutIndexRoute
  '/verify-email': typeof VerifyEmailRoute
  '/login': typeof AuthLoginRoute
  '/recover-password': typeof AuthRecoverPasswordRoute
  '/reset-password': typeof AuthResetPasswordRoute
  '/set-password': typeof AuthSetPasswordRoute
  '/signup': typeof AuthSignupRoute
  '/compare': typeof LayoutCompareRoute
  '/dashboard': typeof LayoutDashboardRoute
  '/references': typeof LayoutReferencesRoute
  '/settings': typeof LayoutSettingsRoute
  '/team': typeof LayoutTeamRoute
  '/admin': typeof LayoutAuthenticatedAdminRoute
  '/specimens/$specimenId': typeof LayoutSpecimensSpecimenIdRoute
  '/specimens': typeof LayoutSpecimensIndexRoute
  '/specimens/new': typeof LayoutAuthenticatedSpecimensNewRoute
  '/specimens/pending': typeof LayoutAuthenticatedSpecimensPendingRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteWithChildren
  '/_layout': typeof LayoutRouteWithChildren
  '/verify-email': typeof VerifyEmailRoute
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/recover-password': typeof AuthRecoverPasswordRoute
  '/_auth/reset-password': typeof AuthResetPasswordRoute
  '/_auth/set-password': typeof AuthSetPasswordRoute
  '/_auth/signup': typeof AuthSignupRoute
  '/_layout/_authenticated': typeof LayoutAuthenticatedRouteWithChildren
  '/_layout/compare': typeof LayoutCompareRoute
  '/_layout/dashboard': typeof LayoutDashboardRoute
  '/_layout/references': typeof LayoutReferencesRoute
  '/_layout/settings': typeof LayoutSettingsRoute
  '/_layout/team': typeof LayoutTeamRoute
  '/_layout/': typeof LayoutIndexRoute
  '/_layout/_authenticated/admin': typeof LayoutAuthenticatedAdminRoute
  '/_layout/specimens/$specimenId': typeof LayoutSpecimensSpecimenIdRoute
  '/_layout/specimens/': typeof LayoutSpecimensIndexRoute
  '/_layout/_authenticated/specimens/new': typeof LayoutAuthenticatedSpecimensNewRoute
  '/_layout/_authenticated/specimens/pending': typeof LayoutAuthenticatedSpecimensPendingRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/verify-email'
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/set-password'
    | '/signup'
    | '/compare'
    | '/dashboard'
    | '/references'
    | '/settings'
    | '/team'
    | '/admin'
    | '/specimens/$specimenId'
    | '/specimens/'
    | '/specimens/new'
    | '/specimens/pending'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/verify-email'
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/set-password'
    | '/signup'
    | '/compare'
    | '/dashboard'
    | '/references'
    | '/settings'
    | '/team'
    | '/admin'
    | '/specimens/$specimenId'
    | '/specimens'
    | '/specimens/new'
    | '/specimens/pending'
  id:
    | '__root__'
    | '/_auth'
    | '/_layout'
    | '/verify-email'
    | '/_auth/login'
    | '/_auth/recover-password'
    | '/_auth/reset-password'
    | '/_auth/set-password'
    | '/_auth/signup'
    | '/_layout/_authenticated'
    | '/_layout/compare'
    | '/_layout/dashboard'
    | '/_layout/references'
    | '/_layout/settings'
    | '/_layout/team'
    | '/_layout/'
    | '/_layout/_authenticated/admin'
    | '/_layout/specimens/$specimenId'
    | '/_layout/specimens/'
    | '/_layout/_authenticated/specimens/new'
    | '/_layout/_authenticated/specimens/pending'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRoute: typeof AuthRouteWithChildren
  LayoutRoute: typeof LayoutRouteWithChildren
  VerifyEmailRoute: typeof VerifyEmailRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/team': {
      id: '/_layout/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof LayoutTeamRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/settings': {
      id: '/_layout/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof LayoutSettingsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/references': {
      id: '/_layout/references'
      path: '/references'
      fullPath: '/references'
      preLoaderRoute: typeof LayoutReferencesRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/dashboard': {
      id: '/_layout/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof LayoutDashboardRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/compare': {
      id: '/_layout/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof LayoutCompareRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/_authenticated': {
      id: '/_layout/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutAuthenticatedRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_auth/signup': {
      id: '/_auth/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/set-password': {
      id: '/_auth/set-password'
      path: '/set-password'
      fullPath: '/set-password'
      preLoaderRoute: typeof AuthSetPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/reset-password': {
      id: '/_auth/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/recover-password': {
      id: '/_auth/recover-password'
      path: '/recover-password'
      fullPath: '/recover-password'
      preLoaderRoute: typeof AuthRecoverPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_layout/specimens/': {
      id: '/_layout/specimens/'
      path: '/specimens'
      fullPath: '/specimens/'
      preLoaderRoute: typeof LayoutSpecimensIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/specimens/$specimenId': {
      id: '/_layout/specimens/$specimenId'
      path: '/specimens/$specimenId'
      fullPath: '/specimens/$specimenId'
      preLoaderRoute: typeof LayoutSpecimensSpecimenIdRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/_authenticated/admin': {
      id: '/_layout/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof LayoutAuthenticatedAdminRouteImport
      parentRoute: typeof LayoutAuthenticatedRoute
    }
    '/_layout/_authenticated/specimens/pending': {
      id: '/_layout/_authenticated/specimens/pending'
      path: '/specimens/pending'
      fullPath: '/specimens/pending'
      preLoaderRoute: typeof LayoutAuthenticatedSpecimensPendingRouteImport
      parentRoute: typeof LayoutAuthenticatedRoute
    }
    '/_layout/_authenticated/specimens/new': {
      id: '/_layout/_authenticated/specimens/new'
      path: '/specimens/new'
      fullPath: '/specimens/new'
      preLoaderRoute: typeof LayoutAuthenticatedSpecimensNewRouteImport
      parentRoute: typeof LayoutAuthenticatedRoute
    }
  }
}

interface AuthRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRecoverPasswordRoute: typeof AuthRecoverPasswordRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  AuthSetPasswordRoute: typeof AuthSetPasswordRoute
  AuthSignupRoute: typeof AuthSignupRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
  AuthRecoverPasswordRoute: AuthRecoverPasswordRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  AuthSetPasswordRoute: AuthSetPasswordRoute,
  AuthSignupRoute: AuthSignupRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface LayoutAuthenticatedRouteChildren {
  LayoutAuthenticatedAdminRoute: typeof LayoutAuthenticatedAdminRoute
  LayoutAuthenticatedSpecimensNewRoute: typeof LayoutAuthenticatedSpecimensNewRoute
  LayoutAuthenticatedSpecimensPendingRoute: typeof LayoutAuthenticatedSpecimensPendingRoute
}

const LayoutAuthenticatedRouteChildren: LayoutAuthenticatedRouteChildren = {
  LayoutAuthenticatedAdminRoute: LayoutAuthenticatedAdminRoute,
  LayoutAuthenticatedSpecimensNewRoute: LayoutAuthenticatedSpecimensNewRoute,
  LayoutAuthenticatedSpecimensPendingRoute:
    LayoutAuthenticatedSpecimensPendingRoute,
}

const LayoutAuthenticatedRouteWithChildren =
  LayoutAuthenticatedRoute._addFileChildren(LayoutAuthenticatedRouteChildren)

interface LayoutRouteChildren {
  LayoutAuthenticatedRoute: typeof LayoutAuthenticatedRouteWithChildren
  LayoutCompareRoute: typeof LayoutCompareRoute
  LayoutDashboardRoute: typeof LayoutDashboardRoute
  LayoutReferencesRoute: typeof LayoutReferencesRoute
  LayoutSettingsRoute: typeof LayoutSettingsRoute
  LayoutTeamRoute: typeof LayoutTeamRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
  LayoutSpecimensSpecimenIdRoute: typeof LayoutSpecimensSpecimenIdRoute
  LayoutSpecimensIndexRoute: typeof LayoutSpecimensIndexRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutAuthenticatedRoute: LayoutAuthenticatedRouteWithChildren,
  LayoutCompareRoute: LayoutCompareRoute,
  LayoutDashboardRoute: LayoutDashboardRoute,
  LayoutReferencesRoute: LayoutReferencesRoute,
  LayoutSettingsRoute: LayoutSettingsRoute,
  LayoutTeamRoute: LayoutTeamRoute,
  LayoutIndexRoute: LayoutIndexRoute,
  LayoutSpecimensSpecimenIdRoute: LayoutSpecimensSpecimenIdRoute,
  LayoutSpecimensIndexRoute: LayoutSpecimensIndexRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthRoute: AuthRouteWithChildren,
  LayoutRoute: LayoutRouteWithChildren,
  VerifyEmailRoute: VerifyEmailRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
