/**
 * Generated by orval v8.0.0-rc.2 🍺
 * Do not edit manually.
 * BarkByte
 * OpenAPI spec version: 0.1.0
 */
import * as zod from "zod";

/**
 * Retrieve joinery types.
 * @summary Get Jtypes
 */
export const joinerytypeGetJtypesQuerySkipDefault = 0;
export const joinerytypeGetJtypesQueryLimitDefault = 100;

export const joinerytypeGetJtypesQueryParams = zod.object({
	skip: zod.number().default(joinerytypeGetJtypesQuerySkipDefault),
	limit: zod.number().default(joinerytypeGetJtypesQueryLimitDefault),
});

export const joinerytypeGetJtypesResponseDataItemLabelMax = 255;

export const joinerytypeGetJtypesResponse = zod.object({
	count: zod.number(),
	data: zod.array(
		zod.object({
			has_dowel: zod.boolean(),
			id: zod.uuid().optional(),
			label: zod
				.string()
				.min(1)
				.max(joinerytypeGetJtypesResponseDataItemLabelMax),
		}),
	),
});

/**
 * Create joinery type.
 * @summary Create Jtype
 */
export const joinerytypeCreateJtypeBodyLabelMax = 255;

export const joinerytypeCreateJtypeBody = zod.object({
	has_dowel: zod.boolean(),
	label: zod.string().min(1).max(joinerytypeCreateJtypeBodyLabelMax),
});

export const joinerytypeCreateJtypeResponseLabelMax = 255;

export const joinerytypeCreateJtypeResponse = zod.object({
	has_dowel: zod.boolean(),
	id: zod.uuid().optional(),
	label: zod.string().min(1).max(joinerytypeCreateJtypeResponseLabelMax),
});

/**
 * Delete joinery type ONLY if not in use.
 * @summary Delete Jtype
 */
export const joinerytypeDeleteJtypeParams = zod.object({
	id: zod.uuid(),
});

export const joinerytypeDeleteJtypeResponse = zod.unknown();

/**
 * Update joinery type.
 * @summary Update Jtype
 */
export const joinerytypeUpdateJtypeParams = zod.object({
	id: zod.uuid(),
});

export const joinerytypeUpdateJtypeBodyLabelMax = 255;

export const joinerytypeUpdateJtypeBody = zod.object({
	has_dowel: zod.boolean(),
	label: zod.string().min(1).max(joinerytypeUpdateJtypeBodyLabelMax),
});

export const joinerytypeUpdateJtypeResponseLabelMax = 255;

export const joinerytypeUpdateJtypeResponse = zod.object({
	has_dowel: zod.boolean(),
	id: zod.uuid().optional(),
	label: zod.string().min(1).max(joinerytypeUpdateJtypeResponseLabelMax),
});
