/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Timverse
 * OpenAPI spec version: 1.2.0
 */

import type {
	DataTag,
	DefinedInitialDataOptions,
	DefinedUseQueryResult,
	MutationFunction,
	QueryClient,
	QueryFunction,
	QueryKey,
	UndefinedInitialDataOptions,
	UseMutationOptions,
	UseMutationResult,
	UseQueryOptions,
	UseQueryResult,
} from "@tanstack/react-query";
import { useMutation, useQuery } from "@tanstack/react-query";

import type {
	HTTPValidationError,
	JoineryType,
	JoineryTypeCreate,
	JoineryTypes,
	JoinerytypeGetJtypesParams,
} from "../../model";
import type { ErrorType } from "../../mutator/custom-instance";
import { customInstance } from "../../mutator/custom-instance";

/**
 * Retrieve joinery types.
 * @summary Get Jtypes
 */
export const joinerytypeGetJtypes = (
	params?: JoinerytypeGetJtypesParams,
	signal?: AbortSignal,
) => {
	return customInstance<JoineryTypes>({
		url: `/api/v1/joinerytype/`,
		method: "GET",
		params,
		signal,
	});
};

export const getJoinerytypeGetJtypesQueryKey = (
	params?: JoinerytypeGetJtypesParams,
) => {
	return [`/api/v1/joinerytype/`, ...(params ? [params] : [])] as const;
};

export const getJoinerytypeGetJtypesQueryOptions = <
	TData = Awaited<ReturnType<typeof joinerytypeGetJtypes>>,
	TError = ErrorType<HTTPValidationError>,
>(
	params?: JoinerytypeGetJtypesParams,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof joinerytypeGetJtypes>>,
				TError,
				TData
			>
		>;
	},
) => {
	const { query: queryOptions } = options ?? {};

	const queryKey =
		queryOptions?.queryKey ?? getJoinerytypeGetJtypesQueryKey(params);

	const queryFn: QueryFunction<
		Awaited<ReturnType<typeof joinerytypeGetJtypes>>
	> = ({ signal }) => joinerytypeGetJtypes(params, signal);

	return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
		Awaited<ReturnType<typeof joinerytypeGetJtypes>>,
		TError,
		TData
	> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type JoinerytypeGetJtypesQueryResult = NonNullable<
	Awaited<ReturnType<typeof joinerytypeGetJtypes>>
>;
export type JoinerytypeGetJtypesQueryError = ErrorType<HTTPValidationError>;

export function useJoinerytypeGetJtypes<
	TData = Awaited<ReturnType<typeof joinerytypeGetJtypes>>,
	TError = ErrorType<HTTPValidationError>,
>(
	params: undefined | JoinerytypeGetJtypesParams,
	options: {
		query: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof joinerytypeGetJtypes>>,
				TError,
				TData
			>
		> &
			Pick<
				DefinedInitialDataOptions<
					Awaited<ReturnType<typeof joinerytypeGetJtypes>>,
					TError,
					Awaited<ReturnType<typeof joinerytypeGetJtypes>>
				>,
				"initialData"
			>;
	},
	queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useJoinerytypeGetJtypes<
	TData = Awaited<ReturnType<typeof joinerytypeGetJtypes>>,
	TError = ErrorType<HTTPValidationError>,
>(
	params?: JoinerytypeGetJtypesParams,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof joinerytypeGetJtypes>>,
				TError,
				TData
			>
		> &
			Pick<
				UndefinedInitialDataOptions<
					Awaited<ReturnType<typeof joinerytypeGetJtypes>>,
					TError,
					Awaited<ReturnType<typeof joinerytypeGetJtypes>>
				>,
				"initialData"
			>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useJoinerytypeGetJtypes<
	TData = Awaited<ReturnType<typeof joinerytypeGetJtypes>>,
	TError = ErrorType<HTTPValidationError>,
>(
	params?: JoinerytypeGetJtypesParams,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof joinerytypeGetJtypes>>,
				TError,
				TData
			>
		>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get Jtypes
 */

export function useJoinerytypeGetJtypes<
	TData = Awaited<ReturnType<typeof joinerytypeGetJtypes>>,
	TError = ErrorType<HTTPValidationError>,
>(
	params?: JoinerytypeGetJtypesParams,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof joinerytypeGetJtypes>>,
				TError,
				TData
			>
		>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
} {
	const queryOptions = getJoinerytypeGetJtypesQueryOptions(params, options);

	const query = useQuery(queryOptions, queryClient) as UseQueryResult<
		TData,
		TError
	> & { queryKey: DataTag<QueryKey, TData, TError> };

	return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * Create joinery type.
 * @summary Create Jtype
 */
export const joinerytypeCreateJtype = (
	joineryTypeCreate: JoineryTypeCreate,
	signal?: AbortSignal,
) => {
	return customInstance<JoineryType>({
		url: `/api/v1/joinerytype/`,
		method: "POST",
		headers: { "Content-Type": "application/json" },
		data: joineryTypeCreate,
		signal,
	});
};

export const getJoinerytypeCreateJtypeMutationOptions = <
	TError = ErrorType<HTTPValidationError>,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof joinerytypeCreateJtype>>,
		TError,
		{ data: JoineryTypeCreate },
		TContext
	>;
}): UseMutationOptions<
	Awaited<ReturnType<typeof joinerytypeCreateJtype>>,
	TError,
	{ data: JoineryTypeCreate },
	TContext
> => {
	const mutationKey = ["joinerytypeCreateJtype"];
	const { mutation: mutationOptions } = options
		? options.mutation &&
			"mutationKey" in options.mutation &&
			options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey } };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof joinerytypeCreateJtype>>,
		{ data: JoineryTypeCreate }
	> = (props) => {
		const { data } = props ?? {};

		return joinerytypeCreateJtype(data);
	};

	return { mutationFn, ...mutationOptions };
};

export type JoinerytypeCreateJtypeMutationResult = NonNullable<
	Awaited<ReturnType<typeof joinerytypeCreateJtype>>
>;
export type JoinerytypeCreateJtypeMutationBody = JoineryTypeCreate;
export type JoinerytypeCreateJtypeMutationError =
	ErrorType<HTTPValidationError>;

/**
 * @summary Create Jtype
 */
export const useJoinerytypeCreateJtype = <
	TError = ErrorType<HTTPValidationError>,
	TContext = unknown,
>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof joinerytypeCreateJtype>>,
			TError,
			{ data: JoineryTypeCreate },
			TContext
		>;
	},
	queryClient?: QueryClient,
): UseMutationResult<
	Awaited<ReturnType<typeof joinerytypeCreateJtype>>,
	TError,
	{ data: JoineryTypeCreate },
	TContext
> => {
	return useMutation(
		getJoinerytypeCreateJtypeMutationOptions(options),
		queryClient,
	);
};
/**
 * Update joinery type.
 * @summary Update Jtype
 */
export const joinerytypeUpdateJtype = (
	id: string,
	joineryTypeCreate: JoineryTypeCreate,
	signal?: AbortSignal,
) => {
	return customInstance<JoineryType>({
		url: `/api/v1/joinerytype/${id}`,
		method: "PUT",
		headers: { "Content-Type": "application/json" },
		data: joineryTypeCreate,
		signal,
	});
};

export const getJoinerytypeUpdateJtypeMutationOptions = <
	TError = ErrorType<HTTPValidationError>,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof joinerytypeUpdateJtype>>,
		TError,
		{ id: string; data: JoineryTypeCreate },
		TContext
	>;
}): UseMutationOptions<
	Awaited<ReturnType<typeof joinerytypeUpdateJtype>>,
	TError,
	{ id: string; data: JoineryTypeCreate },
	TContext
> => {
	const mutationKey = ["joinerytypeUpdateJtype"];
	const { mutation: mutationOptions } = options
		? options.mutation &&
			"mutationKey" in options.mutation &&
			options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey } };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof joinerytypeUpdateJtype>>,
		{ id: string; data: JoineryTypeCreate }
	> = (props) => {
		const { id, data } = props ?? {};

		return joinerytypeUpdateJtype(id, data);
	};

	return { mutationFn, ...mutationOptions };
};

export type JoinerytypeUpdateJtypeMutationResult = NonNullable<
	Awaited<ReturnType<typeof joinerytypeUpdateJtype>>
>;
export type JoinerytypeUpdateJtypeMutationBody = JoineryTypeCreate;
export type JoinerytypeUpdateJtypeMutationError =
	ErrorType<HTTPValidationError>;

/**
 * @summary Update Jtype
 */
export const useJoinerytypeUpdateJtype = <
	TError = ErrorType<HTTPValidationError>,
	TContext = unknown,
>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof joinerytypeUpdateJtype>>,
			TError,
			{ id: string; data: JoineryTypeCreate },
			TContext
		>;
	},
	queryClient?: QueryClient,
): UseMutationResult<
	Awaited<ReturnType<typeof joinerytypeUpdateJtype>>,
	TError,
	{ id: string; data: JoineryTypeCreate },
	TContext
> => {
	return useMutation(
		getJoinerytypeUpdateJtypeMutationOptions(options),
		queryClient,
	);
};
/**
 * Delete joinery type ONLY if not in use.
 * @summary Delete Jtype
 */
export const joinerytypeDeleteJtype = (id: string, signal?: AbortSignal) => {
	return customInstance<unknown>({
		url: `/api/v1/joinerytype/${id}`,
		method: "DELETE",
		signal,
	});
};

export const getJoinerytypeDeleteJtypeMutationOptions = <
	TError = ErrorType<HTTPValidationError>,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof joinerytypeDeleteJtype>>,
		TError,
		{ id: string },
		TContext
	>;
}): UseMutationOptions<
	Awaited<ReturnType<typeof joinerytypeDeleteJtype>>,
	TError,
	{ id: string },
	TContext
> => {
	const mutationKey = ["joinerytypeDeleteJtype"];
	const { mutation: mutationOptions } = options
		? options.mutation &&
			"mutationKey" in options.mutation &&
			options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey } };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof joinerytypeDeleteJtype>>,
		{ id: string }
	> = (props) => {
		const { id } = props ?? {};

		return joinerytypeDeleteJtype(id);
	};

	return { mutationFn, ...mutationOptions };
};

export type JoinerytypeDeleteJtypeMutationResult = NonNullable<
	Awaited<ReturnType<typeof joinerytypeDeleteJtype>>
>;

export type JoinerytypeDeleteJtypeMutationError =
	ErrorType<HTTPValidationError>;

/**
 * @summary Delete Jtype
 */
export const useJoinerytypeDeleteJtype = <
	TError = ErrorType<HTTPValidationError>,
	TContext = unknown,
>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof joinerytypeDeleteJtype>>,
			TError,
			{ id: string },
			TContext
		>;
	},
	queryClient?: QueryClient,
): UseMutationResult<
	Awaited<ReturnType<typeof joinerytypeDeleteJtype>>,
	TError,
	{ id: string },
	TContext
> => {
	return useMutation(
		getJoinerytypeDeleteJtypeMutationOptions(options),
		queryClient,
	);
};
