/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * BarkByte
 * OpenAPI spec version: 0.1.0
 */

import type {
	DataTag,
	DefinedInitialDataOptions,
	DefinedUseQueryResult,
	MutationFunction,
	QueryClient,
	QueryFunction,
	QueryKey,
	UndefinedInitialDataOptions,
	UseMutationOptions,
	UseMutationResult,
	UseQueryOptions,
	UseQueryResult,
} from "@tanstack/react-query";
import { useMutation, useQuery } from "@tanstack/react-query";

import type {
	HTTPValidationError,
	PendingSpecimenCreate,
	PendingSpecimenPublic,
	PendingSpecimenUpdate,
	SpecimenFilterOptionsPublic,
	SpecimenPublic,
	SpecimensPublic,
	SpecimensReadSpecimensParams,
} from "../../model";
import type { ErrorType } from "../../mutator/custom-instance";
import { customInstance } from "../../mutator/custom-instance";

/**
 * Retrieve specimens.
 * @summary Read Specimens
 */
export const specimensReadSpecimens = (
	params?: SpecimensReadSpecimensParams,
	signal?: AbortSignal,
) => {
	return customInstance<SpecimensPublic>({
		url: `/api/v1/specimens/`,
		method: "GET",
		params,
		signal,
	});
};

export const getSpecimensReadSpecimensQueryKey = (
	params?: SpecimensReadSpecimensParams,
) => {
	return [`/api/v1/specimens/`, ...(params ? [params] : [])] as const;
};

export const getSpecimensReadSpecimensQueryOptions = <
	TData = Awaited<ReturnType<typeof specimensReadSpecimens>>,
	TError = ErrorType<HTTPValidationError>,
>(
	params?: SpecimensReadSpecimensParams,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof specimensReadSpecimens>>,
				TError,
				TData
			>
		>;
	},
) => {
	const { query: queryOptions } = options ?? {};

	const queryKey =
		queryOptions?.queryKey ?? getSpecimensReadSpecimensQueryKey(params);

	const queryFn: QueryFunction<
		Awaited<ReturnType<typeof specimensReadSpecimens>>
	> = ({ signal }) => specimensReadSpecimens(params, signal);

	return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
		Awaited<ReturnType<typeof specimensReadSpecimens>>,
		TError,
		TData
	> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type SpecimensReadSpecimensQueryResult = NonNullable<
	Awaited<ReturnType<typeof specimensReadSpecimens>>
>;
export type SpecimensReadSpecimensQueryError = ErrorType<HTTPValidationError>;

export function useSpecimensReadSpecimens<
	TData = Awaited<ReturnType<typeof specimensReadSpecimens>>,
	TError = ErrorType<HTTPValidationError>,
>(
	params: undefined | SpecimensReadSpecimensParams,
	options: {
		query: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof specimensReadSpecimens>>,
				TError,
				TData
			>
		> &
			Pick<
				DefinedInitialDataOptions<
					Awaited<ReturnType<typeof specimensReadSpecimens>>,
					TError,
					Awaited<ReturnType<typeof specimensReadSpecimens>>
				>,
				"initialData"
			>;
	},
	queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useSpecimensReadSpecimens<
	TData = Awaited<ReturnType<typeof specimensReadSpecimens>>,
	TError = ErrorType<HTTPValidationError>,
>(
	params?: SpecimensReadSpecimensParams,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof specimensReadSpecimens>>,
				TError,
				TData
			>
		> &
			Pick<
				UndefinedInitialDataOptions<
					Awaited<ReturnType<typeof specimensReadSpecimens>>,
					TError,
					Awaited<ReturnType<typeof specimensReadSpecimens>>
				>,
				"initialData"
			>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useSpecimensReadSpecimens<
	TData = Awaited<ReturnType<typeof specimensReadSpecimens>>,
	TError = ErrorType<HTTPValidationError>,
>(
	params?: SpecimensReadSpecimensParams,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof specimensReadSpecimens>>,
				TError,
				TData
			>
		>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Read Specimens
 */

export function useSpecimensReadSpecimens<
	TData = Awaited<ReturnType<typeof specimensReadSpecimens>>,
	TError = ErrorType<HTTPValidationError>,
>(
	params?: SpecimensReadSpecimensParams,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof specimensReadSpecimens>>,
				TError,
				TData
			>
		>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
} {
	const queryOptions = getSpecimensReadSpecimensQueryOptions(params, options);

	const query = useQuery(queryOptions, queryClient) as UseQueryResult<
		TData,
		TError
	> & { queryKey: DataTag<QueryKey, TData, TError> };

	return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * Submit a new specimen for review.
 * @summary Create Specimen
 */
export const specimensCreateSpecimen = (
	pendingSpecimenCreate: PendingSpecimenCreate,
	signal?: AbortSignal,
) => {
	return customInstance<PendingSpecimenPublic>({
		url: `/api/v1/specimens/`,
		method: "POST",
		headers: { "Content-Type": "application/json" },
		data: pendingSpecimenCreate,
		signal,
	});
};

export const getSpecimensCreateSpecimenMutationOptions = <
	TError = ErrorType<HTTPValidationError>,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof specimensCreateSpecimen>>,
		TError,
		{ data: PendingSpecimenCreate },
		TContext
	>;
}): UseMutationOptions<
	Awaited<ReturnType<typeof specimensCreateSpecimen>>,
	TError,
	{ data: PendingSpecimenCreate },
	TContext
> => {
	const mutationKey = ["specimensCreateSpecimen"];
	const { mutation: mutationOptions } = options
		? options.mutation &&
			"mutationKey" in options.mutation &&
			options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey } };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof specimensCreateSpecimen>>,
		{ data: PendingSpecimenCreate }
	> = (props) => {
		const { data } = props ?? {};

		return specimensCreateSpecimen(data);
	};

	return { mutationFn, ...mutationOptions };
};

export type SpecimensCreateSpecimenMutationResult = NonNullable<
	Awaited<ReturnType<typeof specimensCreateSpecimen>>
>;
export type SpecimensCreateSpecimenMutationBody = PendingSpecimenCreate;
export type SpecimensCreateSpecimenMutationError =
	ErrorType<HTTPValidationError>;

/**
 * @summary Create Specimen
 */
export const useSpecimensCreateSpecimen = <
	TError = ErrorType<HTTPValidationError>,
	TContext = unknown,
>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof specimensCreateSpecimen>>,
			TError,
			{ data: PendingSpecimenCreate },
			TContext
		>;
	},
	queryClient?: QueryClient,
): UseMutationResult<
	Awaited<ReturnType<typeof specimensCreateSpecimen>>,
	TError,
	{ data: PendingSpecimenCreate },
	TContext
> => {
	return useMutation(
		getSpecimensCreateSpecimenMutationOptions(options),
		queryClient,
	);
};
/**
 * Retrieve predefined specimen filter options for facet controls.
 * @summary Read Specimen Filter Options
 */
export const specimensReadSpecimenFilterOptions = (signal?: AbortSignal) => {
	return customInstance<SpecimenFilterOptionsPublic>({
		url: `/api/v1/specimens/filter-options`,
		method: "GET",
		signal,
	});
};

export const getSpecimensReadSpecimenFilterOptionsQueryKey = () => {
	return [`/api/v1/specimens/filter-options`] as const;
};

export const getSpecimensReadSpecimenFilterOptionsQueryOptions = <
	TData = Awaited<ReturnType<typeof specimensReadSpecimenFilterOptions>>,
	TError = ErrorType<unknown>,
>(options?: {
	query?: Partial<
		UseQueryOptions<
			Awaited<ReturnType<typeof specimensReadSpecimenFilterOptions>>,
			TError,
			TData
		>
	>;
}) => {
	const { query: queryOptions } = options ?? {};

	const queryKey =
		queryOptions?.queryKey ?? getSpecimensReadSpecimenFilterOptionsQueryKey();

	const queryFn: QueryFunction<
		Awaited<ReturnType<typeof specimensReadSpecimenFilterOptions>>
	> = ({ signal }) => specimensReadSpecimenFilterOptions(signal);

	return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
		Awaited<ReturnType<typeof specimensReadSpecimenFilterOptions>>,
		TError,
		TData
	> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type SpecimensReadSpecimenFilterOptionsQueryResult = NonNullable<
	Awaited<ReturnType<typeof specimensReadSpecimenFilterOptions>>
>;
export type SpecimensReadSpecimenFilterOptionsQueryError = ErrorType<unknown>;

export function useSpecimensReadSpecimenFilterOptions<
	TData = Awaited<ReturnType<typeof specimensReadSpecimenFilterOptions>>,
	TError = ErrorType<unknown>,
>(
	options: {
		query: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof specimensReadSpecimenFilterOptions>>,
				TError,
				TData
			>
		> &
			Pick<
				DefinedInitialDataOptions<
					Awaited<ReturnType<typeof specimensReadSpecimenFilterOptions>>,
					TError,
					Awaited<ReturnType<typeof specimensReadSpecimenFilterOptions>>
				>,
				"initialData"
			>;
	},
	queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useSpecimensReadSpecimenFilterOptions<
	TData = Awaited<ReturnType<typeof specimensReadSpecimenFilterOptions>>,
	TError = ErrorType<unknown>,
>(
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof specimensReadSpecimenFilterOptions>>,
				TError,
				TData
			>
		> &
			Pick<
				UndefinedInitialDataOptions<
					Awaited<ReturnType<typeof specimensReadSpecimenFilterOptions>>,
					TError,
					Awaited<ReturnType<typeof specimensReadSpecimenFilterOptions>>
				>,
				"initialData"
			>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useSpecimensReadSpecimenFilterOptions<
	TData = Awaited<ReturnType<typeof specimensReadSpecimenFilterOptions>>,
	TError = ErrorType<unknown>,
>(
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof specimensReadSpecimenFilterOptions>>,
				TError,
				TData
			>
		>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Read Specimen Filter Options
 */

export function useSpecimensReadSpecimenFilterOptions<
	TData = Awaited<ReturnType<typeof specimensReadSpecimenFilterOptions>>,
	TError = ErrorType<unknown>,
>(
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof specimensReadSpecimenFilterOptions>>,
				TError,
				TData
			>
		>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
} {
	const queryOptions =
		getSpecimensReadSpecimenFilterOptionsQueryOptions(options);

	const query = useQuery(queryOptions, queryClient) as UseQueryResult<
		TData,
		TError
	> & { queryKey: DataTag<QueryKey, TData, TError> };

	return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * Get specimen by ID.
 * @summary Read Specimen
 */
export const specimensReadSpecimen = (id: string, signal?: AbortSignal) => {
	return customInstance<SpecimenPublic>({
		url: `/api/v1/specimens/${id}`,
		method: "GET",
		signal,
	});
};

export const getSpecimensReadSpecimenQueryKey = (id: string) => {
	return [`/api/v1/specimens/${id}`] as const;
};

export const getSpecimensReadSpecimenQueryOptions = <
	TData = Awaited<ReturnType<typeof specimensReadSpecimen>>,
	TError = ErrorType<HTTPValidationError>,
>(
	id: string,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof specimensReadSpecimen>>,
				TError,
				TData
			>
		>;
	},
) => {
	const { query: queryOptions } = options ?? {};

	const queryKey =
		queryOptions?.queryKey ?? getSpecimensReadSpecimenQueryKey(id);

	const queryFn: QueryFunction<
		Awaited<ReturnType<typeof specimensReadSpecimen>>
	> = ({ signal }) => specimensReadSpecimen(id, signal);

	return {
		queryKey,
		queryFn,
		enabled: !!id,
		...queryOptions,
	} as UseQueryOptions<
		Awaited<ReturnType<typeof specimensReadSpecimen>>,
		TError,
		TData
	> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type SpecimensReadSpecimenQueryResult = NonNullable<
	Awaited<ReturnType<typeof specimensReadSpecimen>>
>;
export type SpecimensReadSpecimenQueryError = ErrorType<HTTPValidationError>;

export function useSpecimensReadSpecimen<
	TData = Awaited<ReturnType<typeof specimensReadSpecimen>>,
	TError = ErrorType<HTTPValidationError>,
>(
	id: string,
	options: {
		query: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof specimensReadSpecimen>>,
				TError,
				TData
			>
		> &
			Pick<
				DefinedInitialDataOptions<
					Awaited<ReturnType<typeof specimensReadSpecimen>>,
					TError,
					Awaited<ReturnType<typeof specimensReadSpecimen>>
				>,
				"initialData"
			>;
	},
	queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useSpecimensReadSpecimen<
	TData = Awaited<ReturnType<typeof specimensReadSpecimen>>,
	TError = ErrorType<HTTPValidationError>,
>(
	id: string,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof specimensReadSpecimen>>,
				TError,
				TData
			>
		> &
			Pick<
				UndefinedInitialDataOptions<
					Awaited<ReturnType<typeof specimensReadSpecimen>>,
					TError,
					Awaited<ReturnType<typeof specimensReadSpecimen>>
				>,
				"initialData"
			>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useSpecimensReadSpecimen<
	TData = Awaited<ReturnType<typeof specimensReadSpecimen>>,
	TError = ErrorType<HTTPValidationError>,
>(
	id: string,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof specimensReadSpecimen>>,
				TError,
				TData
			>
		>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Read Specimen
 */

export function useSpecimensReadSpecimen<
	TData = Awaited<ReturnType<typeof specimensReadSpecimen>>,
	TError = ErrorType<HTTPValidationError>,
>(
	id: string,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof specimensReadSpecimen>>,
				TError,
				TData
			>
		>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
} {
	const queryOptions = getSpecimensReadSpecimenQueryOptions(id, options);

	const query = useQuery(queryOptions, queryClient) as UseQueryResult<
		TData,
		TError
	> & { queryKey: DataTag<QueryKey, TData, TError> };

	return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * Submit an update for an existing specimen.
 * @summary Update Specimen
 */
export const specimensUpdateSpecimen = (
	id: string,
	pendingSpecimenUpdate: PendingSpecimenUpdate,
	signal?: AbortSignal,
) => {
	return customInstance<PendingSpecimenPublic>({
		url: `/api/v1/specimens/${id}`,
		method: "PUT",
		headers: { "Content-Type": "application/json" },
		data: pendingSpecimenUpdate,
		signal,
	});
};

export const getSpecimensUpdateSpecimenMutationOptions = <
	TError = ErrorType<HTTPValidationError>,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof specimensUpdateSpecimen>>,
		TError,
		{ id: string; data: PendingSpecimenUpdate },
		TContext
	>;
}): UseMutationOptions<
	Awaited<ReturnType<typeof specimensUpdateSpecimen>>,
	TError,
	{ id: string; data: PendingSpecimenUpdate },
	TContext
> => {
	const mutationKey = ["specimensUpdateSpecimen"];
	const { mutation: mutationOptions } = options
		? options.mutation &&
			"mutationKey" in options.mutation &&
			options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey } };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof specimensUpdateSpecimen>>,
		{ id: string; data: PendingSpecimenUpdate }
	> = (props) => {
		const { id, data } = props ?? {};

		return specimensUpdateSpecimen(id, data);
	};

	return { mutationFn, ...mutationOptions };
};

export type SpecimensUpdateSpecimenMutationResult = NonNullable<
	Awaited<ReturnType<typeof specimensUpdateSpecimen>>
>;
export type SpecimensUpdateSpecimenMutationBody = PendingSpecimenUpdate;
export type SpecimensUpdateSpecimenMutationError =
	ErrorType<HTTPValidationError>;

/**
 * @summary Update Specimen
 */
export const useSpecimensUpdateSpecimen = <
	TError = ErrorType<HTTPValidationError>,
	TContext = unknown,
>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof specimensUpdateSpecimen>>,
			TError,
			{ id: string; data: PendingSpecimenUpdate },
			TContext
		>;
	},
	queryClient?: QueryClient,
): UseMutationResult<
	Awaited<ReturnType<typeof specimensUpdateSpecimen>>,
	TError,
	{ id: string; data: PendingSpecimenUpdate },
	TContext
> => {
	return useMutation(
		getSpecimensUpdateSpecimenMutationOptions(options),
		queryClient,
	);
};
/**
 * Delete a specimen.
 * @summary Delete Specimen
 */
export const specimensDeleteSpecimen = (id: string, signal?: AbortSignal) => {
	return customInstance<unknown>({
		url: `/api/v1/specimens/${id}`,
		method: "DELETE",
		signal,
	});
};

export const getSpecimensDeleteSpecimenMutationOptions = <
	TError = ErrorType<HTTPValidationError>,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof specimensDeleteSpecimen>>,
		TError,
		{ id: string },
		TContext
	>;
}): UseMutationOptions<
	Awaited<ReturnType<typeof specimensDeleteSpecimen>>,
	TError,
	{ id: string },
	TContext
> => {
	const mutationKey = ["specimensDeleteSpecimen"];
	const { mutation: mutationOptions } = options
		? options.mutation &&
			"mutationKey" in options.mutation &&
			options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey } };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof specimensDeleteSpecimen>>,
		{ id: string }
	> = (props) => {
		const { id } = props ?? {};

		return specimensDeleteSpecimen(id);
	};

	return { mutationFn, ...mutationOptions };
};

export type SpecimensDeleteSpecimenMutationResult = NonNullable<
	Awaited<ReturnType<typeof specimensDeleteSpecimen>>
>;

export type SpecimensDeleteSpecimenMutationError =
	ErrorType<HTTPValidationError>;

/**
 * @summary Delete Specimen
 */
export const useSpecimensDeleteSpecimen = <
	TError = ErrorType<HTTPValidationError>,
	TContext = unknown,
>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof specimensDeleteSpecimen>>,
			TError,
			{ id: string },
			TContext
		>;
	},
	queryClient?: QueryClient,
): UseMutationResult<
	Awaited<ReturnType<typeof specimensDeleteSpecimen>>,
	TError,
	{ id: string },
	TContext
> => {
	return useMutation(
		getSpecimensDeleteSpecimenMutationOptions(options),
		queryClient,
	);
};
