/**
 * Generated by orval v8.0.0-rc.2 🍺
 * Do not edit manually.
 * BarkByte
 * OpenAPI spec version: 0.1.0
 */
import * as zod from "zod";

/**
 * Retrieve specimens.
 * @summary Read Specimens
 */
export const specimensReadSpecimensQuerySkipDefault = 0;
export const specimensReadSpecimensQueryLimitDefault = 100;

export const specimensReadSpecimensQueryParams = zod.object({
	skip: zod.number().default(specimensReadSpecimensQuerySkipDefault),
	limit: zod.number().default(specimensReadSpecimensQueryLimitDefault),
});

export const specimensReadSpecimensResponseDataItemDoiAuthorsMax = 255;

export const specimensReadSpecimensResponseDataItemDoiLinkMax = 255;

export const specimensReadSpecimensResponseDataItemDoiRefTitleMax = 255;

export const specimensReadSpecimensResponseDataItemEQualitativeFailureMeasureItemLabelMax = 255;

export const specimensReadSpecimensResponseDataItemFastenerTypesItemLabelMax = 255;

export const specimensReadSpecimensResponseDataItemJoineryTypeLabelMax = 255;

export const specimensReadSpecimensResponseDataItemLoadingDirectionsItemLabelMax = 255;

export const specimensReadSpecimensResponseDataItemSubJoineryTypeLabelMax = 255;

export const specimensReadSpecimensResponse = zod.object({
	count: zod.number(),
	data: zod.array(
		zod.object({
			assembly_type: zod.enum([
				"Wall-Floor",
				"Wall-Wall",
				"Wall-Floor & Wall-Wall",
			]),
			connection_description: zod.string(),
			connector: zod.boolean(),
			connector_mechanical_properties: zod
				.union([zod.string(), zod.null()])
				.optional(),
			doi: zod.object({
				authors: zod
					.string()
					.min(1)
					.max(specimensReadSpecimensResponseDataItemDoiAuthorsMax),
				id: zod.uuid().optional(),
				link: zod
					.string()
					.min(1)
					.max(specimensReadSpecimensResponseDataItemDoiLinkMax),
				pub_year: zod.number(),
				ref_title: zod
					.string()
					.min(1)
					.max(specimensReadSpecimensResponseDataItemDoiRefTitleMax),
			}),
			dowel: zod.boolean(),
			e_date: zod.union([zod.string(), zod.null()]).optional(),
			e_ductility: zod.union([zod.number(), zod.null()]).optional(),
			e_max_displacement: zod.union([zod.number(), zod.null()]).optional(),
			e_max_force: zod.union([zod.number(), zod.null()]).optional(),
			e_measurement_unit: zod.union([zod.string(), zod.null()]).optional(),
			e_qfm_description: zod.union([zod.string(), zod.null()]).optional(),
			e_qualitative_failure_measure: zod.array(
				zod.object({
					id: zod.uuid().optional(),
					label: zod
						.string()
						.min(1)
						.max(
							specimensReadSpecimensResponseDataItemEQualitativeFailureMeasureItemLabelMax,
						),
					type: zod.enum(["WOOD", "DOWEL", "CONNECTOR", "OTHER"]),
				}),
			),
			e_stiffness: zod.union([zod.number(), zod.null()]).optional(),
			e_test_loading_type: zod
				.union([
					zod.enum(["Cyclic", "Monotonic", "Monotonic and Cyclic"]),
					zod.null(),
				])
				.optional(),
			e_ultimate_displacement: zod.union([zod.number(), zod.null()]).optional(),
			e_ultimate_force: zod.union([zod.number(), zod.null()]).optional(),
			e_yield_displacement: zod.union([zod.number(), zod.null()]).optional(),
			e_yield_force: zod.union([zod.number(), zod.null()]).optional(),
			e_yield_point_method: zod
				.union([zod.enum(["CEN 1/6", "EEEP", "FEMA P795"]), zod.null()])
				.optional(),
			element_dimension: zod.string(),
			fastener_mechanical_properties: zod
				.union([zod.string(), zod.null()])
				.optional(),
			fastener_numbers: zod.number(),
			fastener_types: zod.array(
				zod.object({
					id: zod.uuid().optional(),
					label: zod
						.string()
						.min(1)
						.max(
							specimensReadSpecimensResponseDataItemFastenerTypesItemLabelMax,
						),
				}),
			),
			id: zod.uuid(),
			joinery_type: zod.object({
				has_dowel: zod.boolean(),
				id: zod.uuid().optional(),
				label: zod
					.string()
					.min(1)
					.max(specimensReadSpecimensResponseDataItemJoineryTypeLabelMax),
			}),
			loading_directions: zod.array(
				zod.object({
					id: zod.uuid().optional(),
					label: zod
						.string()
						.min(1)
						.max(
							specimensReadSpecimensResponseDataItemLoadingDirectionsItemLabelMax,
						),
				}),
			),
			moisture_percentage: zod.string(),
			note: zod.union([zod.string(), zod.null()]).optional(),
			practice: zod.enum(["Conventional", "Research and Development"]),
			replicate_tests: zod.number(),
			specimen_reference_id: zod.string(),
			sub_joinery_type: zod.object({
				id: zod.uuid().optional(),
				joinery_type_id: zod.uuid(),
				label: zod
					.string()
					.min(1)
					.max(specimensReadSpecimensResponseDataItemSubJoineryTypeLabelMax),
			}),
			uploader_id: zod.uuid(),
			wood_mechanical_properties: zod
				.union([zod.string(), zod.null()])
				.optional(),
			wood_type: zod.union([zod.string(), zod.null()]).optional(),
		}),
	),
});

/**
 * Submit a new specimen for review.
 * @summary Create Specimen
 */
export const specimensCreateSpecimenBody = zod.object({
	assembly_type: zod.enum([
		"Wall-Floor",
		"Wall-Wall",
		"Wall-Floor & Wall-Wall",
	]),
	connection_description: zod.string(),
	connector: zod.boolean(),
	connector_mechanical_properties: zod
		.union([zod.string(), zod.null()])
		.optional(),
	doi_id: zod.uuid(),
	dowel: zod.boolean(),
	e_date: zod.union([zod.string(), zod.null()]).optional(),
	e_ductility: zod.union([zod.number(), zod.null()]).optional(),
	e_max_displacement: zod.union([zod.number(), zod.null()]).optional(),
	e_max_force: zod.union([zod.number(), zod.null()]).optional(),
	e_measurement_unit: zod.union([zod.string(), zod.null()]).optional(),
	e_qfm_description: zod.union([zod.string(), zod.null()]).optional(),
	e_qualitative_failure_measure: zod.array(zod.uuid()),
	e_stiffness: zod.union([zod.number(), zod.null()]).optional(),
	e_test_loading_type: zod
		.union([
			zod.enum(["Cyclic", "Monotonic", "Monotonic and Cyclic"]),
			zod.null(),
		])
		.optional(),
	e_ultimate_displacement: zod.union([zod.number(), zod.null()]).optional(),
	e_ultimate_force: zod.union([zod.number(), zod.null()]).optional(),
	e_yield_displacement: zod.union([zod.number(), zod.null()]).optional(),
	e_yield_force: zod.union([zod.number(), zod.null()]).optional(),
	e_yield_point_method: zod
		.union([zod.enum(["CEN 1/6", "EEEP", "FEMA P795"]), zod.null()])
		.optional(),
	element_dimension: zod.string(),
	fastener_mechanical_properties: zod
		.union([zod.string(), zod.null()])
		.optional(),
	fastener_numbers: zod.number(),
	fastener_type_ids: zod.array(zod.uuid()),
	joinery_type_id: zod.uuid(),
	loading_direction_ids: zod.array(zod.uuid()),
	moisture_percentage: zod.string(),
	note: zod.union([zod.string(), zod.null()]).optional(),
	practice: zod.enum(["Conventional", "Research and Development"]),
	replicate_tests: zod.number(),
	specimen_reference_id: zod.string(),
	sub_joinery_type_id: zod.uuid(),
	wood_mechanical_properties: zod.union([zod.string(), zod.null()]).optional(),
	wood_type: zod.union([zod.string(), zod.null()]).optional(),
});

export const specimensCreateSpecimenResponse = zod.object({
	changed_by_user_id: zod.uuid(),
	changed_data: zod.record(zod.string(), zod.unknown()),
	comment_by_reviewer: zod.union([zod.string(), zod.null()]).optional(),
	created_at: zod.iso.datetime({}),
	id: zod.uuid(),
	reviewed_at: zod.union([zod.iso.datetime({}), zod.null()]).optional(),
	reviewer_id: zod.union([zod.uuid(), zod.null()]).optional(),
	specimen_id: zod.union([zod.uuid(), zod.null()]).optional(),
	status: zod.enum(["pending", "approved", "rejected"]),
});

/**
 * Delete a specimen.
 * @summary Delete Specimen
 */
export const specimensDeleteSpecimenParams = zod.object({
	id: zod.uuid(),
});

export const specimensDeleteSpecimenResponse = zod.unknown();

/**
 * Get specimen by ID.
 * @summary Read Specimen
 */
export const specimensReadSpecimenParams = zod.object({
	id: zod.uuid(),
});

export const specimensReadSpecimenResponseDoiAuthorsMax = 255;

export const specimensReadSpecimenResponseDoiLinkMax = 255;

export const specimensReadSpecimenResponseDoiRefTitleMax = 255;

export const specimensReadSpecimenResponseEQualitativeFailureMeasureItemLabelMax = 255;

export const specimensReadSpecimenResponseFastenerTypesItemLabelMax = 255;

export const specimensReadSpecimenResponseJoineryTypeLabelMax = 255;

export const specimensReadSpecimenResponseLoadingDirectionsItemLabelMax = 255;

export const specimensReadSpecimenResponseSubJoineryTypeLabelMax = 255;

export const specimensReadSpecimenResponse = zod.object({
	assembly_type: zod.enum([
		"Wall-Floor",
		"Wall-Wall",
		"Wall-Floor & Wall-Wall",
	]),
	connection_description: zod.string(),
	connector: zod.boolean(),
	connector_mechanical_properties: zod
		.union([zod.string(), zod.null()])
		.optional(),
	doi: zod.object({
		authors: zod
			.string()
			.min(1)
			.max(specimensReadSpecimenResponseDoiAuthorsMax),
		id: zod.uuid().optional(),
		link: zod.string().min(1).max(specimensReadSpecimenResponseDoiLinkMax),
		pub_year: zod.number(),
		ref_title: zod
			.string()
			.min(1)
			.max(specimensReadSpecimenResponseDoiRefTitleMax),
	}),
	dowel: zod.boolean(),
	e_date: zod.union([zod.string(), zod.null()]).optional(),
	e_ductility: zod.union([zod.number(), zod.null()]).optional(),
	e_max_displacement: zod.union([zod.number(), zod.null()]).optional(),
	e_max_force: zod.union([zod.number(), zod.null()]).optional(),
	e_measurement_unit: zod.union([zod.string(), zod.null()]).optional(),
	e_qfm_description: zod.union([zod.string(), zod.null()]).optional(),
	e_qualitative_failure_measure: zod.array(
		zod.object({
			id: zod.uuid().optional(),
			label: zod
				.string()
				.min(1)
				.max(
					specimensReadSpecimenResponseEQualitativeFailureMeasureItemLabelMax,
				),
			type: zod.enum(["WOOD", "DOWEL", "CONNECTOR", "OTHER"]),
		}),
	),
	e_stiffness: zod.union([zod.number(), zod.null()]).optional(),
	e_test_loading_type: zod
		.union([
			zod.enum(["Cyclic", "Monotonic", "Monotonic and Cyclic"]),
			zod.null(),
		])
		.optional(),
	e_ultimate_displacement: zod.union([zod.number(), zod.null()]).optional(),
	e_ultimate_force: zod.union([zod.number(), zod.null()]).optional(),
	e_yield_displacement: zod.union([zod.number(), zod.null()]).optional(),
	e_yield_force: zod.union([zod.number(), zod.null()]).optional(),
	e_yield_point_method: zod
		.union([zod.enum(["CEN 1/6", "EEEP", "FEMA P795"]), zod.null()])
		.optional(),
	element_dimension: zod.string(),
	fastener_mechanical_properties: zod
		.union([zod.string(), zod.null()])
		.optional(),
	fastener_numbers: zod.number(),
	fastener_types: zod.array(
		zod.object({
			id: zod.uuid().optional(),
			label: zod
				.string()
				.min(1)
				.max(specimensReadSpecimenResponseFastenerTypesItemLabelMax),
		}),
	),
	id: zod.uuid(),
	joinery_type: zod.object({
		has_dowel: zod.boolean(),
		id: zod.uuid().optional(),
		label: zod
			.string()
			.min(1)
			.max(specimensReadSpecimenResponseJoineryTypeLabelMax),
	}),
	loading_directions: zod.array(
		zod.object({
			id: zod.uuid().optional(),
			label: zod
				.string()
				.min(1)
				.max(specimensReadSpecimenResponseLoadingDirectionsItemLabelMax),
		}),
	),
	moisture_percentage: zod.string(),
	note: zod.union([zod.string(), zod.null()]).optional(),
	practice: zod.enum(["Conventional", "Research and Development"]),
	replicate_tests: zod.number(),
	specimen_reference_id: zod.string(),
	sub_joinery_type: zod.object({
		id: zod.uuid().optional(),
		joinery_type_id: zod.uuid(),
		label: zod
			.string()
			.min(1)
			.max(specimensReadSpecimenResponseSubJoineryTypeLabelMax),
	}),
	uploader_id: zod.uuid(),
	wood_mechanical_properties: zod.union([zod.string(), zod.null()]).optional(),
	wood_type: zod.union([zod.string(), zod.null()]).optional(),
});

/**
 * Submit an update for an existing specimen.
 * @summary Update Specimen
 */
export const specimensUpdateSpecimenParams = zod.object({
	id: zod.uuid(),
});

export const specimensUpdateSpecimenBody = zod.object({
	assembly_type: zod
		.union([
			zod.enum(["Wall-Floor", "Wall-Wall", "Wall-Floor & Wall-Wall"]),
			zod.null(),
		])
		.optional(),
	connection_description: zod.union([zod.string(), zod.null()]).optional(),
	connector: zod.union([zod.boolean(), zod.null()]).optional(),
	connector_mechanical_properties: zod
		.union([zod.string(), zod.null()])
		.optional(),
	dowel: zod.union([zod.boolean(), zod.null()]).optional(),
	e_date: zod.union([zod.string(), zod.null()]).optional(),
	e_ductility: zod.union([zod.number(), zod.null()]).optional(),
	e_max_displacement: zod.union([zod.number(), zod.null()]).optional(),
	e_max_force: zod.union([zod.number(), zod.null()]).optional(),
	e_measurement_unit: zod.union([zod.string(), zod.null()]).optional(),
	e_qfm_description: zod.union([zod.string(), zod.null()]).optional(),
	e_qualitative_failure_measure: zod
		.union([zod.array(zod.uuid()), zod.null()])
		.optional(),
	e_stiffness: zod.union([zod.number(), zod.null()]).optional(),
	e_test_loading_type: zod
		.union([
			zod.enum(["Cyclic", "Monotonic", "Monotonic and Cyclic"]),
			zod.null(),
		])
		.optional(),
	e_ultimate_displacement: zod.union([zod.number(), zod.null()]).optional(),
	e_ultimate_force: zod.union([zod.number(), zod.null()]).optional(),
	e_yield_displacement: zod.union([zod.number(), zod.null()]).optional(),
	e_yield_force: zod.union([zod.number(), zod.null()]).optional(),
	e_yield_point_method: zod
		.union([zod.enum(["CEN 1/6", "EEEP", "FEMA P795"]), zod.null()])
		.optional(),
	element_dimension: zod.union([zod.string(), zod.null()]).optional(),
	fastener_mechanical_properties: zod
		.union([zod.string(), zod.null()])
		.optional(),
	fastener_numbers: zod.union([zod.number(), zod.null()]).optional(),
	fastener_type_ids: zod.union([zod.array(zod.uuid()), zod.null()]).optional(),
	joinery_type_id: zod.union([zod.uuid(), zod.null()]).optional(),
	loading_direction_ids: zod
		.union([zod.array(zod.uuid()), zod.null()])
		.optional(),
	moisture_percentage: zod.union([zod.string(), zod.null()]).optional(),
	note: zod.union([zod.string(), zod.null()]).optional(),
	practice: zod
		.union([zod.enum(["Conventional", "Research and Development"]), zod.null()])
		.optional(),
	replicate_tests: zod.union([zod.number(), zod.null()]).optional(),
	specimen_reference_id: zod.union([zod.string(), zod.null()]).optional(),
	sub_joinery_type_id: zod.union([zod.uuid(), zod.null()]).optional(),
	wood_mechanical_properties: zod.union([zod.string(), zod.null()]).optional(),
	wood_type: zod.union([zod.string(), zod.null()]).optional(),
});

export const specimensUpdateSpecimenResponse = zod.object({
	changed_by_user_id: zod.uuid(),
	changed_data: zod.record(zod.string(), zod.unknown()),
	comment_by_reviewer: zod.union([zod.string(), zod.null()]).optional(),
	created_at: zod.iso.datetime({}),
	id: zod.uuid(),
	reviewed_at: zod.union([zod.iso.datetime({}), zod.null()]).optional(),
	reviewer_id: zod.union([zod.uuid(), zod.null()]).optional(),
	specimen_id: zod.union([zod.uuid(), zod.null()]).optional(),
	status: zod.enum(["pending", "approved", "rejected"]),
});
