/**
 * Generated by orval v8.0.0-rc.2 🍺
 * Do not edit manually.
 * BarkByte
 * OpenAPI spec version: 0.1.0
 */

import type {
	DataTag,
	DefinedInitialDataOptions,
	DefinedUseQueryResult,
	MutationFunction,
	QueryClient,
	QueryFunction,
	QueryKey,
	UndefinedInitialDataOptions,
	UseMutationOptions,
	UseMutationResult,
	UseQueryOptions,
	UseQueryResult,
} from "@tanstack/react-query";
import { useMutation, useQuery } from "@tanstack/react-query";

import type {
	FailureMode,
	FailureModeCreate,
	FailureModes,
	FailuremodeGetModesParams,
	HTTPValidationError,
} from "../../model";
import type { ErrorType } from "../../mutator/custom-instance";
import { customInstance } from "../../mutator/custom-instance";

/**
 * Retrieve failure modes.

Filters:
  - ?dowel=true       -> include FailureMode.type == DOWEL
  - ?connector=true   -> include FailureMode.type == CONNECTOR
  - both true         -> include either type
  - none provided     -> return only WOOD and OTHER
 * @summary Get Modes
 */
export const failuremodeGetModes = (
	params: FailuremodeGetModesParams,
	signal?: AbortSignal,
) => {
	return customInstance<FailureModes>({
		url: `/api/v1/failuremode/`,
		method: "GET",
		params,
		signal,
	});
};

export const getFailuremodeGetModesQueryKey = (
	params?: FailuremodeGetModesParams,
) => {
	return [`/api/v1/failuremode/`, ...(params ? [params] : [])] as const;
};

export const getFailuremodeGetModesQueryOptions = <
	TData = Awaited<ReturnType<typeof failuremodeGetModes>>,
	TError = ErrorType<HTTPValidationError>,
>(
	params: FailuremodeGetModesParams,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof failuremodeGetModes>>,
				TError,
				TData
			>
		>;
	},
) => {
	const { query: queryOptions } = options ?? {};

	const queryKey =
		queryOptions?.queryKey ?? getFailuremodeGetModesQueryKey(params);

	const queryFn: QueryFunction<
		Awaited<ReturnType<typeof failuremodeGetModes>>
	> = ({ signal }) => failuremodeGetModes(params, signal);

	return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
		Awaited<ReturnType<typeof failuremodeGetModes>>,
		TError,
		TData
	> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type FailuremodeGetModesQueryResult = NonNullable<
	Awaited<ReturnType<typeof failuremodeGetModes>>
>;
export type FailuremodeGetModesQueryError = ErrorType<HTTPValidationError>;

export function useFailuremodeGetModes<
	TData = Awaited<ReturnType<typeof failuremodeGetModes>>,
	TError = ErrorType<HTTPValidationError>,
>(
	params: FailuremodeGetModesParams,
	options: {
		query: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof failuremodeGetModes>>,
				TError,
				TData
			>
		> &
			Pick<
				DefinedInitialDataOptions<
					Awaited<ReturnType<typeof failuremodeGetModes>>,
					TError,
					Awaited<ReturnType<typeof failuremodeGetModes>>
				>,
				"initialData"
			>;
	},
	queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useFailuremodeGetModes<
	TData = Awaited<ReturnType<typeof failuremodeGetModes>>,
	TError = ErrorType<HTTPValidationError>,
>(
	params: FailuremodeGetModesParams,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof failuremodeGetModes>>,
				TError,
				TData
			>
		> &
			Pick<
				UndefinedInitialDataOptions<
					Awaited<ReturnType<typeof failuremodeGetModes>>,
					TError,
					Awaited<ReturnType<typeof failuremodeGetModes>>
				>,
				"initialData"
			>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useFailuremodeGetModes<
	TData = Awaited<ReturnType<typeof failuremodeGetModes>>,
	TError = ErrorType<HTTPValidationError>,
>(
	params: FailuremodeGetModesParams,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof failuremodeGetModes>>,
				TError,
				TData
			>
		>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get Modes
 */

export function useFailuremodeGetModes<
	TData = Awaited<ReturnType<typeof failuremodeGetModes>>,
	TError = ErrorType<HTTPValidationError>,
>(
	params: FailuremodeGetModesParams,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof failuremodeGetModes>>,
				TError,
				TData
			>
		>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
} {
	const queryOptions = getFailuremodeGetModesQueryOptions(params, options);

	const query = useQuery(queryOptions, queryClient) as UseQueryResult<
		TData,
		TError
	> & { queryKey: DataTag<QueryKey, TData, TError> };

	query.queryKey = queryOptions.queryKey;

	return query;
}

/**
 * Create failure mode.
 * @summary Create Mode
 */
export const failuremodeCreateMode = (
	failureModeCreate: FailureModeCreate,
	signal?: AbortSignal,
) => {
	return customInstance<FailureMode>({
		url: `/api/v1/failuremode/`,
		method: "POST",
		headers: { "Content-Type": "application/json" },
		data: failureModeCreate,
		signal,
	});
};

export const getFailuremodeCreateModeMutationOptions = <
	TError = ErrorType<HTTPValidationError>,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof failuremodeCreateMode>>,
		TError,
		{ data: FailureModeCreate },
		TContext
	>;
}): UseMutationOptions<
	Awaited<ReturnType<typeof failuremodeCreateMode>>,
	TError,
	{ data: FailureModeCreate },
	TContext
> => {
	const mutationKey = ["failuremodeCreateMode"];
	const { mutation: mutationOptions } = options
		? options.mutation &&
			"mutationKey" in options.mutation &&
			options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey } };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof failuremodeCreateMode>>,
		{ data: FailureModeCreate }
	> = (props) => {
		const { data } = props ?? {};

		return failuremodeCreateMode(data);
	};

	return { mutationFn, ...mutationOptions };
};

export type FailuremodeCreateModeMutationResult = NonNullable<
	Awaited<ReturnType<typeof failuremodeCreateMode>>
>;
export type FailuremodeCreateModeMutationBody = FailureModeCreate;
export type FailuremodeCreateModeMutationError = ErrorType<HTTPValidationError>;

/**
 * @summary Create Mode
 */
export const useFailuremodeCreateMode = <
	TError = ErrorType<HTTPValidationError>,
	TContext = unknown,
>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof failuremodeCreateMode>>,
			TError,
			{ data: FailureModeCreate },
			TContext
		>;
	},
	queryClient?: QueryClient,
): UseMutationResult<
	Awaited<ReturnType<typeof failuremodeCreateMode>>,
	TError,
	{ data: FailureModeCreate },
	TContext
> => {
	const mutationOptions = getFailuremodeCreateModeMutationOptions(options);

	return useMutation(mutationOptions, queryClient);
};
/**
 * Delete failure mode ONLY if not in use.
 * @summary Delete Mode
 */
export const failuremodeDeleteMode = (id: string) => {
	return customInstance<unknown>({
		url: `/api/v1/failuremode/${id}`,
		method: "DELETE",
	});
};

export const getFailuremodeDeleteModeMutationOptions = <
	TError = ErrorType<HTTPValidationError>,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof failuremodeDeleteMode>>,
		TError,
		{ id: string },
		TContext
	>;
}): UseMutationOptions<
	Awaited<ReturnType<typeof failuremodeDeleteMode>>,
	TError,
	{ id: string },
	TContext
> => {
	const mutationKey = ["failuremodeDeleteMode"];
	const { mutation: mutationOptions } = options
		? options.mutation &&
			"mutationKey" in options.mutation &&
			options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey } };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof failuremodeDeleteMode>>,
		{ id: string }
	> = (props) => {
		const { id } = props ?? {};

		return failuremodeDeleteMode(id);
	};

	return { mutationFn, ...mutationOptions };
};

export type FailuremodeDeleteModeMutationResult = NonNullable<
	Awaited<ReturnType<typeof failuremodeDeleteMode>>
>;

export type FailuremodeDeleteModeMutationError = ErrorType<HTTPValidationError>;

/**
 * @summary Delete Mode
 */
export const useFailuremodeDeleteMode = <
	TError = ErrorType<HTTPValidationError>,
	TContext = unknown,
>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof failuremodeDeleteMode>>,
			TError,
			{ id: string },
			TContext
		>;
	},
	queryClient?: QueryClient,
): UseMutationResult<
	Awaited<ReturnType<typeof failuremodeDeleteMode>>,
	TError,
	{ id: string },
	TContext
> => {
	const mutationOptions = getFailuremodeDeleteModeMutationOptions(options);

	return useMutation(mutationOptions, queryClient);
};
/**
 * Update failure mode.
 * @summary Update Mode
 */
export const failuremodeUpdateMode = (
	id: string,
	failureModeCreate: FailureModeCreate,
) => {
	return customInstance<FailureMode>({
		url: `/api/v1/failuremode/${id}`,
		method: "PUT",
		headers: { "Content-Type": "application/json" },
		data: failureModeCreate,
	});
};

export const getFailuremodeUpdateModeMutationOptions = <
	TError = ErrorType<HTTPValidationError>,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof failuremodeUpdateMode>>,
		TError,
		{ id: string; data: FailureModeCreate },
		TContext
	>;
}): UseMutationOptions<
	Awaited<ReturnType<typeof failuremodeUpdateMode>>,
	TError,
	{ id: string; data: FailureModeCreate },
	TContext
> => {
	const mutationKey = ["failuremodeUpdateMode"];
	const { mutation: mutationOptions } = options
		? options.mutation &&
			"mutationKey" in options.mutation &&
			options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey } };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof failuremodeUpdateMode>>,
		{ id: string; data: FailureModeCreate }
	> = (props) => {
		const { id, data } = props ?? {};

		return failuremodeUpdateMode(id, data);
	};

	return { mutationFn, ...mutationOptions };
};

export type FailuremodeUpdateModeMutationResult = NonNullable<
	Awaited<ReturnType<typeof failuremodeUpdateMode>>
>;
export type FailuremodeUpdateModeMutationBody = FailureModeCreate;
export type FailuremodeUpdateModeMutationError = ErrorType<HTTPValidationError>;

/**
 * @summary Update Mode
 */
export const useFailuremodeUpdateMode = <
	TError = ErrorType<HTTPValidationError>,
	TContext = unknown,
>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof failuremodeUpdateMode>>,
			TError,
			{ id: string; data: FailureModeCreate },
			TContext
		>;
	},
	queryClient?: QueryClient,
): UseMutationResult<
	Awaited<ReturnType<typeof failuremodeUpdateMode>>,
	TError,
	{ id: string; data: FailureModeCreate },
	TContext
> => {
	const mutationOptions = getFailuremodeUpdateModeMutationOptions(options);

	return useMutation(mutationOptions, queryClient);
};
